### ISSUE TITLE
Select component broken after clearing

### ISSUE THREAD

**Issue by vascoosx** [rob-balfre/svelte-select#101]
I was experimenting with 

https://svelte.dev/repl/37d7166eac804893b825445b612053fc?version=3.16.4

I noticed the following when trying to clear an item:

1. It doesn't clear it
2. nothing can be selected anymore

**Comment by rob-balfre** [comment]
You have a bug in your code... fixed it 

https://svelte.dev/repl/5f7199c5bd964c49b010e56c5484c154?version=3.16.4
