### ISSUE TITLE
Select component always blurs if instantiated inside shadow dom.

### ISSUE THREAD

**Issue by jpz** [rob-balfre/svelte-select#105]
When processing `handleClickEvent(event)` at the window level, the `event.target` value (on Chrome, where I am testing) does not reference the element that it clicked, if it is within the shadow DOM, as the handler is on the window, outside the shadow DOM, as per:

https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-301/#toc-events

Thus the following guard is never true, and the code always falls through to always blur the input.

```
if (container.contains(event.target)) return;
```

One may however inspect the event.path[0] value, and this does what one would like it to do.

```
const eventTarget = event.path && (event.path.length > 0) ? event.path[0] : event.target
if (container.contains(eventTarget)) return;
```

**Comment by rob-balfre** [comment]
@jpz thanks!

Released in v3.3.6
