### ISSUE TITLE
Setting height variable when using isVirtualList gives unexpected result

### ISSUE THREAD

**Issue by jpz** [rob-balfre/svelte-select#107]
As per here - the dropdown list has some excess whitespace at the end.  

I haven't been able to fix it as I'm not terribly familiar with the code but I thought I'd just report it here.  

I do realise the isVirtualList is marked as experimental btw.

https://svelte.dev/repl/c08ea53edfba4b9889c0b9c94d239ea9?version=3.17.2

**Comment by rob-balfre** [comment]
Thanks, fixed that for you 3.3.7

Just pass the itemHeight to the component...

https://svelte.dev/repl/1f6df8790da544d3924bf5d14f7fdb01?version=3.17.2

**Comment by jpz** [comment]
cheers Rob, I appreciate your help!
