### ISSUE TITLE
Add required field prop

### ISSUE THREAD

**Issue by Taha-Firoz** [rob-balfre/svelte-select#108]
Right now there isn't an easy way to make a field required to ensure that a form isn't submitted without the field being left empty. Could we add this?

**Comment by rob-balfre** [comment]
@Taha-Firoz thanks for the suggestion.  Unfortunately It's a pretty tricky thing to add and best to handle outside of the component.

Two options to try...
https://svelte.dev/repl/1cd3dc9d01754501968d4fa89fde6eb7?version=3.12.1
https://svelte.dev/repl/208edfcc70d34fdc836ad3be2f5a2f94?version=3.12.1

**Comment by Taha-Firoz** [comment]
Yes it works, Thank you?
