### ISSUE TITLE
Question: Allow entered text to be used

### ISSUE THREAD

**Issue by rpersche** [rob-balfre/svelte-select#113]
Hello. Thanks for the great work. I am looking for a component that works like Google Search or Twitter Typeahead. I am using the svelte-select for a search. What I want is that you can submit the text entered without selecting an item. I created a workaround by adding the text entered as first option:

async loadOptions(text) {
  ...
  return [text].concat(suggestions);
}

And then hiding the first option
  :global(.selectParent .first) {
    display: none;
  }

It works unless you type fast and hit Enter fast. 

Is there any nicer way to implement/configure that?

**Comment by JoshuaCrewe** [comment]
I would be interested in this answer as I have taken the same approach @rpersche . Great minds think alike!

**Comment by rpersche** [comment]
@JoshuaCrewe FYI - I use https://leaverou.github.io/awesomplete/  instead for the time being. It's not Svelte but it is lightweight and does what I need.

**Comment by JoshuaCrewe** [comment]
Oh Cool. Not sure about some of the styling they have going on there but nice recomendation. Thanks very much

**Comment by rob-balfre** [comment]
Can you not just `bind:filterText`  ?

**Comment by JoshuaCrewe** [comment]
I had another look into this after your comment Rob. I can access the value of the input using `bind:filterText` but the event is the thing I have been struggling with.

The scenario is, there is the slect element ready for input. When the user types in the box data is fetched and populated. The user can select which item they want (in my case selecting an item changes the URL for that page). It is the space in between typing and fetching data that we are dealing with. The two events we have access to are clearning and selecting. 

If we were able to use the form submit event or something then we could use the value of `filterText` to do something, although I would suspect this would be quite messy.

At the moment typing some content and pressing enter before there are options returned from the ajax request results in no action.

Binding `filterText` is still too late by the looks of things, but then again my Svelte abilities are probably holding me back.

I am trying to get reactive statements to play ball :

```
    let items = [];

    $: items = (filterText) => {
        let array = [];

        array.push({
            label:  filterText,
            value: ''
        });
        return array;
    }
```

But that doesn't run when filterText is updated I don't think.

**Comment by rob-balfre** [comment]
@JoshuaCrewe can you make a REPL please?

**Comment by JoshuaCrewe** [comment]
To be honest, writing this REPL out I am not sure if this is even a good idea.

https://svelte.dev/repl/29545bb26c624d2c94012fef260b489c?version=3.20.1

The idea was to start with nothing in the select. Type a thing which will trigger a Promise to get the options. Before those options come back press enter to do something with what ever was typed in.

The usecase for me (I can't speak for @rpersche is a search box with auto suggestion. The user is looking for a product. Hitting enter before the suggestions sends the user to a search page proper with a grid of results. The select element would go and fetch the products and present them to the user in place.

Does this make sense?

**Comment by rpersche** [comment]
I agree with @JoshuaCrewe. The use case is exactly how Google Search works. You have to be able to type a text (very fast) and hit "Enter", and it should search for that text. In addition, you could select a value from the suggestions.

**Comment by JoshuaCrewe** [comment]
@rpersche this is my usecase for sure but I don't think it is a given that this library facilitate that. It is a little bit of an odd one for a select element perhaps? Why should a select element behave like this ?

(obviously I would like it to but that doesn't count for much!)

**Comment by rpersche** [comment]
@JoshuaCrewe I had the same thought earlier, that what we need it not a "select" element but a typeahead. I am still happy with my https://leaverou.github.io/awesomplete/  solution.

**Comment by rob-balfre** [comment]
Yeah awesomplete is awesome 😄

@JoshuaCrewe https://svelte.dev/repl/136fa2c5a3f84c6c80df654cc38b9aab?version=3.20.1
Does that solve your issue?

**Comment by JoshuaCrewe** [comment]
That answers this question I would say. Thank you so much for taking the time to show us a solution. I have really appreciated the learning experience.

This should be able to feed back into the component I am working on with some additional checks to know when to search and when to select so feeling pretty good about that.

From my perspective I am happy for this issue to be closed 🥇

**Comment by rpersche** [comment]
Also, thank you from me, and for the tip to bind the keyDown on the whole window.
