### ISSUE TITLE
Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by JoshuaCrewe** [rob-balfre/svelte-select#118]
I am looking at IE11 support specifically. I am using this component to fetch data and present a drop down of the returned results from the fetch.

This all works fine except in IE11 which doesn't support promises. We use polyfill.io to handle the lack of Promise support but this doesn't appear to be working on this occasion.

Is it possible to get IE11 support with this component?

**Comment by JoshuaCrewe** [comment]
The `loadOptions` property uses a Promise. Am I handling this wrong ?

```
    async function loadOptions(filterText) {
        loading = true;
        filterText = filterText ? filterText.replace(' ','_') : '';

        let results = [{
            title : {
                rendered : `Search for : ${filterText}`
            },
            link : `${baseURL}/?s=${filterText}&post_type=${type}`
        }];

        let url = `${baseURL}/wp-json/wp/v2/${type}?search=${filterText}`;
        results = fetch(url)
            .then(function(response) {
                if (!response.ok) {
                    throw new Error("HTTP error, status = " + response.status);
                }
                return response.json();
            })
            .then(function(results) {
                console.log(results);
                let json = results;
                loading = false;

                results.push(...json);
                return results;
            })
            .catch(function(error) {
                console.log(error);
            });
        return results;
    }
```

**Comment by JoshuaCrewe** [comment]
OK so updating the loadOptions function to match the example you have in the docs gets around the issue. Which means I am not understanding it
```
    async function loadOptions(filterText) {
        loading = true;
        filterText = filterText ? filterText.replace(' ','_') : '';

        let results = [{
            title : {
                rendered : `Search for : ${filterText}`
            },
            link : `${baseURL}/?s=${filterText}&post_type=${type}`
        }];

        let url = `${baseURL}/wp-json/wp/v2/${type}?search=${filterText}`;
        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url);
            xhr.send();

            xhr.onload = () => {
                if (xhr.status >= 200 && xhr.status < 300) {
                    let json = JSON.parse(xhr.response);
                    console.log('the json' , json);
                    loading = false;
                    results.push(...json);
                    resolve(results);
                } else {
                    console.log('error');
                    reject()
                }
            };
        });
        return results;
    }
```

**Comment by rob-balfre** [comment]
I use Svelte-select in multiple websites that support IE11. We use axios
instead of fetch, bable to compile to ES5 and post-css to convert custom
props to vanilla CSS.

It's a total pain in the 🍑!

Have you got it all working?

**Comment by JoshuaCrewe** [comment]
Thanks for your response!

I got much of it working. So what I do not understand is how to handle `loadOptions` so that I don't get the `Uncaught (in promise) undefined` error.  With the `XMLHttpRequest()` I can see that we can call `resolve()` or `reject()` which seems to satisfy the requirements.

When I was using fetch I did have an error catcher but that didn't avoid the issue. With Axios the promise worked the same as fetch (chaining responses together). How does this function work? What should I be returning ?

I had babel compiling to ES5  ... at least I thought I did. In the end it wasn't handling Svelte properly and I was getting weird errors. I came to the conclusion that it was running the loaders in the wrong order. It appears to be working now but I did rage quit a few times. I have yet to configure post-css yet but it is good to know that it is at least possible.

**Comment by JoshuaCrewe** [comment]
@rob-balfre are you using webpack or rollup in your projects?

I am tearing my hair out a little bit. I basically have two websites with very similar setups. I have got one of them working (with the exception of the postcss step) and it functions well on IE11.

I have used the same webpack and babel config for both but the second one is throwing an error in IE11 `Exception expected :` which is being triggered from `Item.svelte` that is being included via this library. Which is where the head scratching begins.

In your Docs you suggest updating `mainFields` to include svelte files which will include the `.html` rather than the compiles `.mjs`. This fixes a bug I was experiencing that caused the whole component to crash out if the select element was updated by the user. Without updating `mainFields` it all compiles fine in IE11 and the component works well apart from the bug which crashes the component. With an updated `mainFields` I get the console error.

So I thought that I needed to include `.html` files in the svelte => babel loaders, but this did nothing.

How do I fix the error I get in IE11 from `Item.svelte` when compiling via babel? Why do I get this error in one project but not another using the same config?

Internet Explorer doesn't tell me exactly where in Item.svelte the error is triggered but I suspect that the component is not getting compiled by svelte before being passed to babel so it is looking at the `{}` in the template and thinking it is an object?! not sure though.

**.babelrc.js**
```
{
    "presets": [["@babel/preset-env", {
        "targets": {
            "browsers": [
                "ie >= 11"
            ]
        },
        "useBuiltIns": "entry",
        "corejs": 3
    }]],
    "plugins": [
        ["transform-react-jsx", {
            "pragma": "wp.element.createElement"
        }]
    ]
}
```

**webpack.config.js**
```
    resolve: {
        mainFields: ['svelte', 'browser', 'module', 'main'],
        extensions: ['.mjs', '.js', '.svelte'],
        alias: {
            svelte: path.resolve('node_modules', 'svelte'),
        },
    },
    module: {
        rules: [
            {
                test: /\.(svelte|html)$/,
                exclude: /node_modules\/(core-js|@babel)/,
                loader: ['babel-loader', 'svelte-loader'],
            },
            {
                test: /\.(js|mjs)$/,
                exclude: /node_modules\/(core-js|@babel)/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: mix.config.babel(),
                    },
                ],
            },
        ],
    },
```

**Component.svelte**
```
<script>
    import { onMount } from 'svelte';

    import axios from 'axios';
    import Select from 'svelte-select';

    // This is the prop which gets passed to the component
    export let data;

    // This will handle our state
    let loading = false;

    // Pull out the data we will be using from props
    let id = data.default_file.uploaded_to;
    let name = data.default_file.title;
    let url = data.default_file.url;

    // Set the default options for the select
    let options = [{
        value: 'default',
        label: 'English'
    }];

	onMount(() => {
        // If we have other files
        if (data.files.length > 0) {
            data.files.forEach(file => {
                // Set their languages ad the select options
                options.push({
                    value: file.language.value,
                    label: file.language.label
                })
            })
        }
	});

    function handleSelect(SelectedValue) {
        // Get the language selected
        const language = SelectedValue.detail.value;

        // Set the state to loading
        loading = true;

        // Fetching the information about that download
        // functions/rest/download.php
        axios
            .get(`/wp-json/project/v1/download/${id}?language=${language}`)
            .then(function (response) {

                // Pull out the data we want from the response
                const data = response.data.data.file;

                // Reassign the data on the download
                // (This will be synced to the view automatically as they are
                // linked in the template)
                name = data.title;
                url = data.url

            })
            .catch(function (error) {

                // If there is an error we can do more things here
                // Like set error styles
                console.log(error);
            })
            .then(function () {
                // Remove the loading state
                loading = false;
            });
    }
</script>

         <Select items={options} on:select={handleSelect} isClearable={false} placeholder="Looking for another Language?" showChevron={true}></Select>

**Comment by JoshuaCrewe** [comment]
I think I am going to pack in the whole programming role. I fancy becoming a potter or a gardener again.

Forcing babel loader to load the babelrc config solved the issue on this occasion. I have no idea why the other project didn't need it but this one did.

```
            {
                test: /\.(svelte)$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: mix.config.babel(),
                    },
                    {
                        loader: 'svelte-loader',
                    },
                ],
            },
```

**Comment by silllli** [comment]
I encountered the same problem: adding a `Promise` polyfill outside of Svelte via `polfyfill.io` did not work here. Adding the polyfill using `core-js` in Babel solved it.

Thank you @JoshuaCrewe for pointing in the right direction.
