### ISSUE TITLE
CSS Variable --padding on .selectContainer

### ISSUE THREAD

**Issue by andeeplus** [rob-balfre/svelte-select#123]
Hi people, great and essential stuff here!

I'm writing you because trying to style the selectContainer I've noted that --padding cannot be controlled from outside.

The issue seems related to the way --padding is declared inside .selectContainer{}.
I've seen also that in previous branches the .selectContainer class was set differently from how it is now on the master branch.

NOW:
 `.selectContainer {
    --padding: 0 16px;
    ...
    padding: var(--padding);
   ...
  }`

BEFORE:
`  .selectContainer {
    ...
    padding: var(--padding, 0 16px);
    ...
  }`

I've just did a test updating the library in my local machine using the second example and everything work as expected. 

Is it just a simple bug or there is some reason behind this change?

Thanks a lot

**Comment by rob-balfre** [comment]
Change was intentional - not a bug.
Can you create a REPL of the problem you're trying to solve please.

**Comment by andeeplus** [comment]
Basically I'm just trying to give the right padding to the input.

**Comment by andeeplus** [comment]
Hi Rob, thanks for answering.

I've tried to reproduce it on REPL but without success.
In REPL it works correctly.
Anyway this is the behaviour I'm experiencing.

![Screen Shot 2020-04-21 at 17 25 25](https://user-images.githubusercontent.com/13163970/79884596-a5328880-83f5-11ea-8fff-b27c7693d0b3.png)

As you can see the padding used in the class "themed" is not actually overriding the original.

I do not have any other libraries installed nor any global variable declared.

**Comment by rob-balfre** [comment]
`.selectContainer` and the `.selectContainer input` share the same padding css var. To override just do this:

```
.themed :global(.selectContainer),
.themed :global(.selectContainer input)
 {
    --padding: 0 0.5rem;
}
```

Bit of a hack but I've avoiding a breaking change until the next major version.

**Comment by andeeplus** [comment]
Ok, in the meanwhile It works,
Thanks Rob

**Comment by aktxyz** [comment]
this line is also causing some issues for me as well

```
--padding: 0 16px
```

With svelte + svelte-kit ... this line is preventing my override in the theme from taking affect.
You mention the change to add this was intentional, curious what the reason was?

Using chrome dev tools, I see the following ... clicking the checkbox next to the ```--padding``` property (do disable it) allows my custom theme ```--padding``` to take affect.
```
.selectContainer.s-322NloBWXWsQ.s-322NloBWXWsQ {
    --padding: 0 16px;
    border: var(--border, 1px solid #d8dbdf);
    border-radius: var(--borderRadius, 3px);
    height: var(--height, 42px);
    position: relative;
    display: flex;
    align-items: center;
    padding: var(--padding);
    background: var(--background, #fff);
}
```

https://github.com/rob-balfre/svelte-select/blob/c2a7b53c14819b0d3c7eb649256416d4d2a3a74f/src/Select.svelte#L652

I have worked around it so no biggie, great component ... so thank you for your work !
