### ISSUE TITLE
Feature request: add a focus method

### ISSUE THREAD

**Issue by EmrysMyrddin** [rob-balfre/svelte-select#127]
Hi, thank for this amazing component !

It could be great to have a simple way to programatically manage the focus.

Here is an example of what I need:

```svelte
<script>
	import Select from 'svelte-select'

	let select
</script>

<Select bind:this={select} />
<button on:click={() => select.focus()}>Focus</button>
```

If you already have a way to manage the focus, let me know, I have perhaps missed it...

I have tried to do this but it doesn't work:

```svelte
<script>
	import Select from 'svelte-select'

	let selectInput
</script>

<Select bind:input={selectInput} />
<button on:click={() => selectInput.focus()}>Focus !</button>
```

**Comment by rob-balfre** [comment]
@EmrysMyrddin Does this do the trick?

https://svelte.dev/repl/fabd0a84b1b244f2925c1431ae9ec4c5?version=3.12.1

**Comment by EmrysMyrddin** [comment]
Yes it seems to work, even if it doesn't open the select.

But perhaps it could be a better api to have a focus method doing this instead of messing with internal props ?

**Comment by rob-balfre** [comment]
REPL updated...
https://svelte.dev/repl/fabd0a84b1b244f2925c1431ae9ec4c5?version=3.12.1
