### ISSUE TITLE
Multi select initial values

### ISSUE THREAD

**Issue by mgholam** [rob-balfre/svelte-select#131]
In multi select mode only the first initial value is showing (i.e. 'One'):
```js
const items = ['One', 'Two', 'Three', '4'];
var ms = ['One',  '4']
<Select items={items} isMulti={true} bind:selectedValue={ms}></Select>
```

**Comment by rob-balfre** [comment]
Looks like a bug with simple arrays and `isMulti`.

Works fine with collections...
https://svelte.dev/repl/8119ccc4d7124605908530af37585ccd?version=3.20.1

Will keep open to remind me to fix this! Thanks

**Comment by oharsta** [comment]
In https://github.com/rob-balfre/svelte-select/pull/161 - which adds the ability to have a custom chevron indicator - I also included a fix for this issue.

**Comment by rob-balfre** [comment]
@oharsta thanks for that!! 🙏
