### ISSUE TITLE
Custom HTML `autocomplete` attribute

### ISSUE THREAD

**Issue by silllli** [rob-balfre/svelte-select#132]
When a searchable `svelte-select` component is being used inside a `<form>` element, clicking on it will trigger the autocomplete function of the browser (and cover `svelte-select`).

It may be useful to pass an `autocomplete` property to the component?

**Comment by silllli** [comment]
Oh sorry, I just saw that it actually is set to `off`. The problem is that at least Chrome ignores the attribute being set to `off`. One workaround is setting it to something different than `off` (preferably a word that wouldn’t be used as an input id).

The problem now is, a different value passed via `inputAttributes` will be ignored.

**Comment by rob-balfre** [comment]
Can't you just set `autocomplete="off"` on the `<form>` element instead? 

Can you create a REPL for the issue please.

**Comment by silllli** [comment]
You are right, this should work. The problem seems to be Chrome.

The autocomplete dropdown sometimes appears, depending on the layout, scroll position… the weather—I don’t know. When I tried it in a REPL, it wouldn’t come up at all. Anyways, for now it doesn’t seem to be related to `svelte-select` since the other, regular inputs are also affected.
