### ISSUE TITLE
The z-index of selectionContainer is fixed to 2

### ISSUE THREAD

**Issue by KiwiJuicer** [rob-balfre/svelte-select#134]
As per this [code-line](https://github.com/rob-balfre/svelte-select/blob/c508eb602604988eccbe21a53efeff6fe07fdd86/src/Select.svelte#L534) the z-index is forced to 2 and I cannot increase it when using the component.

Is there a way? I have higher z-indexes on the page I render.

**Comment by rob-balfre** [comment]
I think all you need is a container div with `position: relative; z-index: XX;`

https://svelte.dev/repl/66fce47444b8471ab6760f8076c9368f?version=3.12.1
