### ISSUE TITLE
http-proxy DOS vulnerability

### ISSUE THREAD

**Issue by ajdegol** [rob-balfre/svelte-select#135]
Hi there, on a recent npm install there was a warning of a high severity vulnerability; running `npm audit` turned up this : https://www.npmjs.com/advisories/1486

Seems like an alternative to http-proxy may be required.

**Comment by rob-balfre** [comment]
It's only for testing, those deps should never get to your compiled app

**Comment by heardy** [comment]
Hi @ajdegol, as far as I can see `http-proxy` isn't used.

Also `npm audit` has 0 vulnerabilities for me.

<img width="382" alt="Screen Shot 2020-05-20 at 8 08 08 am" src="https://user-images.githubusercontent.com/678392/82383513-510cd980-9a71-11ea-92af-b51ca58f4dad.png">

**Comment by ajdegol** [comment]
Okay, great stuff.
