### ISSUE TITLE
No event dispatched on new item created via loadOptions

### ISSUE THREAD

**Issue by timgblack** [rob-balfre/svelte-select#136]
I'm loading the list via a server call and the selecting an option, but not getting selectedItem set nor any events fired indicating an item is created.

Is there a correct way to do this, or is this as of yet unsupported?

I'm running the most recent version from npm.

**Comment by rob-balfre** [comment]
Should work. on:select={handleSelect}

**Comment by timgblack** [comment]
Thanks Rob, I tested using a real browser (not my phone's) and found event.detail which does the trick - and as I was removing selectedItem, I realised I'd forgotten to bind: it - oops! I appreciate the prompt response.
