### ISSUE TITLE
Enter on empty input selects the first groupHeaderTitle

### ISSUE THREAD

**Issue by KiwiJuicer** [rob-balfre/svelte-select#137]
When using groupHeaders and you hit Enter on an empty input, it will select the first groupHeader.
This is not intended as it should check if it isGroupHeader and isGroupHeaderSelectable and actually not select anything.

Is there a way around this or is a bugfix needed?

**Comment by rob-balfre** [comment]
@KiwiJuicer yep, that's a bug 😭

**Comment by rob-balfre** [comment]
@KiwiJuicer thanks for that, fix released v3.7.1
