### ISSUE TITLE
bind:selectedValue fires multiple times when adding values to multi-select

### ISSUE THREAD

**Issue by brettdawkins** [rob-balfre/svelte-select#140]
I'm not sure if this is the expected behavior

Set the Select to isMulti and bind:selectedValue then console.log(selectedValue). I would assume that the selectedValue to change only once when adding a new value to the multiselect - yet it triggers multiple changes when you add a new item to the multi select.  If you check the REPL below and add all items to the mutli-select you will see in the console log this below:

> 2x  Array(1)[ Object { … } ]
5x  Array(2)[ Object { … } , Object { … } ]
5x  Array(3)[ Object { … } , Object { … } , Object { … } ]
5x  Array(4)[ Object { … } , Object { … } , Object { … } , Object { … } ]
5x  Array(5)[ Object { … } , Object { … } , Object { … } , Object { … } , Object { … } ]
5x  Array(6)[ Object { … } , Object { … } , Object { … } , Object { … } , Object { … } , … ]
5x  Array(7)[ Object { … } , Object { … } , Object { … } , Object { … } , Object { … } , … ]
5x  Array(8)[ Object { … } , Object { … } , Object { … } , Object { … } , Object { … } , … ]
8x  Array(9)[ Object { … } , Object { … } , Object { … } , Object { … } , Object { … } , … ]
3x  Array(10)[ Object { … } , Object { … } , Object { … } , Object { … } , Object { … } , … ]

I've also had it producing endless loops if I try to use something like $: item = selectedValue when using the multi-select.
 
[REPL](https://svelte.dev/repl/6672c34330b244228045bcf8fd6e403e?version=3.12.1)

If you watch the console - you can see that the bound value updates many times. Is this expected or is there a bug?

**Comment by rob-balfre** [comment]
Nah, it's just Svelte internals working through updates. Best to use `on:select` https://svelte.dev/repl/79703a088c144b27b88ba9b60cd49f75?version=3.12.1

**Comment by brettdawkins** [comment]
Awesome ;-)
