### ISSUE TITLE
how to add many svelte-select in a same component

### ISSUE THREAD

**Issue by b3b00** [rob-balfre/svelte-select#142]
I  have hard time trying to add 2 svelte-select in a same svelte component. As there is only 1 bind:selectedValue how can I use binding with 2 selects ? If one is set then the other will get the same value as in : 
[many svele-select in a component](https://svelte.dev/repl/f74fc868f8c74d31834b9a42f6b0a7c3?version=3.22.3)

I could use the on:select approach but it's quite dull and it would really be usefull to be able to use all svelte native features.

Is there already a way to do what I want , or would it be a new feature ? if it's a new feature I would be glad to help you.

**Comment by b3b00** [comment]
solved by myself, too idiot

**Comment by JoseThen** [comment]
Hey @b3b00 I'm curious as to what you used? I'm hitting this issue myself.

**Comment by JoseThen** [comment]
Nevermind I am also an idiot 😆 , for anyone who hits this issue just add


```
<script>
  import Select from 'svelte-select';
  let someValue = undefined;
  let otherValue = undefined;
</script>

<Select items={someItem} bind:selectedValue={someValue} />
<Selectitems={otherItem} bind:selectedValue={otherValue} />
```

Notice how I assigned a value to `bind:selectedValue`
