### ISSUE TITLE
Focused state is never reset

### ISSUE THREAD

**Issue by http-teapot** [rob-balfre/svelte-select#148]
Selecting an option then clearing the option adds classes `selectContainer focused` on the wrapper element of `input`. Repeating the process appends the classes to the already existing classes. The screenshot below is more explicit.

<img width="457" alt="Screen Shot 2020-06-02 at 9 00 18 PM" src="https://user-images.githubusercontent.com/1534519/83594572-6b848f80-a514-11ea-8c9c-6d184e323d86.png">

Reproducible on the demo: https://svelte.dev/repl/a859c2ba7d1744af9c95037c48989193?version=3.12.1

**Comment by rob-balfre** [comment]
@http-teapot thanks! Fixed svelte-select@3.8.1
