### ISSUE TITLE
Add option to map `selectedValue` to `option[optionIdentifier]`

### ISSUE THREAD

**Issue by http-teapot** [rob-balfre/svelte-select#149]
I couldn't find an option related to this. The library is able to select an option based on a string but then binds the full option `{ value: string; label: string }` back. It'd be great to have a parameter or a binding that only returns the value and not the full option.

```html
<script>
  let items = [{ value: "foo", label: "F00" }, { value: "bar", label: "B4r" }];
  let selectedValue;
  $: console.log(selectedValue); // print "foo" instead of { value: "foo", label: "F00" }
</script>

 <!-- with parameter -->
 <Select  {items} valueOnly={true} bind:selectedValue />

<!-- with binding -->
 <Select {items} bind:value={selectedValue} />
```

It would ideally work with multi-selection as well.

It might create a wrapper component for that purpose actually. It might be the cleanest if the goal of `svelte-select` is to remain as flexible as possible. I am submitting this issue as a reference if others stumbling upon it.

**Comment by http-teapot** [comment]
Despite having to declare the same props as the component, the solution is actually pretty good. On top of that, I can add my custom CSS variables.

```html
<script>
  /**
   * Instead of returning `{ value: "foo", label: "F00" }`
   * the component returns `foo`.
   */
  import Select from "svelte-select/src/Select.svelte"; // You might need to import differently.

  export let items;
  export let value; // string or string[]
  export let placeholder;

  export let isMulti = false;
  export let isSearchable = false;

  let selectedValue;
  $: {
    if (Array.isArray(value)) {
      // value is ['foo', 'bar']
      selectedValue = items.filter(item => value.includes(item.value));
    } else if (value) {
      // value is 'foo'
      selectedValue = items.find(item => item.value === value);
    }
  }

  function onSelect(event) {
    if (!event.detail) {
      return;
    }
    if (Array.isArray(value)) {
      value = event.detail.map(opt => opt.value);
    } else {
      value = event.detail.value;
    }
  }
</script>

<Select
  {items}
  {selectedValue}
  {isSearchable}
  {isMulti}
  {placeholder} 
  on:select={onSelect} />
```

Obviously you may need to customize to your needs as I've probably not tested for every scenarios.

**Comment by rob-balfre** [comment]
@http-teapot I'd just use a reactive statement but happy you found a solution that works.  
https://svelte.dev/repl/2ba74bda59d4439dafc602ecb0fba89d?version=3.12.1

Can I close this?

**Comment by http-teapot** [comment]
I had about seven select element on the page so using reactive statement ended up being too verbose for my taste

Yes, the issue can be closed, thank you!

**Comment by nickyhajal** [comment]
@http-teapot Thanks for this! IMO it makes so much more sense to handle that transformation in the component instead of having to do it over and over throughout an app.
