### ISSUE TITLE
Forward on:focus event

### ISSUE THREAD

**Issue by dydx-git** [rob-balfre/svelte-select#150]
```
<Select
        placeholder="Select Item"
        on:blur="{() => console.log('got focus')}"
        on:focus="{() => console.log('got focus')}" />
```

Please allow forwarding these events from the component to the parent as this code above does not work.

**Comment by ConProgramming** [comment]
@dydx-git Did you find a solution to this?

**Comment by dydx-git** [comment]
> @dydx-git Did you find a solution to this?

@ConProgramming Yes, you can see how the focus works here: https://svelte.dev/repl/fabd0a84b1b244f2925c1431ae9ec4c5?version=3.12.1

**Comment by TylerRick** [comment]
Hmm. Is there an easy way to convert `bind:isFocused bind:listOpen` into events (`on:focus on:blur` from your example above) that trigger when they become true?

**Comment by TylerRick** [comment]
I guess we could always add a bunch of adapter code to watch the flag and trigger a callback when it becomes true or false...
```js
	const watchForOnFocus  = whenValueBecomes(isFocused, true, onFocus)
	const watchForOnBlur  = whenValueBecomes(isFocused, false, onBlur)
	$: watchForOnFocus(isFocused)
	$: watchForOnBlur(isFocused)
```
([REPL](https://svelte.dev/repl/2024292df9c7479ab8ca6544445dbdc8?version=3.12.1))

... but would it be reasonable to expect svelte-select to handle that so that consumers of this lib don't have to do all that?

**Comment by TylerRick** [comment]
If there's a possibility of adding that, maybe we could reopen this issue?

**Comment by TylerRick** [comment]
Just checked the code and noticed that it's already tracking and diffing against the previous value of `isFocused`:
```js
    if (isFocused !== prev_isFocused) {
      if (isFocused || listOpen) {
        handleFocus();
      } else {
        resetFilter();
        if (input) input.blur();
      }
    }
```

So it should be pretty trivial to have it also emit those events for any consumer who wants to listed for them, right?

```js
    if (isFocused !== prev_isFocused) {
      if (isFocused || listOpen) {
        handleFocus();
        dispatch('focus')
      } else {
        resetFilter();
        if (input) input.blur();
        dispatch('blur')
      }
    }
```
