### ISSUE TITLE
selectedValue as empty collection for multi select

### ISSUE THREAD

**Issue by lkalinowski** [rob-balfre/svelte-select#151]
When removing all selections `selectedValue` is set to `undefined`

What you think about setting it to empty collection when using `isMulti={true}` ?

For example in my case initial selectedValue value is `[]` - because I'm relying on API data. I compared that with JSON:API and it says about `empty array ([]) for empty to-many relationships` is desired value. I thought it might me pretty useful change.

**Comment by ak5** [comment]
Is there another solution for this? I am running into this issue and still get undefined for isMulti=true fields

**Comment by martinbaste** [comment]
Why is this closed? It was fixed in edugadges's fork, but not this one.
