### ISSUE TITLE
Ability to hide options list until filterText supplied

### ISSUE THREAD

**Issue by caschbre** [rob-balfre/svelte-select#152]
Is there a way to keep the list of options closed until the user begins entering filterText?  I may have missed an API option and haven't figured out a way to keep the list of options hidden until the user begins entering filterText.  I tried binding the listOpen property but that seems to get overridden by the Select widget.

The only way I've been able to do this is pass the list of options through loadOptions() and return no results when the user has not typed any filterText... however that means the custom loadOptions function needs to handle the filtering as well.

**Comment by rob-balfre** [comment]
Only way I can think this can work without internal changes is...
https://svelte.dev/repl/8ff2399c31dc4f4c9ddc49ca87d422cb?version=3.12.1

**Comment by caschbre** [comment]
Yep, that works better than handling it through loadOptions(). Thanks!
