### ISSUE TITLE
Placement as inline-block

### ISSUE THREAD

**Issue by ianengelbrecht** [rob-balfre/svelte-select#153]
I'd like to have Select in line with some other elements. I've placed it inside a div with a class that includes display:inline-block. When Select is clear it is offset upwards. When I make a selection then it corrects its position to be inline with the others. See screenshots below. I have also set width in the class, but there is no other css applied.  

![image](https://user-images.githubusercontent.com/9418787/84915477-238d6d00-b0bd-11ea-942a-7a32a580c28c.png)

![image](https://user-images.githubusercontent.com/9418787/84915584-43249580-b0bd-11ea-9be6-38e9bef40583.png)

**Comment by rob-balfre** [comment]
Check out the CSS custom props (CSS vars) available for svelte select. You
should be able to style it the way you want.

**Comment by mckennajones** [comment]
I'm having the same issue that was outlined by @ianengelbrecht. Can you clarify which CSS vars you are referring to @rob-balfre ? I'm not seeing any that seem to be related to [placement here](https://github.com/rob-balfre/svelte-select/blob/master/docs/theming_variables.md). Thanks!
