### ISSUE TITLE
on:select doesn't support custom parameter

### ISSUE THREAD

**Issue by zigots007** [rob-balfre/svelte-select#155]
Hello There,

I really thanks for your works specially for Async Select in  svelte.

This is my current situation : 
I have table with dynamic row count. each row has sync Select that fetch an API.

how I can have multiple selectedValue on each row?

my expectation: 

> let selectedValues = [];
> //selectedValues is an array that contains selectedValue from each Select on each row

I hope I can have selectedValues in array

thanks

**Comment by rob-balfre** [comment]
@zigots007 not sure I understand. I think this is more a Svelte/JS question than about svelte-select. 

Cant you just assign selectedValue to a different variable name?

`<Select bind:selectedValue={foo} ...>`

**Comment by zigots007** [comment]
I am sorry for my bad English due to I am not a native speaker.

here is the screenshot of my layout in svelte
[https://pasteboard.co/JeZgT5c.png](url)

I just found the solution to the my problem.
I created an array (`_selectedProduct`) that contains each selectedValue of each row in the table.

`<Select {loadOptions} {optionIdentifier} {getSelectionLabel} {getOptionLabel} {Item}  placeholder="Cari Nama Produk" on:select={handleSelectProduct} on:clear={handleClearProduct} {noOptionsMessage}></Select>`

_selectedProduct = [];

```
function handleSelectProduct(selectedVal) {
    _selectedProduct.push(selectedVal.detail.product_id);
    _isProductSelected[itemLength] = true;
    getSatuanPerProduct(selectedProduct);
  }
```


Thanks for creating easiest and fastest select component for svelte!

regards,

Ulir

**Comment by rob-balfre** [comment]
You're very welcome 😊 glad you found a solution
