### ISSUE TITLE
Searching for items changes component's position

### ISSUE THREAD

**Issue by HotStealer** [rob-balfre/svelte-select#157]
Problem is the hopping that happens when you start typing in select:

![svelte_select_problem](https://user-images.githubusercontent.com/45164780/86459373-5aa38580-bd2f-11ea-9eed-2562ad5704cd.gif)

If I remove .selectContainer position:absolute it doesn't do that anymore but that pushes selected name off the select input: 

![image](https://user-images.githubusercontent.com/45164780/86459704-e0bfcc00-bd2f-11ea-8c65-92395f5ab22d.png)

How to prevent that from happening?

**Comment by rob-balfre** [comment]
Hard to debug without a code sample. Can you share a REPL showing the issue
please.

**Comment by HotStealer** [comment]
Here's a link to the REPL
[REPL](https://svelte.dev/repl/77a6e4d4049e44268902292cd292214a?version=3.12.1)

**Comment by rob-balfre** [comment]
@HotStealer I don't have any experience with tailwind but with CSS always avoid inline-blocks and use flex or grid instead.

https://svelte.dev/repl/1377d718e8da4ea9be25c6be118c9089?version=3.12.1

Tailwind has docs for flex here but if you want some advice, it's usually easier to write CSS by hand these days.
https://tailwindcss.com/docs/flex/
