### ISSUE TITLE
Property to force show the chevron indicator

### ISSUE THREAD

**Issue by oharsta** [rob-balfre/svelte-select#159]
The current - undocumented - property showChevron forces the chevron indicator to be shown if there is no selectedValue. I have the design requirement to always show the - custom styled - chevron indicator. In pull request https://github.com/rob-balfre/svelte-select/pull/158 I have added the property showIndicator that will force the chevron indicator to be shown regardless of there is a value selected.

**Comment by rob-balfre** [comment]
Released in v3.9.0 thanks
