### ISSUE TITLE
Async Select with initial value

### ISSUE THREAD

**Issue by zigots007** [rob-balfre/svelte-select#160]
How I can set initial value in async select?
`<script>
let selectedValue = 3
</script>`
`<Select {loadOptions} bind:selectedValue {optionIdentifier} {getSelectionLabel} {getOptionLabel} {Item}  placeholder="Cari Nama Produk" on:select={handleSelectProduct} on:clear={handleClearProduct} {noOptionsMessage}></Select>`

**Comment by rob-balfre** [comment]
@zigots007 please create a REPL example, thanks

**Comment by zigots007** [comment]
[https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1](https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1)

I am following your REPL example, I have no idea how to create `selectedValue` for Async Select (based on your REPL)

thanks

**Comment by rob-balfre** [comment]
Here you go @zigots007 

https://svelte.dev/repl/0331e47f852740c0b66acc3155bf01e8?version=3.20.1

**Comment by zigots007** [comment]
thank you so much.
you always make my day much much much easier!
