### ISSUE TITLE
Support for <label for="">

### ISSUE THREAD

**Issue by AnandChowdhary** [rob-balfre/svelte-select#162]
In an HTML `<select>`, we can do this:

```html
<label for="example">Example input</label>
<select id="example">...</select>
```

In this case, clicking on the label focuses the select element, an important accessibility feature. However, there is no way to do this with `svelte-select`:

```html
<script>
  import Select from "svelte-select";
</script>

<label for="example">Example input</label>
<Select id="example" items={[]} />
```

Maybe we can `export let id` within the selector, which is then added to the input element?

**Comment by rob-balfre** [comment]
@AnandChowdhary already possible, see docs... `inputAttributes`

**Comment by AnandChowdhary** [comment]
Thanks!
