### ISSUE TITLE
Multiple Instances bind issue

### ISSUE THREAD

**Issue by andrewb1974** [rob-balfre/svelte-select#164]
I have two Select components declared in the same svelte file like this:

`<Select on:select={handleSelect1} items={items1} bind:selected1 isMulti={false}/>`
...
`<Select on:select={handleSelect2} items={items2} bind:selected2 isMulti={true}/>`

items1 and items2 start off with the same data, selecting an item in one removes an item from the other. This functionality is fine, and I can determine the selected items through the on:select handlers.

However, I am having trouble with the bind: it only works when I use bind:selectedValue, and it does not work of course work if I assign selectedValue to both bind:

Is this an issue or is there something else I should be doing to achieve this, as currently I would only be able to assign initially selected values to one Select.

If the mitigation is to create a custom svelte component to hold the Select, then so be it, but I just wanted to explore if there are any easier fixes.

**Comment by rob-balfre** [comment]
@andrewb1974 can you replicate the issue in a REPL please. Thanks

**Comment by andrewb1974** [comment]
@rob-balfre 

I certainly can.

https://svelte.dev/repl/9d80da054f0248caa8a0d71be4b0082a?version=3.6.7

Thanks,

Andrew

**Comment by vcheeze** [comment]
I seem to be experiencing the exact same issue.

**Comment by rob-balfre** [comment]
https://svelte.dev/repl/85f0f439dca648efb6b39c233e0e6991?version=3.6.7

`bind:selectedValue` is shorthand for `bind:selectedValue={selectedValue}`

see https://svelte.dev/docs#bind_element_property

**Comment by andrewb1974** [comment]
@rob-balfre 

Excellent that's solved it.

Thank you.

Andrew
