### ISSUE TITLE
Congratulations and some thoughts

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#165]
First of all: CONGRATULATIONS FOR THIS PROJECT! **It's AMAZING!**

Some notes:

1. adding `svelte-select` to my project increased bundle size of 40 KB: is there a way to three-shake (I'm not using the Virtual List option and still have ~5 KB in my final bundle coming from `VirtualList.svelte`)? I'm using `sveltejs/template` project BTW

1. I know I can use CSS variables to style it, but is there a chance to have every component with no style at all? Can we use `classes` on each element? In this way we can style using our own CSS framework / CSS rules

Thanks again. :smile:

**Comment by rob-balfre** [comment]
@frederikhors  thanks. 

1. Yeah the bundle size annoys me too. Not sure of a nice backwards compatible option for removing VirtualList from the bundle unless required.

2. You can override any of the styles with good old CSS but no plans to have a style-less approach I'm afraid.

**Comment by rob-balfre** [comment]
Gonna close for now
