### ISSUE TITLE
UX messages when no search text at all

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#166]
I think we should have two messages:

1. `noOptionsMessage` like it is right now, but to show only when no options are available but something is searched

1. `stillNoSearchMessage` (or what you like) to display if still no search is made at all (eg.: "Write something, please...")

What do you think?

Some people may think that the first message displayed before they start writing something already has the meaning of: "no option available for you, you can also avoid searching".

I refer mainly to the use in "async" mode.

**Comment by rob-balfre** [comment]
Can't this be done externally by changing the `noOptionsMessage` value in the async method?

**Comment by frederikhors** [comment]
I'm using this code and it doesn't change when I write something with no options available. It only changes when I click outside, and then that message isn't needed anymore.

```svelte
<script>
  import Select from 'svelte-select'

  const loadOptions = async (filterText) => {
    if (filterText) {
      noOptionsMessage = 'No options'
    }
    return new Promise((resolve, reject) => {
      ...
    })
  }

  let noOptionsMessage = 'Write something, please...'
</script>

<Select
  ...
  {noOptionsMessage}
  isSearchable
  {loadOptions}
  bind:selectedValue />
```

Can you please suggest something?

**Comment by rob-balfre** [comment]
@frederikhors should work now hopefully. v3.10.1
