### ISSUE TITLE
Make required working

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#167]
In the issue https://github.com/rob-balfre/svelte-select/issues/108 you said:

> Unfortunately It's a pretty tricky thing to add and best to handle outside of the component.

Can I ask you why?

Can we just set the input value to something and let browser input's `required` prop do its job?

I'm using:

```svelte
inputAttributes={{ id: 'player', required: true }}
```

and for the browser it's always empty.

**Why?**

**Comment by rob-balfre** [comment]
There is no `<input>` to set required on. The internal input field is used for searching list items not recording the selected value. `selectedValue` is an internal prop not an DOM element so adding `required` would do nothing.

**Comment by andreasnuesslein** [comment]
@frederikhors look:  https://github.com/rob-balfre/svelte-select/issues/214#issuecomment-746589030
