### ISSUE TITLE
Mildly confusing naming issue

### ISSUE THREAD

**Issue by uriberto** [rob-balfre/svelte-select#168]
Awesome project, thanks!

A small note: Your variable called selectedValue actually keeps the pair {value:X,label:Y}, when I would have expected (because of the name) that it would have just the value X. Perhaps change that row of the table in the docs to show that it's not "Selected value(s)", but rather "selected item(s)"

**Comment by rob-balfre** [comment]
Value was chosen instead of items as HTML inputs bind to `value`. Changing it now would be a breaking change.  Why don't you do `bind:selectedValue={selectedItems}` 😸

**Comment by uriberto** [comment]
I want suggesting changing the variable name. I was suggesting making a very minor change to the readme to clarify.

**Comment by rob-balfre** [comment]
Cool, will do. Reformatting the readme is in progress actually 🤓
