### ISSUE TITLE
containerClasses not working

### ISSUE THREAD

**Issue by sainzg** [rob-balfre/svelte-select#174]
<Select containerClasses="myclass" />

The class is not being added to the class="selectContainer myClass"

**Comment by rob-balfre** [comment]
@sainzg can you make a REPL please. Thanks

**Comment by sainzg** [comment]
https://svelte.dev/repl/d2e2570cddd843d2820e1a36209b2974?version=3.6.8

**Comment by rob-balfre** [comment]
The class is added but your styles are being stripped out by Svelte.  Either use an external stylesheet or `:global(...)`

https://svelte.dev/repl/9ccb772e3ab74b76b936026eb4fe06a4?version=3.6.8
