### ISSUE TITLE
stopPropagation when selecting a value.

### ISSUE THREAD

**Issue by MaddoxDevelopment** [rob-balfre/svelte-select#175]
I am having an issue where I select a value and it ends up clicking on the element under it once I select. I can't find a way to stop the event propagation, i tried to do it on the onSelect callback, but it did not work.

Example: https://streamable.com/8ox3bz

**Comment by rob-balfre** [comment]
@MaddoxDevelopment can you create a REPL please.

**Comment by MaddoxDevelopment** [comment]
Welp I can't seem to replicate it in a REPL and I noticed the onSelect has a e.stopPropagation on it already, I'll keep digging into my own code and close this.
