### ISSUE TITLE
Fixing the style for wrapping of long item names

### ISSUE THREAD

**Issue by jonjes** [rob-balfre/svelte-select#176]
On small screens, the multi select items with long names don't enclose the full name properly.  This makes the library not an optimal choice for projects where many of the customers are using their phones.

![svelte_select_bad_wrap](https://user-images.githubusercontent.com/2365749/92124757-cce22600-edc3-11ea-9adf-ad71c9f4cc01.png)

Could we fix the style to enclose the full name, and not stretch the close X button on the right?

**Comment by rob-balfre** [comment]
Fixed in svelte-select@3.12.0

**Comment by jonjes** [comment]
Thanks!!
