### ISSUE TITLE
filterText variable without loadOptions, is it possible?

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#178]
Is there a way I can get the `filterText` and freely use it wherever I want?

I mean, do I necessarily have to use `loadOptions()`?

Can we just have something like: `bind:filterText={ImTheFilterTextVariable}`?

**Comment by rob-balfre** [comment]
@frederikhors not sure what you mean, can you make a REPL please?

**Comment by frederikhors** [comment]
Of course: https://svelte.dev/repl/a18abb13f8cf4782878f8b16d1ca32fe?version=3.25.0

How can I get text that is typed and change `typedText` variable actually filtering items using that text?

I don't want to use `loadOptions` function, which by the way forces us to use promises.

Can we use Svelte reactivity with `bind:` or something else?

Thanks.

**Comment by rob-balfre** [comment]
By default `filterText` does this but if you don't want to show any items until a match then try this...

https://svelte.dev/repl/e410e66aa80b40098bb633a9f04dc50b?version=3.25.0

**Comment by frederikhors** [comment]
Thanks.

**Comment by mikekok** [comment]
> By default `filterText` does this but if you don't want to show any items until a match then try this...
> 
> https://svelte.dev/repl/e410e66aa80b40098bb633a9f04dc50b?version=3.25.0

I know this is pretty old but is there any way to hide the empty slot when `filterText` is empty (`filterText.length === 0`) and only display it when no options are found?

**Comment by rob-balfre** [comment]
@mikekok https://svelte.dev/repl/2353916ac81d4595a75878d9d7817c94?version=3.55.1

**Comment by mikekok** [comment]
> @mikekok https://svelte.dev/repl/2353916ac81d4595a75878d9d7817c94?version=3.55.1

Thanks for the quick reply but that would work only in case the items array is empty. What if it's not though?
https://svelte.dev/repl/0cf8be9fed924406b3094726cf5dd12a?version=3.55.1

**Comment by rob-balfre** [comment]
Just adjust the hide logic I guess 🙂

Feel free to open a new issue with a REPL example of your exact problem. Thanks
