### ISSUE TITLE
Why option.value cannot be a number?

### ISSUE THREAD

**Issue by Bighamster** [rob-balfre/svelte-select#182]
I just replaced the values with numbers and got undefined.

```	
const items = [
    {value: 1, label: 'Chocolate', group: 'Sweet'},
    {value: 2, label: 'Pizza', group: 'Savory'},
    {value: 3, label: 'Cake', group: 'Sweet'},
    {value: 4, label: 'Cookies', group: 'Savory'},
    {value: 5, label: 'Ice Cream', group: 'Sweet'}
];
	
let favouriteFood =  3;
```

[https://svelte.dev/repl/86571791cd59463d89bc2bd3806578a2?version=3.12.1](https://svelte.dev/repl/86571791cd59463d89bc2bd3806578a2?version=3.12.1)

How could this be fixed?

**Comment by rob-balfre** [comment]
In your example favouriteFood just needs to be an object.

{value: 1, label: 'Chocolate', group: 'Sweet'},

**Comment by Bighamster** [comment]
Wow! Thanks a lot!
