### ISSUE TITLE
<Select> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [rob-balfre/svelte-select#183]
Getting the following error, how i can fix this?

`<Select> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

**Comment by rob-balfre** [comment]
See docs...

Note: Install as a dev dependency (yarn add svelte-select --dev) if using
Sapper <https://sapper.svelte.dev/> to avoid a SSR error.

**Comment by UnnikrishnanBhargavakurup** [comment]
@rob-balfre - Thanks, it's working
