### ISSUE TITLE
How to detect that an item has been created?

### ISSUE THREAD

**Issue by amanharwara** [rob-balfre/svelte-select#186]
I want to detect when an item has been created, so I can add that new item to the actual list, so I can persist it.
I couldn't find a way to do that currently. Is it possible? If not, I think it would be good if it dispatched an `item-created` event.

**Comment by amanharwara** [comment]
Found a way. Feel very dumb because the solution was so simple & obvious.

**Comment by gponty** [comment]
Can you share your solution please ? ty
