### ISSUE TITLE
[Feature] Option to disable async load fallback

### ISSUE THREAD

**Issue by quentincaffeino** [rob-balfre/svelte-select#188]
It is nice that there is a fallback, but in my application it shows items that were already selected until it pulls newer data from backend. That is not very good in my opinion.

Could it be tweaked with and option to disable fallback or some kind of callback to modify fallback state to remove already selected items?

I can try doing a pr.

Thanks.

**Comment by rob-balfre** [comment]
Please create a REPL. Thanks
