### ISSUE TITLE
FEATURE multi word search

### ISSUE THREAD

**Issue by whishkid** [rob-balfre/svelte-select#190]
Hi, 
Please consider to change line 31 of select.svelte 
FROM
    label.toLowerCase().includes(filterText.toLowerCase());

TO
      !filterText.split(" ").some(word=>!label.toLowerCase().includes(word.toLowerCase()));

This will allow the user to search on multiple words (actually parts of words)

typing "he ar" (without quotes) will match hello how are you

For me this would be great default behavior, but if you have a large group of non believers it needs to be configurable and more work to implement :)

Have a nice day

**Comment by rob-balfre** [comment]
See https://github.com/rob-balfre/svelte-select#exposed-methods

You can override the default filter.

**Comment by whishkid** [comment]
Thanks!... Sorry i didn't notice... it was indeed overridable!

have a nice day
[image: photo] Bastiaan Oelrich
Human Content

Phone: +31 20 76 000 20  <+31+20+76+000+20>
Email: bastiaan@humancontent.nl  <bastiaan@humancontent.nl>
Website: http://www.humancontent.nl  <http://www.humancontent.nl/>
Skype: bastiaan@oelrich.nl  <https://mail.google.com/mail/u/0/#>
Address: Lindengracht 9, Amsterdam
