### ISSUE TITLE
Option to place select list into a new parent

### ISSUE THREAD

**Issue by efreibe** [rob-balfre/svelte-select#191]
Hello!

One problem that I have is when I apply any overflow property to the parent div, it doesn't show the floating list because is located under the same parent as the input box.

This can happen often with popup windows or floating items that make the overflow hidden/scrollable. You can't view the list, or in some cases, need to reposition the content inside the scrollable control for the list to appear. It is very anti-intuitive.

Some css frameworks overcome this limitation giving the chance of placing the floating box into any parent container such as the body.

You can see the problem in this example: https://svelte.dev/repl/8f914162341b4621984808f3a6f0dea0

There is any solution or tweak for that?

**Comment by rob-balfre** [comment]
Sorry, I guess don't use overflow hidden for now if you can. 

I've used the solution you've suggested in dropdown elements before just not implemented it in svelte-select yet.  Feel free to create a pull request if you get a chance. 

Thanks for reporting.

**Comment by rob-balfre** [comment]
Fixed in v5

https://svelte.dev/repl/a1993624b8a24b29a778228081c053fe?version=3.47.0
