### ISSUE TITLE
Async - using keyboard arrow ?

### ISSUE THREAD

**Issue by x4080** [rob-balfre/svelte-select#192]
Hi, nice implementation of drop down. In async, the drop down list cannot be selected with keyboard arrow, is this on purpose ?

Thanks

**Comment by rob-balfre** [comment]
Yup - that's a bug! Thanks for reporting.

**Comment by x4080** [comment]
For sure

**Comment by Moonpax** [comment]
Please add it to the next release

**Comment by www-chique** [comment]
The same I found when using the `isVirtualList`. Turning it off allows keyboard navigation.

**Comment by rob-balfre** [comment]
See REPL for working example https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1

Updating the virtual list will be a different task.  Closing this ticket.

**Comment by x4080** [comment]
very nice
