### ISSUE TITLE
Dropdown not always closing automatically

### ISSUE THREAD

**Issue by Tharit** [rob-balfre/svelte-select#195]
First of all, thanks for the great component! Works really well, exactly what I needed.

I just found one minor issue:

When I clear the last selected item from a multi select via the (X) button on the item itself, the dropdown with the options opens immediately, but it does not close when I click outside of the input or list.
To close it once it is in this state, I have to first click into the input, and then click somewhere else.

Clearing the last selected item from the select via the X button at the right of the input element works fine and does NOT open the dropdown.

Also, a small question:
I am using the async loadOptions routine to autocomplete, but I also want to load an initial set of suggestions.

Would it be possible to somehow asynchronously initialize the items? Right now it seem you have to load your items before mounting the component. Would be cool if you could just optionally call loadOptions once initially or something like that.

**Comment by rob-balfre** [comment]
possible to recreate in a REPL please?
