### ISSUE TITLE
complexItems and selectedValue

### ISSUE THREAD

**Issue by mjadobson** [rob-balfre/svelte-select#204]
Thanks for the lib!

I suspect this is working as intended, but here goes:

When using `complexItems` with a `<Select />`, the `selectedValue` isn't the value, but the whole `{ value: '..', label: '..' }` object.

This was a bit surprising, as for a native select:

```
<select>
    <option value="chocolate">CHOCOLATE</option>
    <option value="pizza">PIZZA</option>
</select>
```

The selected value will be just the `<options>`'s value attribute (eg: "pizza"), not the whole option including value and label.

It is a bit awkward to integrate alongside array fields in my model/database, as the label info has to be added and then removed from the model value:

```
<Select
    items={foodOptions}
    isMulti={true}
    selectedValue={foodOptions.filter(option => user.foods.indexOf(option.value) > -1)}
    on:select={options => (user.foods = options.map(option => option.value))} />
```

When ideally, this would just be:

```
<Select items={foodOptions} isMulti={true} bind:selectedValue />
```

Altering this behaviour would be a breaking change, but maybe some additional API might work? At the least I think it's worth documenting.

**Comment by rob-balfre** [comment]
@mjadobson a simple reactive statement will solve your problem.
https://svelte.dev/repl/5990ab35189a4f1fa88d06455bb23912?version=3.20.1

Checkout the svelte docs here... https://svelte.dev/docs#3_$_marks_a_statement_as_reactive

**Comment by mjadobson** [comment]
Thanks for the quick response and REPL example.

My use case is a little more complicated, which makes using reactive statements awkward.

1. I need to load in the current values rather than start with undefined, so there needs to be code to map what is stored in the database to their related options form. Reactive statements are one-way, but this is more of a two-way situation, as I need to transform into the options form for the component, and then back again into values to save to a database.
2. The `<Select />` are in an each loop, and so using reactive statements becomes more cumbersome than the approach above.

REPL example: https://svelte.dev/repl/0bad783a3f7f41a0868368fc3dcd9d2c?version=3.29.7

What I have works fine, but I did find the API a little counterintuitive. I would maybe have expected something more like:

```
selectedValue => 'chocolate'
selectedOption => { value: 'chocolate', label: 'Chocolate' }
selectedLabel => 'Chocolate'
```

**Comment by rob-balfre** [comment]
Glad you found a solution. 👍
