### ISSUE TITLE
on:select callback argument is CustomEvent not selectedVal

### ISSUE THREAD

**Issue by mjadobson** [rob-balfre/svelte-select#205]
Just encountered this when coming across the REPL. Docs say the callback arg for `on:select` is the selected value:

```
<script>
  import Select from 'svelte-select';

  let items = [...];
  function handleSelect(selectedVal) {
    ...
  }
  function onClear() {
    ...
  }
</script>

<Select {items} on:select={handleSelect} on:clear={handleClear}></Select>
```

But it seems like it is actually an event object:

REPL: https://svelte.dev/repl/cb5e503fad164f03bc9e671b3f676faf?version=3.20.1

Using Chrome 86

**Comment by rob-balfre** [comment]
All dispatched events in Svelte are objects, `event.detail` is where you will find the selected value.

See https://svelte.dev/docs#createEventDispatcher
