### ISSUE TITLE
Add multiple new items in select doesn't seem to work

### ISSUE THREAD

**Issue by quasarchimaere** [rob-balfre/svelte-select#207]
could it be possible that adding more than one new element is not supported?
after adding one element that is not yet in the list, the ability to add another element that is not yet present seems to disappear

**Comment by rob-balfre** [comment]
Sorry @quasarchimaere not sure I follow. Can you make a REPL please?

**Comment by quasarchimaere** [comment]
Here is a simple example based on your Demo case:

https://svelte.dev/repl/462923029f814206a2e5ba79163aafa0?version=3

What happens is that I allow multiselect and isCreatable, and as you can see you can add a new Item that is not in the list yet.
However once a new Item is added to the selection, the possibility of adding YET ANOTHER new item is not available anymore.

**Comment by rob-balfre** [comment]
@quasarchimaere works fine for me... https://svelte.dev/repl/3e8775b7ba314e3ebf8c55fc1a8dadec?version=3.30.0

<img width="664" alt="Screen Shot 2020-11-26 at 1 13 20 pm" src="https://user-images.githubusercontent.com/2623102/100299995-29cb3200-2fe9-11eb-8a6b-4cae84cd1950.png">

**Comment by quasarchimaere** [comment]
ok, i see where my issue was, i also had a createItem function as a prop and set the id: to undefined (our optionIdentifier is id) and thats why there was an issue. thx for the repl and the swift answer!
