### ISSUE TITLE
Setting required to true via inputAttributes breaks form validation/submission

### ISSUE THREAD

**Issue by MattPurland** [rob-balfre/svelte-select#214]
Setting required to true via inputAttributes adds the property to the input field correctly, but the value never gets set when a selection is made. So the field is always invalid and any form submissions fail checkValidity

**Comment by MattPurland** [comment]
I've found a solution:

inputAttributes={{ required: !selectedValue }}

**Comment by MattPurland** [comment]
I've found a solution:

inputAttributes={{ required: !selectedValue }}

**Comment by andreasnuesslein** [comment]
Thanks for that solution @MattPurland . I know technically it uses the "wrong" input element, but it totally solves it anyways

**Comment by frederikhors** [comment]
It works and it's brilliant! Thanks!

@rob-balfre I think we should add this on docs, nope?

**Comment by MarkBFamFour** [comment]
Forgive me, I don't quite understand how @MattPurland 's example works? What is `selectedValue` and where does it originate from?

**Comment by andreasnuesslein** [comment]
@MarkBFamFour  it's the `bind:value` basically. E.g.:
```
<script>
  import Select from 'svelte-select';
  let selectedValue = {value: 'cake', label: 'Cake'};

  function handleSelect(event) {
    selectedValue = event.detail;
  }
</script>

<Select {items} value={selectedValue} on:select={handleSelect} inputAttributes={{ required: !selectedValue }}></Select>

```

**Comment by MattPurland** [comment]
> Forgive me, I don't quite understand how @MattPurland 's example works? What is `selectedValue` and where does it originate from?

Following on from @andreasnuesslein reply, bind:selectedValue was from an older version of svelte-select, it's bind:value in the current version

**Comment by MarkBFamFour** [comment]
Thanks the code example was a big help! :)
