### ISSUE TITLE
Can I use bind:value={values} like a normal select? 

### ISSUE THREAD

**Issue by Hoss3770** [rob-balfre/svelte-select#217]
With a normal select we can just bind values easily 
```html
<select bind:value={selected}>
```

How can it be done here? 
Till now I did not find any way except with ```handleSelect```
However if I have three different selects then I have to write three different functions

**Comment by rob-balfre** [comment]
```svelte
<Select bind:selectedValue={selected} />
```

**Comment by orgertot** [comment]
@rob-balfre this is different tho... selectedValue is not the value. Its a object.

**Comment by rob-balfre** [comment]
@orgertot yes but that's easily solved with a reactive statement or using the on:select event.
