### ISSUE TITLE
List did not close when blur

### ISSUE THREAD

**Issue by Ginfone** [rob-balfre/svelte-select#218]
Here is REPL:
https://svelte.dev/repl/92bb657dd7bb4acc9f90f9a10b545bad?version=3.31.0

Expect:

It should close all lists (both loadingOptions and default items) when blur.

Actual:
only loadingOptions closed.

https://user-images.githubusercontent.com/14543212/102970291-37190500-4532-11eb-8a18-54f08abedb92.mov

**Comment by rob-balfre** [comment]
Strange, I can't recreate this locally.  🤔

https://user-images.githubusercontent.com/2623102/103040680-4d71a000-45c8-11eb-933d-1427b27d5a92.mov

**Comment by rob-balfre** [comment]
Fixed in 3.16.1

Thanks for reporting @Ginfone

**Comment by Ginfone** [comment]
Appreciate.
