### ISSUE TITLE
Add '--listBorder' & 'readonly'

### ISSUE THREAD

**Issue by vexkiddy** [rob-balfre/svelte-select#219]
1. Would it be possible to add a CSS variable `var(--listBorder)` so it's possible to add a border colour to the dropdown box?
2. Could you expose 'readonly' as a boolean prop on the input, or a way of disabling the ios / android keyboard input that appears when using the selectbox on mobile ?
3. A way to hide the 'X' after you have selected something in the list

Thanks!

**Comment by rob-balfre** [comment]
v4 will have `var(--listBorder)` and a fix for `isSearchable` not opening keyboards on touch devices. 

Please note we already have this to cover point 3 ... When `isClearable` is `false` the X does not show.
