### ISSUE TITLE
Feature Req - add ability to bold text during type down filtering

### ISSUE THREAD

**Issue by kane81** [rob-balfre/svelte-select#221]
Thank you for the component.

It would be great if there was an option to enable matching text to be bolded when typing for a selected value.

 list = ["James", "Maddison", "John"]
 
 type "a"

will show  ["James", "Maddison"] and "a" is bolded in ["James", "Maddison"] the drop down list

type "am"
will show  ["James"] and "am" in "James" is bolded in the drop down list

Thank you

**Comment by rob-balfre** [comment]
Already possible by overriding the `getOptionLabel` method.

REPL... https://svelte.dev/repl/4a958b5ba27f4200b8234c25f6069d3d?version=3.12.1
