### ISSUE TITLE
How can i get the selected value ?

### ISSUE THREAD

**Issue by abhijitgujar86** [rob-balfre/svelte-select#222]
When using select I need to get the selected value from select 
`
<Select {selectedValue}  {items} bind:filterText {loadOptions}/>
`
after selecting the "selectedValue" should be populated with selected array or value based on if its multi or not, am i  right ?

Note : 

I don't want to use handleselect its not exactly the correct solution though it can be a temporary solution but not suitable for all cases. 

Thanks  for lib its good , I liked it.

**Comment by rob-balfre** [comment]
Usually it's best to use the `on:select` event or if you'd prefer two-way binding use `bind:selectedValue={yourVarName}`
