### ISSUE TITLE
Having trouble with dropdown to display outside the container

### ISSUE THREAD

**Issue by sainzg** [rob-balfre/svelte-select#223]
![image](https://user-images.githubusercontent.com/22079605/103787579-bc5ce900-500b-11eb-9df2-2ec18a32eea1.png)

This happens when the container div is position relative and the bottom div is not part of the parent div, usually modal forms

Any idea how can I resolve this?

**Comment by rob-balfre** [comment]
Duplicate of https://github.com/rob-balfre/svelte-select/issues/191
