### ISSUE TITLE
Not working optionIdentifier

### ISSUE THREAD

**Issue by etozhealkhipce** [rob-balfre/svelte-select#224]
Not working 'optionIdentifier' props (items - Array with Objects).

Example items: 
`items = [{code: 'USD', qt: '15'}, {code: 'EUR', qt: '12'}]
`

In Select component props `optionIdentifier="code"` does not work

**Comment by rob-balfre** [comment]
Make a REPL please.

**Comment by kylehqcom** [comment]
https://svelte.dev/repl/84e80b0b90ca452698bda86d994723f6?version=3.44.1

I seem to be having the same issue. onMount, I load make my request to get my items. I feel like there "could" be a disconnect between the render of the component/Select and data binding?

I tried to reassign values with a manual on click event just in case, but my options are still undefined?

![Screen Shot 2021-11-03 at 6 43 08 PM](https://user-images.githubusercontent.com/424321/140238476-c863852b-97ba-41c4-a228-4fbb9a999851.png)

**Comment by kylehqcom** [comment]
@rob-balfre I appreciate this is an open src labour of love - so if you need anything more from me please let me know. I found this package via Goog's, all looks pretty slick and your demo repl was "muah" - but trying to get this to work with my own project gave undefined's.

I tried to make the "simplest" example without luck. I though that "perhaps" I could only use the 'optionIdentifier" directive when using a "loadOptions" flow. But from looking at the https://github.com/rob-balfre/svelte-select demo, this is not the case. 

Again, I appreciate the efforts in maintaining such a package.
Best K

**Comment by rob-balfre** [comment]
@kylehqcom you're just missing `labelIdentifier`

https://svelte.dev/repl/c4721f2787c947368906e1342bafc1de?version=3.44.1

**Comment by kylehqcom** [comment]
😶‍🌫️  - OMG so sorry, I wasn't aware this was a tuple. Limme sort & again thanks!

**Comment by kylehqcom** [comment]
It's a beautiful thing .
