### ISSUE TITLE
A composite optionIdentifier?

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#227]
Maybe I'm wrong but I can't understand how to use a composite `optionIdentifier`.

**Is it possbile?**

Example:

```js
items: [
  {shelf: 'A', bookName: 'Arts'}
  {shelf: 'B', bookName: 'Arts'}
  {shelf: 'A', bookName: 'Games'}
  {shelf: 'B', bookName: 'Games'}
]

optionIdentifier="shelf-bookName"
```

As you can see I can have books with the same name on different shelves.

How to do?

**Comment by rob-balfre** [comment]
@felipedrumond yep...
https://svelte.dev/repl/359e2de4c5e54215aabdeee8a9a3e05a?version=3.12.1

**Comment by frederikhors** [comment]
@rob-balfre thank you very much for this example.

What I find inconvenient using this is the use of the `selectedValue` like this:

```js
export let selectedValue = null

<Select {items} bind:selectedValue />
```

using it like:

```js
<MySelect bind:selectedValue={item} />
```

`MySelect` is getting directly the `item` (`item: {shelf: 'A', bookName: 'Arts'}`), not the object you are recommending me to use (`{value, label}`).

Is there an elegant way to solve?

Thanks again.

**Comment by rob-balfre** [comment]
@felipedrumond couldn't a simple reactive statement in your MySelect handle this?

**Comment by frederikhors** [comment]
An example?
