### ISSUE TITLE
Make container, list container, and list item classes configurable

### ISSUE THREAD

**Issue by wallw-teal** [rob-balfre/svelte-select#231]
We are able to specify `containerClasses`, which are placed alongside the default `selectContainer` class [here](https://github.com/rob-balfre/svelte-select/blob/master/src/Select.svelte#L812). `listContainer` and `listItem` do not have that ability. However, what I would like to see is the ability to completely replace the default classes. This is useful in projects using Sass or other CSS post processing to bring in complete CSS solutions such as Bootstrap, whose styles fight a bit with the default styles from `svelte-select`.

Simply replacing `class="selectContainer {containerStyles}"` with `class="{containerStyles || 'selectContainer'}"` may not be ideal since that may break current functionality (although that might work nicely for `listContainer` and `listItem` since it would be a non-breaking addition). Instead, it may be better to adopt an optional custom component for each container. Perhaps something like this:

`SelectContainer.svelte`
```svelte
<script>
  export let containerClasses = '';
</script>
<div class="selectContainer {containerClasses}">
  <slot/>
</div>
```
`ListContainer.svelte`
```svelte
<div class="listContainer">
  <slot/>
</div>
```
`ListItemContainer.svelte`
```svelte
<div class="listItem">
  <slot/>
</div>
```
Then make those components optional on the main select component like `Item`, where they would default to the above implementations.

I think it is possible to merge `Item` and `ListItemContainer`, but that probably results in breaking changes.

If this is acceptable, I can submit a PR.

**Comment by rob-balfre** [comment]
Can you try creating a wrapper component and override the styles in there (extending/replacing svelte-select styles with your own etc) or use our [CSS vars](https://github.com/rob-balfre/svelte-select/blob/master/docs/theming_variables.md).  I'm not sure we need to introduce breaking changes like the one you describe above.  Thanks

**Comment by wallw-bits** [comment]
The main suggestion above is not a breaking change, since all of the components still default to their current implementations.

**Comment by rob-balfre** [comment]
You'll have to experiment in a fork and show me. I'm struggling to see how you can just swap a few classes and get it working with bootstrap. Happy to be proved wrong as I'm sure plenty of people would find it useful.

It's not a breaking change I'd be more than happy to accept the PR.

**Comment by wallw-bits** [comment]
I threw it up at https://github.com/wallw-bits/svelte-select/tree/more-custom-components. I can also put that up as a WIP PR if that's easier to view.

For my particular theme, it still ends up being less code to dig out the Bootstrap variables and map them to the CSS vars:
```svelte
<style lang="scss" global>
  @import "../variables.scss";
  @import "bootstrap/scss/bootstrap.scss";

  .selectContainer {
    --background: #{$input-bg};
    --border: 1px solid #{$border-color};
    --clearSelectColor: #{$white};
    --clearSelectFocusColor: #{$white};
    --clearSelectHoverColor: #{$warning};
    --clearSelectTop: 4px;
    --clearSelectWidth: 20px;
    --height: #{$input-height};
    --inputColor: #{$input-color};
    --itemColor: #{$input-color};
    --itemActiveBackground: #{$warning};
    --itemIsActiveBG: #{$gray-600};
    --itemHoverBG: #{$primary};
    --listBackground: #{$input-bg};
    --listEmptyColor: #{$input-color};
    --listEmptyPadding: 1rem;
    --listEmptyTextAlign: left;
    --placeholderColor: #{$input-placeholder-color};
  }
</style>
```
However, there is a lot more potential customization available through that branch if you still want to explore that direction.

My initial thought for a dropdown in my theme was to use Bootstrap's  `.list-group` style, which is [documented here](https://getbootstrap.com/docs/4.6/components/list-group/). I'm able to do that more effectively using my branch. Given that your dropdown list isn't all that different, I opted to go with fewer changes for now.

**Comment by rob-balfre** [comment]
Nice work!  Both approaches look promising. 

Your fork isn't a breaking change, all tests pass and doesn't add too much extra boilerplate. Raise a PR if you'd like.

Also maybe an examples folder in the repo for how to apply Bootstrap like libs and update the README?

**Comment by wallw-bits** [comment]
Cool. I'll work on that. Yes, the tests pass, but the new functionality needs some tests too. I'll add those and the examples.

**Comment by rob-balfre** [comment]
Fixed in v5

https://github.com/rob-balfre/svelte-select/tree/feature/v5#replace-styles-tailwind-bootstrap-bulma-etc
