### ISSUE TITLE
Select in dialog, listContainer displayed "inside" instead of on top

### ISSUE THREAD

**Issue by olivierchatry** [rob-balfre/svelte-select#234]
Hello !

First thanks for this component :). 

We are trying to use svelte-select inside a dialog. The issue being, the list appear "inside" the dialog ( so if dialog is fixed size, we get a scroll bar in the dialog itself ).

I'm not to sure how to fix it ( one solution would be to let the user pick a "sinkhole" where the list could be attached, so that we can display it on top of a dialog ).

Anyone has any idea ?

**Comment by rob-balfre** [comment]
Do you control the CSS of the dialog box? If so just put a overflow:
visible; on it.

**Comment by olivierchatry** [comment]
Duh, that tonight work. I will try tomorrow and update this.
Thanks !

**Comment by olivierchatry** [comment]
And it work beautiful. Thanks a lot !

**Comment by MTyson** [comment]
I'm having this exact issue.  Not sure how overflow: visible on the dialog box would help -- that just adds scrollbars, which is what we don't want -- we want the select list to appear on top of the dialog!

**Comment by olivierchatry** [comment]
Not at all, overflow visible tells the rendering engine to not clip against
the parent ( it's not overflow scroll ). Work great for me.

Le mer. 10 févr. 2021 à 20:33, Matt Tyson <notifications@github.com> a
écrit :
