### ISSUE TITLE
Select inside dialog doesn't appear on top

### ISSUE THREAD

**Issue by MTyson** [rob-balfre/svelte-select#235]
I'm having [this exact issue](https://github.com/rob-balfre/svelte-select/issues/234). Not sure how overflow: visible on the dialog box would help -- that just adds scrollbars, which is what we don't want -- we want the select list to appear on top of the dialog!

**Comment by MTyson** [comment]
Here's a pic
![select-clipping-dialog](https://user-images.githubusercontent.com/54382/107589583-91922180-6bc3-11eb-8342-f3abaf8e0230.png)

**Comment by rob-balfre** [comment]
It's 100% a CSS issue with your modal... https://svelte.dev/repl/3f05d7fa997345b7ba7382f889966de0?version=3.12.1
