### ISSUE TITLE
onCreate doesn't behave as expected

### ISSUE THREAD

**Issue by MTyson** [rob-balfre/svelte-select#237]
In the component:
`createItem={onCreateItem}`

in the code:
```
let onCreateItem = (filterText)=> {
		console.log("filterText: " + filterText);
		return {
			value: filterText,
			label: filterText
		};
	};
```

In the console when typing "test" and clicking "create "test"":

```
filterText: t
Nav.svelte:65 filterText: te
Nav.svelte:65 filterText: tes
Nav.svelte:65 filterText: test
Nav.svelte:65 filterText: test
```

I would expect to just see "filterText: test" one time, and that's it.

**Comment by MTyson** [comment]
This is preventing us from determining when the user actually wants to create an item.

**Comment by rob-balfre** [comment]
@MTyson  I presume you mean the `createItem` method? This is an internal method that takes `filterText` as its argument.  You can listen to the `on:select` event if you need to know which items are selected.  There is no `onCreateItem` event currently.

**Comment by MTyson** [comment]
Yep, I'm overriding the createItem method, in an attempt to capture the user creating a new item (I think that is the purpose of the isCreatable flag?)

So that I can then handle sending an xhr to the server to create the new item.

**Comment by rob-balfre** [comment]
`itemCreated` event added in v3.17.0
