### ISSUE TITLE
Doesn't work when building to a web component

### ISSUE THREAD

**Issue by wojtekgalaj** [rob-balfre/svelte-select#239]
I'm trying to use the component in a web component, so building the application using customElement: true.

In that context the component fails to render with the following error message:

index.mjs:1512 Uncaught TypeError: Illegal constructor
    at new SvelteElement (index.mjs:1512)
    at new Select (Select.svelte:240)
    at create_fragment (Select.svelte:240)
    at init (index.mjs:1489)
    at new App (App.svelte:14)
    at App.svelte:14
    at App.svelte:14

I'll try to set up a code sandbox to demonstrate later.

**Comment by wojtekgalaj** [comment]
This is a "problem" with Svelte. In case anyone stumbles onto this comment, once a customElement: true option is passed to rollup, all components must specify <svelte:options tag="tag-name"/>. In order to use any third party component, rollup config needs to be configured to compile those without the customElement option.

Closing, excuse the noise.

**Comment by msaglietto** [comment]
Hey @wojtekgalaj I have the same issue .. how do you tell rollup to no use customElement with third party ?

**Comment by msaglietto** [comment]
I did this: 
```
  plugins: [
    svelte({
      // enable run-time checks when not in production
      dev: !production,
      // Tell the compiler to output a custom element.
      customElement: true,
      // Exclude third party libraries that dont need to be customElement
      exclude: ['node_modules/svelte-select/**/*.svelte']
    }),
    svelte({
      // enable run-time checks when not in production
      dev: !production,
      // Tell the compiler to output a custom element.
      customElement: false,
      // Include only third party libraries that dont need to be customElement
      include: ['node_modules/svelte-select/**/*.svelte']
    }),
 ```
But now it insert the CSS for svelte-select outside the web component on the header so the styles are not applied

Where you able to use it?

**Comment by wojtekgalaj** [comment]
Hey @msaglietto 

Yeah, I did something similar, just using a suffix for web components and passing custom element to that block. But it's the same idea.

I had the same problem with styles and didn't find an elegant way to solve it. I built the component myself in the end, it's just a simple select component, I spent more time figuring out how to use a third party then writing my own.
