### ISSUE TITLE
Select event does not trigger when values are functions

### ISSUE THREAD

**Issue by k-onrad** [rob-balfre/svelte-select#240]
Hi, thanks for this nice component!

I was trying to use bunch of them with functions as values, so I could later compose them into a single function to filter some data, and ended up catching a bug. Seems like on:select only fires the first time I select an item - from then on it doesn't fire anymore. Reproduced it in the REPL below. Ended up doing this through a workaround, also in the REPL fwiw.

https://svelte.dev/repl/4b93267ae45744c48233e14dff6e4d14?version=3.20.1

Don't know if you plan on actually supporting this or not, but either way it seems like a good idea to say somewhere in the readme what kind of types we can expect to pass as values.

**Comment by rob-balfre** [comment]
We `JSON.stringify` to compare values before dispatching select events - which you can't do with functions.  I'd suggest you use your workaround, it's a better option.  Thanks for reporting though.
