### ISSUE TITLE
Multi Select shouldn't close upon selecting one value.

### ISSUE THREAD

**Issue by abhijit-kar** [rob-balfre/svelte-select#241]
Hey Guys,

Thanks for creating such a wonderful component. I am glad I don't have to rely on datalist component.

There's one hiccup with this library though. The multi select closes upon selecting 1 value, instead of staying open and allowing multiple selection.

Kind of like: [Mouse Friendly Multi Select](https://svelte.dev/repl/c7094fb1004b440482d2a88f4d1d7ef5?version=3.14.0)

P.S. So glad that I'm able to just use the keyboard and select values, thank you for making your component accessible.

**Comment by rob-balfre** [comment]
Kind of possible with a sneaky reactive statement 😊

https://svelte.dev/repl/78878691436040bcb7111176e47456d6?version=3.20.1

**Comment by PlkMarudny** [comment]
That's cool, but it's becoming quite impractical  if I generate tens of selects programatically...

**Comment by rob-balfre** [comment]
@PlkMarudny then just wrap the extra functionality in a component

**Comment by PlkMarudny** [comment]
And that's what I did, thank you.
