### ISSUE TITLE
Values get erased after a few selecting

### ISSUE THREAD

**Issue by moisesGarmendia** [rob-balfre/svelte-select#243]
Hi, I wanna say thank you for making this library, appreciate your effort, hope to make a PR, I'm having some troubles when changing the selected item in simple mode, I use on:select as I returned an object ( for example {id: 1, label: "Employee", value: []}), sure I use event.detail to get the object I want.
This is at the beginning:
![image](https://user-images.githubusercontent.com/78880943/111200608-90b82b00-8587-11eb-8930-1e49ceed68ca.png)
This after few selects changing:
![image](https://user-images.githubusercontent.com/78880943/111200797-b7766180-8587-11eb-8d85-3142984fe8e8.png)
Do not know at this moment if it happens because it's cleared by the library or does not hold the complete object on RAM(which I don't think it is), maybe there are other alternatives by right now I cannot found them,

Regards.

**Comment by moisesGarmendia** [comment]
I thought that `isClearable` were making the issue happens, but it's not. Here is a more clearer view at what it is returning using event.detail
![image](https://user-images.githubusercontent.com/78880943/111209871-2c4e9900-8592-11eb-9541-c58ca252381c.png)
When i do just:
```JS
const handleSelect = (event)=>{
console.log(event.detail)
}
```
Makes no problem, so it is clearly my fault, thank you btw!

**Comment by moisesGarmendia** [comment]
Finally got implementation problems, I was assigning the array to another array, but before that assign, I execute 
```JS
$list.lenght = 0 
$list = event.detail.value
```
now:
```JS
$list = []
$list = event.detail.value
```
Fatal error of newbie to JS, sorry for making the issue haha

**Comment by rob-balfre** [comment]
Glad you sorted it out 👍
