### ISSUE TITLE
isClearable and showIndicator attributes clash with each other

### ISSUE THREAD

**Issue by mi1971** [rob-balfre/svelte-select#244]
<img width="69" alt="Screen Shot 2021-03-17 at 9 50 43 am" src="https://user-images.githubusercontent.com/7830054/111394473-86706b00-8706-11eb-94ce-189eeba632b1.png">
Hi Rob, When both icons are enabled, they sit on top of each other, and cannot clear selection

**Comment by rob-balfre** [comment]
Looks fine to me 😂

Will take a look next week!  Thanks

**Comment by mmcenti** [comment]
Any update on this?

**Comment by rob-balfre** [comment]
fixed in v4.0.0-beta.12
