### ISSUE TITLE
Is there a way to always have at least one selected? (multiselect) 

### ISSUE THREAD

**Issue by mval1002** [rob-balfre/svelte-select#245]
Hi there, I'm struggling a lot to prevent the multiselect from going below 1 selection. I created a [REPL](https://svelte.dev/repl/a1be6788f1764a3a9835a54ee0beb5ab?version=3.35.0) which shows at least some of the things I've tried. There are two different selects because in my actual app, I've somehow managed to have the selection 'stick' but it would only update when another UI item changed (a second Select, in this case) - for some reason this is not the case with the REPL.

I've been searching and experimenting for the better part of two days, and I am truly out of ideas. 

Some things I've noticed:
- `on:select` seems to run before the value is actually changed, at least on REPL, so changing the `selectedValue` there does not really do anything
- `on:clear` runs when any item is removed (not only with `clearAll`, as the docs indicate), but seems to run before `on:select`, so that doesn't seem to be a way around the previous issue
- the `isClearable` property only removes the `clearAll` button, so that can't be set to false when `selectedValue.length == 1`

Hopefully I haven't left the REPL too messy, as I mentioned, I've been trying anything and everything I could find. I also hope I've provided enough information about what has worked and what hasn't.

I appreciate any help you can provide! Thanks for creating a great component!

**Comment by rob-balfre** [comment]
@mval1002 how's this? https://svelte.dev/repl/bfb8a7bd6c2a4e6895901c3b36649799?version=3.35.0

**Comment by mval1002** [comment]
That worked wonderfully! Thank you!!

**Comment by rob-balfre** [comment]
@mval1002 Glad it worked 👍
