### ISSUE TITLE
Feature Request - Show list only after user input

### ISSUE THREAD

**Issue by Doomd** [rob-balfre/svelte-select#248]
I'd like users to be able to filter through a visible list...but only after they enter X number of characters...

This is especially nice when the list is very long...if a user doesn't realize that it's a search field as well, they might try to scroll through super long lists instead.

EDIT:
For now, I have changed the handleClick function to suit my client's request:
```javascript
function handleClick() {
  if (isDisabled) return
  isFocused = true
  // listOpen = !listOpen
  if (listOpen) listOpen = false
  else if (filterText.length > 1 && !listOpen) listOpen = true
}
```

**Comment by rob-balfre** [comment]
use the loadOption function to return a promise (filtered list items) if filterText has X length
