### ISSUE TITLE
Best practices for large datasets and fuzzy search?

### ISSUE THREAD

**Issue by TheCoinPerspective** [rob-balfre/svelte-select#249]
Hi, I'm migrating my site to svelte and have found this library. Thanks for making it! However I'm facing the following challenges:

I have a long list (6000+) of items which if passed along naively make the select unresponsive (both to open and search).

- I'd like to pre-cache the 500-1000 most common values, and lazily search the rest if not found in the cache. 
- It also seems that the `itemFilter` function iterates through each label individually. However I'd like to use FuseJS so as to perform fuzzy search, which takes the whole list as an argument. Is there a method to use or a way to get around this?

Example:

```js

// fuse.js example from https://fusejs.io/examples.html#search-object-array
const options = {
  includeScore: true,
  // Search in `author` and in `tags` array
  keys: ['author', 'tags']
}

const fuse = new Fuse(list, options) // <-- notice the 'list' here

const result = fuse.search('tion')
```

Any help would be greatly appreciated!

**Comment by rob-balfre** [comment]
Use isVirtualList prop

**Comment by TheCoinPerspective** [comment]
I’ll try that, thanks. Any ideas on second part? how to integrate fuse js?

Il giorno mer 31 mar 2021 alle 21:59 Rob B ***@***.***> ha
scritto:

**Comment by rob-balfre** [comment]
yes you can replace the filter function. See https://github.com/rob-balfre/svelte-select#exposed-methods

**Comment by TheCoinPerspective** [comment]
The `isVirtualList` helps a lot! thank you. Regarding the search, I've checked that, but the itemFilter exposed method checks the label 1 by 1, rather than as a list. FuseJS expects the list as an input so it can do its own optimizations. Is there a way around this?

**Comment by rob-balfre** [comment]
You should be able to just use a reactive statement that runs your FuseJS logic when filterText changes and then check against the results in the itemFilter method

**Comment by moisesGarmendia** [comment]
Hi @rob-balfre , wondering if you would make another event, that fires when text in input changes 😅, something like on:textChange or on:inputTextChange.

This will help to implement the custom searching logic using either FuseJS, MiniSearch or whatever search engine devs will use, changing the dataset for the Select component you made when users is writing by a reactive statement, thanks again for such a great library you made, blessings.

**Comment by rob-balfre** [comment]
`svelte-tiny-virtual-list` added for v5.
