### ISSUE TITLE
Select is always focused once initially focused

### ISSUE THREAD

**Issue by jquesada2016** [rob-balfre/svelte-select#250]
I am working on a larger project using Svelte and have noticed when using the component, once the user selects the input to start typing, the focused styles always remain as if the select were still focused even after bluring to another element. This also produces some unwanted side effects, such as the list opening when you press the up or down arrow when navigating a native `<select>` drop-down menu, as well as the list remaining opened until you explicitly click again on the input field of the component.

I'm not sure what code to submit on the issue, because it happens when I just use a plain `<Select />` with no props or styles, as well as anything else I do. In case it is noteworthy, I am using TailwindCSS. Please let me know what else I can provide. I'll try looking through the source code of this component when I get a chance to try and troubleshoot the cause, but I suspect by the way it's behaving, it has to do with some kind of event handler not working properly.

As another note, I am also using Microsoft's Chromium Edge browser, but have also tested on Android's mobile version of Chrome.

**Comment by rob-balfre** [comment]
@jquesada2016  I can't seem to recreate the issue...
https://svelte.dev/repl/ef0d5fd7ce1e415fbc75662976267f01?version=3.12.1
