### ISSUE TITLE
Crash on select when using Svelte DevTools

### ISSUE THREAD

**Issue by bartektelec** [rob-balfre/svelte-select#253]
When running Svelte DevTools for debugging (both Firefox and Chrome), and selecting a new value from the dropdown, the app crashes with this error:

```js
 Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at removeNode (<anonymous>:118:31)
    at Object.block.d (<anonymous>:280:11)
    at destroy_component (index.mjs:1434)
    at List.$destroy (index.mjs:1558)
    at List.$destroy (index.mjs:1671)
    at removeList (Select.svelte:513)
    at Select.svelte:272
    at run (index.mjs:18)
    at Array.forEach (<anonymous>)
    at run_all (index.mjs:24)
```
    
I've tried it on both vite and rollup, using the most simple configuration of the component:
```js
<script>
  import Select from 'svelte-select';
  const items = ['A', 'B', 'C', 'D'];

  let selectedValue = 'A';
</script>

<Select {items} bind:selectedValue />
```

## How to reproduce
- Start the dev server
- Open Browser DevTools and go to the 'Svelte' tab, refresh the page to enable the Svelte DevTools.
- Open the Select and choose a new value

Has anyone experienced the same?

**Comment by rob-balfre** [comment]
@bartektelec thanks for reporting.  I've personally never used the extension until today, but yes it doesn't like svelte-select 

Use the beta for svelte-select v4, it's had some internals reworked.  Tested myself and works. 

Current beta build is:
`npm i svelte-select@4.0.0-beta.7`

**Comment by bartektelec** [comment]
Thanks for the reply, this helped me fix the issue ✌
