### ISSUE TITLE
Use a function to pass the optionIdentifier

### ISSUE THREAD

**Issue by bartektelec** [rob-balfre/svelte-select#254]
We have a project where our grouped data would look like 
```js
[
{group: 'A', value: { id: 1, name: 'One', location: 'New York'}},
{group: 'B', value: { id: 2, name: 'Two', location: 'London'}},
...
]
```
But because we are using the data in a form, we only store the .value part as the selectedValue. The way I ended up hacking it is that for getSelectionLabel and OptionLabel i would do 
`(option) => option.value?.id || option.id;`
I would love to be able to do the same thing with the identifiers, because sometimes the list doesn't highlight the item that is set. Passing a function to optionIdentifier like we do in getSelectionLabel would probably make it more dynamic.

**Comment by rob-balfre** [comment]
Can you create a REPL please?  Sounds like you might need to use a reactive statement to compute the selected value and the `on:select` method to handle selection logic.
