### ISSUE TITLE
Is there offset variable to position the list?

### ISSUE THREAD

**Issue by psyCodelist** [rob-balfre/svelte-select#256]
Hi,

Thank you for the grate component. 
I was wondering if there is a way to remove the few pixel gap between the dropdown and the list? as you can see below, there is a small gap there:

![Screen Shot 2021-05-07 at 3 36 17 PM](https://user-images.githubusercontent.com/3287128/117515034-159d4080-af4a-11eb-8679-befb5a766ce0.png)

Many thanks!

**Comment by JanSmolko** [comment]
> Easy enough to fix with some CSS... https://svelte.dev/repl/34a0e6586a0a4338bc94acee18379c03?version=3.12.1

but behaviour will change. if your svelte-select is at the bottom, list should be at the top. With your solution it will be always at the bottom.

**Comment by rob-balfre** [comment]
@JanSmolko fair point, will add full 'gap' control to v4's next beta :)
