### ISSUE TITLE
Pass and get additional value, example data-id, data-name

### ISSUE THREAD

**Issue by cleitonmedeiros** [rob-balfre/svelte-select#258]
in the on: select event, in addition to the option value, get a select id value or data-id or get value class

in jquery i took the change event of the select and then i managed to get the id of the html element

Ex: $(this).prop('id);

**Comment by cleitonmedeiros** [comment]
<Select items={options.produto} isVirtualList={true} selectedValue={selectedProduto} containerClasses="form-control form-control-sm produto" on:select={changeProduto} id="test" listAutoWidth="{false}"></Select>`

Ex: I`m need get value "test" of id select in function changeProduto, and in event param does not exist

**Comment by rob-balfre** [comment]
Just use the `on:select` method ...

https://svelte.dev/repl/def1298b63a7418ca352a8d3baa91e2f?version=3.12.1
