### ISSUE TITLE
Problem: Ellipsis is not shown on mobile

### ISSUE THREAD

**Issue by raduab** [rob-balfre/svelte-select#260]
When an option's text is larger than the input box, when I select it instead of the input box to show the truncated value and an ellipsis at the end, it expands the input box wrecking the layout

This happens only on mobile. On desktop it shows the ellipsis as expected

![ellipsis](https://user-images.githubusercontent.com/64026120/119601533-08a99980-bdf2-11eb-860b-0b4447948bfe.gif)

**Comment by rob-balfre** [comment]
It will grow to fit the allowed max-width of the parent element. I think this is a CSS issue on your site.

**Comment by raduab** [comment]
This can't be possible. The same code is working on desktop but not on mobile. There's no max width on the parent. Actually the parent is getting wider because of this input that is getting bigger. Here is a comparison from desktop to mobile, with the same code (nothing different from desktop to mobile):

DESKTOP:
![desktop](https://user-images.githubusercontent.com/64026120/119928596-89989a80-bf84-11eb-90d6-540e695683e3.gif)

MOBILE:
![mobile](https://user-images.githubusercontent.com/64026120/119928615-93ba9900-bf84-11eb-8f54-50e5e6a04e5b.gif)

**Comment by rob-balfre** [comment]
Have you been able to replicate the issue on the svelte REPL?

**Comment by raduab** [comment]
You are right. On REPL it works as expected. Maybe I miss something. I'll have another look. Thanks!
