### ISSUE TITLE
Improvement: Instead of the list to show upward or downward depending on the viewport space, the window should scroll to make space

### ISSUE THREAD

**Issue by raduab** [rob-balfre/svelte-select#261]
The list should only appear under the input element. If there's no enough space into the viewport, the whole window should scroll up.

Here's an example of a svelte action which can also be used to scroll the page if the list is outside the viewport:

```
export default function scrollIntoViewport(node) {
  // Determine whether bottom of the element will be below window at current scroll position
  const viewportHeight = window.innerHeight || document.documentElement.clientHeight
  const widgetBottom = node.getBoundingClientRect().bottom
  if (widgetBottom > viewportHeight) {
    window.scrollBy({ top: widgetBottom - viewportHeight + 10, behavior: 'smooth' })
  }
}
```

**Comment by rob-balfre** [comment]
Just set `listPlacement`  to  `bottom` and the page will scroll unless the parent is set to `overflow: hidden;`

```svelte
<Select {items} listPlacement="bottom" on:select={handleSelect}></Select>
```

**Comment by raduab** [comment]
The problem is that the window doesn't scroll up when the space is not sufficient:

![scroll](https://user-images.githubusercontent.com/64026120/119899847-5e925480-bf4c-11eb-9d6d-95ca9306ed27.gif)
