### ISSUE TITLE
The window doesn't scroll up when the space is not sufficient

### ISSUE THREAD

**Issue by raduab** [rob-balfre/svelte-select#262]
The problem is that the window doesn't scroll up when the space is not sufficient and the list is shown at the bottom:

![scroll](https://user-images.githubusercontent.com/64026120/119899847-5e925480-bf4c-11eb-9d6d-95ca9306ed27.gif)

_Originally posted by @raduab in https://github.com/rob-balfre/svelte-select/issues/261#issuecomment-849957642_

**Comment by rob-balfre** [comment]
You'll need to handle that kind of functionality locally @raduab 

Does the keyboard appear below it on a mobile device pushing it upward?

**Comment by raduab** [comment]
I managed to use the MutationObserver along with the Svelte's tick() function in order to wait for the list to get into the DOM and scroll it into the view. Here's for reference:

```
const observer = new MutationObserver(async (mutations, obs) => {
    const list = document.querySelectorAll('.listContainer')[0]
    await tick()
    list.scrollIntoView({
      behavior: 'smooth',
      block: 'end',
    })
    obs.disconnect()
    return
})

observer.observe(document, {
    subtree: true,
    childList: true,
})
```
