### ISSUE TITLE
i18n strings

### ISSUE THREAD

**Issue by juho** [rob-balfre/svelte-select#265]
Hi, thanks for the lib- saved some time here. Wondering if you would be open for a PR for i18nable strings or is that a planned thing for v4? Currently forked it to use it in our project but I was thinking just passing an object with strings to override anything that's used in the component would work as it's only a couple of keys.

**Comment by rob-balfre** [comment]
Can you throw a REPL together with how you see it working please?

**Comment by rob-balfre** [comment]
@juho I looked at the changes you made in your fork. You can just override `getOptionLabel` no need to fork.  For example...

```js
let getOptionLabel = (option, filterText) => {
   if (option) return option.isCreator ? `${TAPi8n.__('requisitions.interview.create')} \"${filterText}\"` : option.label;
};

<Select {getOptionLabel} ... /> 
```

**Comment by juho** [comment]
Thanks for the help!
