### ISSUE TITLE
Display first list item as placeholder

### ISSUE THREAD

**Issue by mrmikardo** [rob-balfre/svelte-select#269]
Hey

As the title suggests, I'd like to drop the placeholder text, and instead display a list item as the "placeholder". As the list items in my particular contain formatted html, it's not possible to simply pass the first of these to the `placeholder` prop, unfortunately.

Is there any way of achieving this? I took a look through the advanced docs, but couldn't find an example of this. Apologies if I missed something here.

Btw, lovely work on this component/library -- generally really great to work with!

**Comment by mrmikardo** [comment]
There's an easy way of doing this, I've realised -- bind the `selectedValue` to the first choices item.

Closing this.

**Comment by bewards** [comment]
Side note: selectedValue is no longer used. Use value instead.
