### ISSUE TITLE
"clear" event is fired when any selection is cleared in multiselect

### ISSUE THREAD

**Issue by oneserv-heuser** [rob-balfre/svelte-select#271]
Hi,

the "clear" event is fired every time a single selected value gets cleared in multiselects.
The README says that the "clear" event is fired when **clear all** is invoked. But clearing one item when others are present is not the same as clearing all items. So I think that the event should not fire if one item gets cleared in multiselects.
It should also not be a problem to not fire the event at this point as if you want to know when any value gets cleared you can just bind the selected values and will know when any change appears.

Example: https://svelte.dev/repl/afccab2d4864485aa0a5346de2c86a31?version=3.38.3

**Comment by rob-balfre** [comment]
See this REPL https://svelte.dev/repl/e7a84fd420f54e509ee72268e2cdfce4?version=3.38.3.
The event detail shows which item was removed.

**Comment by oneserv-heuser** [comment]
Yes, thats true, but doesn't solve the issue. The README says "clear fires when clear all is invoked". So I think that either the README should be updated and say that for multiselects the clear function gets fired every time an item gets cleared or the behaviour should be changed as it's unclear at the moment.
This ambiguity lead to a bug (which was easy to solve, thats not the point here) in my application and I guess that this can be prevented for future users by clarifying it.

**Comment by oneserv-heuser** [comment]
Thanks for clarifying!
