### ISSUE TITLE
Group headers undefined for custom identifiers without `createGroupHeaderItem` updated

### ISSUE THREAD

**Issue by stephenlrandall** [rob-balfre/svelte-select#275]
Not sure if this is intended or not (although it was slightly confusing for me): https://svelte.dev/repl/183b491358ad470e868a8de5c781fa3d?version=3.20.1

Basically the default version of `createGroupHeaderItem` ignores the `optionIdentifier` and `labelIdentifier` props, meaning that you also have to set an updated version of `createGroupHeaderItem`. If this is intentional, I can close this issue.

**Comment by rob-balfre** [comment]
Yeah it's confusing and stupid... will fix

**Comment by rob-balfre** [comment]
Fixed in v4.2.4

https://svelte.dev/repl/5e04afe2ef9a48ae9ae2f4354dabdc22?version=3.20.1
