### ISSUE TITLE
For multi-selects, the `select` event isn't fired when clearing the last entry from the list

### ISSUE THREAD

**Issue by stephenlrandall** [rob-balfre/svelte-select#276]
REPL comparing pre-v4 to current release: https://svelte.dev/repl/f71de83f124d4b82a7df564a8412358b?version=3.38.3.

I think this is a bug in v4; according to the documentation, I would expect the select event to be fired on clearing the last event of a multi-select. You can get around this by binding to `value` directly, but as displayed in the REPL this triggers twice (for defined `value`), which isn't ideal in situations where a new selection triggers an action.

**Comment by rob-balfre** [comment]
fixed in v4.2.5
