### ISSUE TITLE
Upgrade to v4: select styles, ES import

### ISSUE THREAD

**Issue by tvanier** [rob-balfre/svelte-select#280]
I have been using `svelte-select@3` without issue, thanks for the great work!

Now trying to upgrade to v4, I noticed these 2 points and was wondering if they are expected?
- the select styles are not imported automatically anymore
- my app is bundled with [vite](https://vitejs.dev/) and rollup, the [module field](https://github.com/rob-balfre/svelte-select/blob/master/package.json#L7) points to a non-existing `dist/index.mjs`
```
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-fc2895ac.js:38154:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "svelte-select". The package may have incorrect main/module/exports specified in its package.json.
```

My app works with v4 and the following changes
```diff
-  import Select from 'svelte-select';
+  import Select from 'svelte-select/dist/index.js';
+  import 'svelte-select/dist/bundle.css';
```

Since `dist/index.js` is an ES module, should the `module` field be removed from `package.json` to keep `main` only?

**Comment by rob-balfre** [comment]
@tvanier thanks for reporting the bug.  

Just so I fully understand usually the recommended way to build is to point to the .svelte file instead of the dist. I've not had a chance to use vite yet, can you share more info on your vite/rollup config please?

**Comment by tvanier** [comment]
Thanks @rob-balfre , here is my sample app PR with the svelte-select upgrade https://github.com/tvanier/sport-visioner/pull/85
Running `npm install` and `npm run dev` in the `dependabot/npm_and_yarn/svelte-select-4.2.6` branch causes the error above.
Vite is configured in [vite.config.js](https://github.com/tvanier/sport-visioner/blob/main/vite.config.js). This is one of the first projects I build with Vite, something may be missing for Svelte files. Also, this is not high priority, only when you have time ;-)

**Comment by rob-balfre** [comment]
@tvanier can you test svelte-select@4.2.7-beta.0 please.

**Comment by tvanier** [comment]
@rob-balfre `svelte-select@4.2.7-beta.0` works good (https://github.com/tvanier/sport-visioner/pull/87), thanks!

**Comment by rob-balfre** [comment]
v4.2.7 released. Closing this now.  Thanks @tvanier
