### ISSUE TITLE
Is it possible to apply classes or attributes on a per-item basis?

### ISSUE THREAD

**Issue by VaelVictus** [rob-balfre/svelte-select#288]
I have a series of items that I'd like to manually apply a class to; specifically if an item in the list doesn't meet requirements, I'd like to apply a `failed` class to it. `/src/Item.svelte` suggests it may not yet be possible?

Thank you for your work on this lovely component!

**Comment by rob-balfre** [comment]
@VaelVictus not really BUT you can replace the Item. See the Async example @ https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1

**Comment by rob-balfre** [comment]
Named slots should make this possible in latest beta. Thanks
