### ISSUE TITLE
Exposing item index or other data fields in Item.svelte

### ISSUE THREAD

**Issue by costinBol** [rob-balfre/svelte-select#289]
Hello,

Would it be possible to either expose the ID (or value) of an Item or the index in the list as an attribute of the Item.svelte element? Or at least certain properties of the objects in the list?

The scenario I'm after is being able to style categories of items, e.g., red, amber and green. The data would be something like: [{value: 'chocolate', label: 'Chocolate', group: 'Sweet', nutrition: 'red'}, ...] and the result I'd expect is:

`<div class="listItem" tabindex="-1">`
`  <div class="item first svelte-u0t2tk" data-nutrition="red">Chocolate</div> `
 `</div>`

(CSS: .item[data-nutrition='red']{ background-color: red})

or

`<div class="listItem" tabindex="-1">`
`  <div class="item first svelte-u0t2tk" data-index="0">Chocolate</div> `
 `</div>`

or

`<div class="listItem" tabindex="-1">`
`  <div class="item first svelte-u0t2tk list-index-0">Chocolate</div> `
 `</div>`

What do you think, would any one of those options work?

Thanks,
Costin

**Comment by rob-balfre** [comment]
@costinBol not really. Only option is to supply your own `Item` component, that gives you complete control. See... https://svelte.dev/repl/36e15c806e1945c1965fad2ff6bd01bf?version=3.20.1

**Comment by costinBol** [comment]
That could work as well, thanks.
