### ISSUE TITLE
noOptionsMessage is not displayed with isVirtualList when there are no matching search results

### ISSUE THREAD

**Issue by maartenzam** [rob-balfre/svelte-select#290]
To reproduce, add `isVirtualList={true}` to the "Multi" example of the [Advanced demo page](https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1)

Thanks for this great component!

**Comment by rob-balfre** [comment]
Fixed in v5

https://svelte.dev/repl/1f44ff9be0f145469a2283776e766103?version=3.47.0
