### ISSUE TITLE
4.3.0, issue with bind:filterText and bind:value

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#291]
I'm having issues with 4.3.0.

REPL (4.3.0): https://svelte.dev/repl/8cb101d5b5f04b9ea9e85b653cf47345?version=3.42.1

As you can see if I select the first player (e.g.: John) and I try to search another one (e.g.: Bob) it changes `filterText` but immediately restores the previous list.

**The same code works with 3.7.0:**

REPL (3.7.0): https://svelte.dev/repl/4153cf78a21e48669d83138833f438d2?version=3.42.1

**Why?**

**Comment by frederikhors** [comment]
Updated the first post.

**Comment by frederikhors** [comment]
@rob-balfre I just found this issue, it's urgent because it is already in production unfortunately.

Can you please see if I'm the problem?

**Comment by frederikhors** [comment]
@rob-balfre can you help please?

**Comment by subpx** [comment]
@frederikhors you should be using loadOptions by the look of it.
Here is a quick example that fixes your issue
https://svelte.dev/repl/15f41258b62442d39d16095fc43fef02?version=3.42.1

I hope that helps

**Comment by frederikhors** [comment]
Thanks but whay is my code not working?

I think `loadOptions` is an alternative, but why is my code not working?

**Comment by frederikhors** [comment]
@subpx can I ask you why

```ts
leading: true,
trailing: false
```

???

**Comment by frederikhors** [comment]
@rob-balfre I added REPL with 4.3.0 and 3.7.0.

Everything works good with 3.7.0.

**Comment by rob-balfre** [comment]
@frederikhors you can reactively update `items` using `loadOptions`. It uses debounce internally and is designed for this use-case.

**Comment by frederikhors** [comment]
>  you can reactively update items using loadOptions

How?

And why the code works with 3.7.0 and not with 4.3.0?

**Comment by frederikhors** [comment]
I don't know how to do because I'm using svelte-query to reactively update items and it can update items twice using cache-and-network mode.

So first it renders cache list and then (after a while, many seconds) it can update the list with network call results.

**Comment by frederikhors** [comment]
@rob-balfre the code I'm using is similar to this:

```html
<script lang="ts">
  import { useQuery } from "@sveltestack/svelte-query";
  import Select from "svelte-select";

  import { service } from "$lib/players";

  export let value = null;

  let search = "";

  $: items = useQuery(
    ["players", search],
    () => service.playerList({ search }).response,
    { enabled: !!search }
  );

  const getOptionLabel = (option) => option.lastname + " " + option.firstname;

  function loadOptions(query = "") {
    return new Promise((resolve, reject) => {
      search = query;
      // HOW TO resolve here stale players (in cache) and then new players (if any) after the call?

      // I can think something similar to this, but it's very ugly code and it doesn't work!

      // const unsubscribe = items.subscribe((results) => {
      // 	console.log('items.subscribe ~ results', results);
      // 	if (results.data) {
      // 		resolve(results.data?.players);
      // 	}
      // });
      // unsubscribe();
    });
  }
</script>

<select
  optionIdentifier="id"
  {loadOptions}
  {getOptionLabel}
  getSelectionLabel={getOptionLabel}
  bind:selectedValue={value}
/>
```

for this reason I wanna use `items={items}` reactively with `$:`.

**Comment by frederikhors** [comment]
I'm trying to use both `loadOptions` to update `searchText` and `items={$items.data?.patients}`.

**It works with 3.7.0, but doesn't work with 4.3.0.**

```html
<script lang="ts">
  // ...

  let search = "";

  $: items = useQuery(
    ["players", search],
    () => service.playerList({ search }).response,
    { enabled: !!search }
  );

  const getOptionLabel = (option) => option.lastname + " " + option.firstname;

  function loadOptions(query = "") {
    return new Promise((resolve, reject) => {
      search = query;
      resolve([]) // I will update items reactively!
    });
  }
</script>

<select
  items={$items.data?.players || []}
  optionIdentifier="id"
  {loadOptions}
  {getOptionLabel}
  getSelectionLabel={getOptionLabel}
  bind:value
/>
```

Do you think this is still wrong?

**Comment by rob-balfre** [comment]
@felipedrumond something like this might work?
https://svelte.dev/repl/960fd2abbdec436192abdf3d63886d33?version=3.12.1

**Comment by frederikhors** [comment]
I will try in a few hours. But in this way I need to write debounce function by me.

Maybe we can add a `debounce` prop to handle `filterText` change?

**Comment by frederikhors** [comment]
I tried your example, it "almost" reproduces my use case: you are using simple strings there, in my case I'm using objects.

I have slightly modified your example here: https://svelte.dev/repl/4e6af5e63f3f465b93a5ca7b5c45909e?version=3.42.1

As you will notice after selecting the first one when I try to look for another the value changes:

![iss](https://user-images.githubusercontent.com/41120635/128853501-5502ec5d-d88a-4b9b-9b80-58a514ab3cdb.gif)

But in my project one more thing happens, the updated filtered list DISAPPEARS!

I made a video, here it is:

![Animation](https://user-images.githubusercontent.com/41120635/128853172-7cd55b1a-cffb-4775-ae1c-e045180f1e76.gif)

Maybe we should wait for a `tick` before update the lists?

**Comment by rob-balfre** [comment]
Don't bind value use on:select

**Comment by frederikhors** [comment]
> Don't bind value use on:select

It doesn't change: https://svelte.dev/repl/5420d9017e9a4dbabe63010058e20456?version=3.42.1.

**Comment by rob-balfre** [comment]
Why did you remove itemFilter from my repl?

**Comment by frederikhors** [comment]
> Why did you remove itemFilter from my repl?

Because I didn't know what it was for.

Here the REPL updated with itemFilter: https://svelte.dev/repl/6521979ac15e4226a11459bb2c4e14cc?version=3.42.1

Same problem.

**Comment by rob-balfre** [comment]
I removed some filterText logic. Will write some tests in the morning and check I've not broken anything important!

`svelte-select@4.3.1-beta.0`

https://svelte.dev/repl/62656cc463a64e828649b68ee8c1194c?version=3.42.1

**Comment by frederikhors** [comment]
NOW IT WORKS PERFECTLY!

PLEASE DON'T DAMAGE THIS MAGIC AGAIN!

😄😄😄😄😄😄😄😄

**Comment by rob-balfre** [comment]
`svelte-select@4.3.1` released
