### ISSUE TITLE
Avoid importing VirtualList and other in final bundle

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#293]
This is the size in my project final bundle:

![image](https://user-images.githubusercontent.com/41120635/128609833-98acd047-4bd4-46d6-98a6-76ada0a4d46a.png)

How can I avoid importing VirtualList, MultiSelection if I'm using one-select only?

**Comment by rob-balfre** [comment]
@frederikhors I almost made it an optional import for v4 but decided against it, maybe v5 😉.  

If you're worried about 5kb (probably 2kb gzip?) then I would avoid using svelte-select, especially if you don't need a multi select.  I'd recommend the native select element  or https://github.com/pstanoev/simple-svelte-autocomplete

**Comment by frederikhors** [comment]
> I'd recommend the native select element or https://github.com/pstanoev/simple-svelte-autocomplete

There are problems with it too: https://github.com/pstanoev/simple-svelte-autocomplete/issues/90

I will wait for v5. Thanks!
