### ISSUE TITLE
Debounce filterText change, please

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#294]
Because I'm not using `loadOptions` and I'm updating `items` reactively, it would be amazing to use the internal `debounce`/`loadOptionsInterval` logic but when binding with `bind:filterText`.

It's very hard to add this?

I have many `Select` components and I'm repeating the below code again and again only for debounce:

```html
<script lang="ts">
  // ...
	import debounce from 'lodash/debounce.js';

  // ...
	import { DEBOUNCE_TIMEOUT } from '$lib/constants';

  // ...

	let filterText;
	let search = '';

	const updateFilterText = debounce((val) => (search = val), DEBOUNCE_TIMEOUT);

	$: updateFilterText(filterText);

	$: condition = Condition.create({ ...condition, search });

	$: items = useQuery(
		[playerListKey, condition],
		() => service.playerList({ condition }),
	);

  // ...
</script>

<Select
  items={$items.data?.players || []}
  bind:filterText
  ...
/>
```

**Comment by mbornath** [comment]
I'm using the `loadOptionsInterval` option for that. unfortunately it's not in the docs

**Comment by rob-balfre** [comment]
Going to close this as you achieve same result outside of svelte-select.

Simple example of adding your own:
https://svelte.dev/repl/074fb24ac93746578588963d8143a680?version=3.50.0

You could also use derived stores or a shared component if repeating yourself too much

Thanks
