### ISSUE TITLE
Please, can you add the possibility to show a different indicator when the list is open?

### ISSUE THREAD

**Issue by ThornDuke** [rob-balfre/svelte-select#295]
It would be very nice if one could choose an indicator (let's say: `chevronDown`) when the list is close and another indicator (let's say: `chevronUp`) when the list is open.
Alternatively, you could add two custom events: `onOpenList` and `onCloseList`; this way one could programmatically choose the indicator with a code like this:
```html
<script>
  const chevronUp = '<svg> ...';
  const chevronDown = '<svg> ...';
  let chevron = chevronDown;

  const handleOpenList = (event) => {
    chevron = chevronUp;
  }
  const handleCloseList = (event) => {
    chevron = chevronDown;
  }
</script>
<Select
  indicatorSvg={chevron}
  on:openList={handleOpenList}
  on:closeList={handleCloseList}
/>
```

Thank for your very valuable component.

**Comment by rob-balfre** [comment]
Can you bind to `listOpen` and update `indicatorSvg` reactively? Not tried this but might work!

**Comment by ThornDuke** [comment]
Yes, it works. I did the job this way:

```html
<script>
  const chevronUp = '<svg ...';
  const chevronDown = '<svg ...';
  let chevron = chevronDown;
  let isListOpen = false;
  
  $: chevron = isListOpen ? chevronUp : chevronDown;
</script>

<Select
  indicatorSvg={chevron}
  bind:listOpen={isListOpen}
/>
```
Many thanks for the tip.

**Comment by ZerdoX-x** [comment]
This is more proper way: 

```js
$: listActuallyOpen = !!(isCreatable && filterText && listOpen) || (hideEmptyState ? items.length > 0 && listOpen : listOpen);
```

Works with all possible cases (as for me). Because sometimes listOpen may be `true` when you don't even have list or some cases like this...
