### ISSUE TITLE
Make default styles optional and expose class names as props (ie Tailwind etc support)

### ISSUE THREAD

**Issue by rob-balfre** [rob-balfre/svelte-select#299]

**Comment by milesje** [comment]
support for Tailwind would be extremely appreciated.

**Comment by eriknyk** [comment]
not only tailwind classes, I think that clases shouldn't being generated dynamically, the component should load a css file by including it and allow pass custom classes through properties, a kind of.

<Select class="any-class from-any css-framework"/>

iside the component the class properrty can be acccessed from $$props.class
