### ISSUE TITLE
Can't get padding and placeholder to work

### ISSUE THREAD

**Issue by hsb-tonmoy** [rob-balfre/svelte-select#300]
![image](https://user-images.githubusercontent.com/35843150/129571993-34b60597-0f7f-41d6-b24e-c98fdaf60a4b.png)
![image](https://user-images.githubusercontent.com/35843150/129572247-bba8246f-7430-413b-a316-f1d12eacd6a3.png)

The first blank one is a svelte-select component whereas the rest are plain buttons styled with Tailwind. I'm trying to get the Select component to look like the rest. 

```
<span class="themed">
    <Select items={boards} placeholder="Boards" on:select={handleSelect} />
  </span>
<style>
  .themed {
    --background: #f1feff;
    --border: 1px solid #f1feff;
    --borderRadius: o.125rem;
    --inputPadding: 0.5rem 1rem;
    --padding: 0.5rem 1rem;
    --listEmptyPadding: 0.5rem 1rem;
    --selectedItemPadding: 0.5rem 1rem;
  }
</style>
```

I just tried every paddng variable lol

**Comment by rob-balfre** [comment]
Presume the container is a flex box? Just add `min-width: xxx;` to `.themed`.
