### ISSUE TITLE
How to set the style of the placeholder?

### ISSUE THREAD

**Issue by ThornDuke** [rob-balfre/svelte-select#301]
Hallo. I'm not able to set the font-size and font-weight of the placeholder. The items are correctly styled, but the placeholder is always normal (not bold or semi-bold) and with an incorrect font-size.
Are there any variables to set for the placeholder?

**Comment by rob-balfre** [comment]
@ThornDuke all the available ones are listed here... https://github.com/rob-balfre/svelte-select/blob/master/docs/theming_variables.md

font size and weight is not on there I'm afraid. So just use `:global(...)`, example here... 
https://svelte.dev/repl/c399ea60b142432ea1c6c103f1c916e9?version=3.12.1
