### ISSUE TITLE
How to pass events from list items?

### ISSUE THREAD

**Issue by bostondevin** [rob-balfre/svelte-select#304]
I want to add a delete icon in the items, then somehow pass that delete event up - any way to achieve this? I want to get on: events from the Item...

<Select
    {Item}
></Select>>

**Comment by rob-balfre** [comment]
@bostondevin not a feature we have out of the box but you can replace `Item` with your own version and use a global store to power `items`.

Example @ https://svelte.dev/repl/3c257e395ef641d9967c0778129b29a7?version=3.20.1
