### ISSUE TITLE
on:mouseover must be accompanied by on:focus

### ISSUE THREAD

**Issue by mrmikardo** [rob-balfre/svelte-select#307]
I'm using `svelte-select` in one of my projects and recently upgraded from Svelte `3.32.3` to `3.42.4`. The new compiler throws some minor warnings pertaining to the `Select.svelte` and `List.svelte` components;

```
WARNING in ./node_modules/svelte-select/src/List.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
A11y: on:mouseover must be accompanied by on:focus (215:4)
213:   <VirtualList {items} {itemHeight} let:item let:i>
214:
215:     <div on:mouseover="{() => handleHover(i)}" on:click="{event => handleClick({item, i, event})}"
         ^
216:         class="listItem">
217:           <svelte:component
```

I'm not sure what the best way to actually handle these events would be -- do we think it's best if the `focus` event also calls the `handleHover` function (for instance)?

Happy to work on a PR for this.

**Comment by rob-balfre** [comment]
@mrmikardo it's already fixed I think. What version of `svelte-select` are you using?

**Comment by mrmikardo** [comment]
@rob-balfre `3.17.0` - will update and report back!

**Comment by mrmikardo** [comment]
@rob-balfre have confirmed that this works on the latest version (`4.4.0`) - many thanks for your response.
