### ISSUE TITLE
Cannot focus select with tabulation using a modal library

### ISSUE THREAD

**Issue by brian-dechoux** [rob-balfre/svelte-select#308]
Hello, I am trying to use Svelte-Select along with another library, [Svelte Simple Modal](https://github.com/flekschas/svelte-simple-modal). 

When I use a `Select` in the opened modal, I'm not able to get focus on the select. I also cannot continue to tabulate through other inputs afterward.

I created a REPL with my exact versions:  
https://svelte.dev/repl/7423b7a7c40c4e0e90cf40c919739d59?version=3.12.1 

In the modal, click on the first input, and try to access others using only tabulation.

Any thoughts on what could be the cause of this issue ?

**Comment by rob-balfre** [comment]
@brian-dechoux hmmm yeah, thats annoying! Might be an `on:` event conflicting somewhere, not sure.

**Comment by brian-dechoux** [comment]
I found the issue, it's a custom handler for the 'Tab' key in the modal library. Closing here. Thanks for your time @rob-balfre
