### ISSUE TITLE
`value` changes when I search for items, not when I select one of them

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#310]
I'm using `bind:value` and as you can see the `value` is changed every time I search something.

**I expect the value to change when I select an item, not when the `items` change.**

- **REPL**: https://svelte.dev/repl/ecf2a4bcdd324f45bec87df704fb2d86?version=3.42.4

- **video**:

![iss](https://user-images.githubusercontent.com/41120635/132842192-6da91f9b-fda7-4e11-9087-31ec9dff8c23.gif)

**Comment by frederikhors** [comment]
I will post a video now.

**Comment by frederikhors** [comment]
Video posted.

**Comment by FluffyDiscord** [comment]
try `<svelte:options immutable={true}/>` at the `SelectPlayer.svelve` 

https://svelte.dev/repl/1c26456a56674299a59c89243b1004a9?version=3.42.4

**Comment by frederikhors** [comment]
Unfortunately this is not a solution in my case. If I use this things go wrong in my `SelectPlayer` component: if I use simple svelte code in it it doesn't update prop like: `isWaiting`, `hasError`.

**Comment by rob-balfre** [comment]
@felipedrumond try using `on:select` instead of `bind` for `value`...

https://svelte.dev/repl/5a31f21ef2e444e7aaf68f6f40757bc7?version=3.42.4

Essentially `svelte-select` doesn't support streaming, so assigning new items fires a chain of reactive events. No plans to add currently. PRs welcome though.

**Comment by frederikhors** [comment]
With `on:select` it works amazingly. Thanks for your work!
