### ISSUE TITLE
Receive values for selection

### ISSUE THREAD

**Issue by gabrieldejesus** [rob-balfre/svelte-select#311]
## Hello Guys
It would be very useful if this lib could receive values for the select without the user needing to select

### Example:
User has a field on a profile page that selects their tags using **svelte-select** when sending this information to the backend the backend returns the current value of the tags after having a variable with the tags we could just insert this value (by default) when **svelte-select** is displayed so it doesn't need the user to re-enter their tags if they don't want to edit this field in their profile.

If it was not clear, just comment below that I explain more about the use case.

**Comment by FluffyDiscord** [comment]
just bind the value and update it once you receive values from your API

https://svelte.dev/repl/e744b4cc70d6497096d2ba2850ba455f?version=3.12.1
(wait ~3 secs for the timeout)
