### ISSUE TITLE
Once 1 item is selected in MultiSelect, none others show

### ISSUE THREAD

**Issue by Edward-Heales** [rob-balfre/svelte-select#314]
Sandbox: https://codesandbox.io/s/elastic-haze-ob7d6?file=/App.svelte

Once one item has been selected none others show below it.
If it is removed, the others show again.

Is this my fault or a problem with the component?

**Comment by rob-balfre** [comment]
@Edward-Heales you can't use `Object.values` in that way I'm afraid.  I'd suggest you map the items before...

https://svelte.dev/repl/3e1c541179b544fab85d79ddd8e0d338?version=3.12.1

**Comment by Edward-Heales** [comment]
Ah I see, so I wouldn't be able to pass around objects inside the MultiSelect then, it has to be a list of strings, do you know of a possible workaround whereby I could pass the key in somehow but display the value? as I need the key to identify the object.

**Comment by rob-balfre** [comment]
Yes you can but your objects needs to be consistent.

For example...
https://svelte.dev/repl/09df3e44fb7348d7b0ad898e8f906c7a?version=3.20.1

**Comment by rob-balfre** [comment]
@Edward-Heales I'd suggest adding 'add all' button somewhere. Closing this now.
