### ISSUE TITLE
Virtual list is buggy at best

### ISSUE THREAD

**Issue by FluffyDiscord** [rob-balfre/svelte-select#316]
Hi, would you mind migrating virtual list to some other package, which is not dead and has less bugs please? We are facing some issues such as:

- dropdown window is higher than it should be (if I have 1 item, I don't need to have dropdown as high as 4 items are, unnecessary blank space)
- opening the select, scrolling with mouse and then trying to navigate via arrow keys becomes impossible

I think you could easily replace it with this package https://www.npmjs.com/package/svelte-tiny-virtual-list

**Comment by rob-balfre** [comment]
Yeah 100%, v5 (#298) will do just that. No ETA.

On a side note don't post issues with 'buggy at best' in the title - please update.

**Comment by FluffyDiscord** [comment]
Alright, thank you and closing.
