### ISSUE TITLE
Problem setting a selected value

### ISSUE THREAD

**Issue by newlegendmedia** [rob-balfre/svelte-select#319]
In some cases I am attempting to set the current selected item by setting the "value" prop. What I get is select showing the value I set but not the associated label. Meaning the select is displaying the value and not the label. Is there a different way I should be setting a current selection programmatically?

**Comment by rob-balfre** [comment]
@newlegendmedia you can set the value by setting a matching object or label...

https://svelte.dev/repl/faa158ae17634a139a6dea274511897f?version=3.12.1

But it would be cleaner and less confusing to also support accepting the value. I'll keep this open as a reminder to improve the logic. Thanks 👍

**Comment by newlegendmedia** [comment]
Thanks! I can do it the way you showed for now with no problem.

**Comment by rob-balfre** [comment]
Fixed in v5
