### ISSUE TITLE
Different styles between the main box and the indicator.

### ISSUE THREAD

**Issue by ThornDuke** [rob-balfre/svelte-select#325]
Hallo. If I set

```html
<Select
  {items}
  containerStyles="cursor: pointer;"
/>
```

the cursor on the indicator (the "chevron") is styled as "pointer", but the cursor on the main box is styled as "default".

How can I style the full component with `cursor: pointer;`?

**Comment by rob-balfre** [comment]
@ThornDuke just use Svelte's `:global` modifier... docs here https://svelte.dev/docs#style
