### ISSUE TITLE
Allow on:change and on:blur to be set on input

### ISSUE THREAD

**Issue by vince-xopolis** [rob-balfre/svelte-select#326]
Hello, I am trying to use this select with a svelte form package in my project.

However I cannot fire the onchange event properly using the on:select event because that event does not set the event target as the input, the event target is always null.

My preferred solution would be to set on:change and on:blur on the Select and have those be connected to the resulting input.

Is there some way to do this?

**Comment by rob-balfre** [comment]
@vince-xopolis not 100% sure what you mean, can you make a REPL please

**Comment by vince-xopolis** [comment]
I hope this makes sense: https://svelte.dev/repl/5627e1e19fcb4a288fa334b75d350839?version=3.12.1

I didn't include the part with the svelte form package, but essentially it uses events to update the form state and I would like to use the same change handler to keep my state up to date.

**Comment by rob-balfre** [comment]
@vince-xopolis I've not used `svelte-forms` before, can you include that in the REPL please so I can fully understand the problem. Thanks

**Comment by vince-xopolis** [comment]
Ok, I rewrote the REPL but I don't know why the form package gives errors in the REPL: https://svelte.dev/repl/5627e1e19fcb4a288fa334b75d350839?version=3.44.0

In this example `on:change={handleChange}` will never fire.  Using `on:select={handleChange}` will fire, but the error I get is that the event target is null.

**Comment by rob-balfre** [comment]
added in v5
