### ISSUE TITLE
First item not selected when input field is focused w/ group headers

### ISSUE THREAD

**Issue by brollb** [rob-balfre/svelte-select#331]
There appears to be an issue when group headers are set to not be selectable. It seems like the group header still occupies a "slot" when using the arrow keys even though it isn't able to actually be selected (as desired).

This is also noticeable when focusing on the input as shown below. Selecting the input slot when there aren't group headers highlights the first item in the list; when there is a group header this isn't the case.

![DeepinScreenshot_select-area_20211020162151](https://user-images.githubusercontent.com/4982789/138173981-5a035bbb-57d6-4cb4-9203-addc41577887.png)
![DeepinScreenshot_select-area_20211020162138](https://user-images.githubusercontent.com/4982789/138173982-bb6fc738-eed7-49b0-bb55-14d3925b3f7e.png)

Upon closer inspection, it appears this might be an issue with the `isItemSelectable` function in `List.svelte`. The group header is:
```
{value: 'Ports', label: 'Ports', id: 'Ports', isGroupHeader: true, isSelectable: false}
```
However, this is considered to be selectable since there isn't a `selectable` key (https://github.com/rob-balfre/svelte-select/blob/master/src/List.svelte#L210-L212).

**Comment by rob-balfre** [comment]
Fixed in v5
