### ISSUE TITLE
on:blur event

### ISSUE THREAD

**Issue by rob-balfre** [rob-balfre/svelte-select#333]
@rob-balfre I have quite similar issue. In your codesandbox sample when I type "abc" and move on (blur), the value "abc" stays and it seems that something is selected - but it is not, "abc" is not an option. This is misleading from UI perspective so I thought that `on:blur` method could help here.

_Originally posted by @tomekrozalski in https://github.com/rob-balfre/svelte-select/issues/326#issuecomment-948674245_

**Comment by akiarostami** [comment]
+1

**Comment by Iuriy-Budnikov** [comment]
+1

**Comment by zwergius** [comment]
I'd like the following input events added in addition to on:blur => 

on:invalid & on:input I use the native HTML5 validation api and these events are required in order to accomplish this.

**Comment by rob-balfre** [comment]
Added in v5
