### ISSUE TITLE
itemCreated dispatcher

### ISSUE THREAD

**Issue by Inqnuam** [rob-balfre/svelte-select#336]
Hello,
as I can see in source code there's a dispatcher for "itemCreated" and we can use it with "on:itemCreated".
Could you expose that "API" in documentation and into interface so we can do things like POST to db or open a modal to enter more info once an item is created
Thanks for this component it is very useful!

Also I've customised your module to add tooltips on labels in Items List when labels string length is > 60 
<img width="489" alt="Screenshot 2021-10-25 at 11 50 45" src="https://user-images.githubusercontent.com/69360379/138674295-f81b5835-44cd-48fc-8283-bbc5ba43ab48.png">
and tooltip boolean parameter
<img width="343" alt="Screenshot 2021-10-25 at 11 52 11" src="https://user-images.githubusercontent.com/69360379/138674502-7aa57544-6fb7-4b4c-8d63-7a47d0ca9a9a.png">
Could you please add this functionality but with a better implementation ?

**Comment by rob-balfre** [comment]
Not to self to add `itemCreated` to docs

```svelte
<Select on:itemCreated={doSomething} />

**Comment by rob-balfre** [comment]
@Inqnuam no plans to add `tooltip` to svelte-select. Nice solution though. Can you share the code on a fork so I can add to examples?

**Comment by rob-balfre** [comment]
Documented `itemCreated` in v5 docs
