### ISSUE TITLE
add additional vars and props

### ISSUE THREAD

**Issue by basaran** [rob-balfre/svelte-select#337]
Hello,

In an effort to conform to existing styles, do you think it would be good to include a box-shadow var for the `select-container`?

A transition variable could also be helpful.

I can send a PR if you like.

**Comment by rob-balfre** [comment]
@basaran someone else asked about keeping the list open...
https://svelte.dev/repl/e1ca7867e3b543539b25ccba1ef4de0a?version=3.44.0

**Comment by basaran** [comment]
This is a nice way to make a function reactive, by passing a dummy argument. The modified package I published has id independent prop to keep the list open but either will work just fine. I also changed the logic of `name` prop, as it was causing issues with third party validation library I was using. Well, I will update you if I make any dramatic changes. Thank you again.
