### ISSUE TITLE
bind:value to underlying 'value' instead of the entire object

### ISSUE THREAD

**Issue by MattPurland** [rob-balfre/svelte-select#338]
I may be completely missing something here, so I'll apologise in advance.

Assuming a collection is used for the underlying data.

From a backend point of view, having to access option['value'] (or whatever language equivalent) doesn't really feel right. Ideally the value bound to the select is **only** the underlying value of the selected object, that way when sent to a server I only need to access the request's parameter, not the parameter with the 'value' key. This is how a 'normal' select works.

Hopefully that makes sense. And my question is: is it possible to bind the value of the select to just the underlying value of the selection object?

Note: I understand I could use on:select and manually update a variable, but binding is much simpler.

**Comment by rob-balfre** [comment]
@MattPurland no it makes sense. Just can't think of a nice prop name for it. Any ideas?

**Comment by MattPurland** [comment]
Personally I'd use 'option' for the object and 'value' for the value. But I
understand you'd be changing the default behaviour again

**Comment by josdejong** [comment]
This would be great indeed, currently I have to do extra plumbing to turn a value into an option and the other way around to be able to work with it.

Maybe all we need is `value` to "just" be selected value instead of an option object and that's it 😁. It would be a breaking change indeed, but I think it would be the right choice for the long run.

**Comment by josdejong** [comment]
The library is working like a charm btw, thanks a lot Rob 👍

**Comment by MattPurland** [comment]
> This would be great indeed, currently I have to do extra plumbing to turn a value into an option and the other way around to be able to work with it.
> 
> Maybe all we need is `value` to "just" be selected value instead of an option object and that's it 😁. It would be a breaking change indeed, but I think it would be the right choice for the long run.

I agree, I don't see the need to store the entire object as the value. The object could always be added to the event detail should the user need to access it on change

**Comment by rob-balfre** [comment]
Fixed in v5

`justValue` prop added

**Comment by josdejong** [comment]
That sounds good, thanks! Looking forward to `v5` 😄
