### ISSUE TITLE
svelte:window usage

### ISSUE THREAD

**Issue by basaran** [rob-balfre/svelte-select#341]
Hello, at the moment each `Select` component is assigning a svelte:window to the window with keyboard events. It probably doesn't matter that much, but do you think it would make more sense to move the keyboard and click outside handlers out of the component, and export them through JS to be attached in the parent component.

something like:

```
import { Select, Selection, Item, handlerStuff } from "$components/Select";
```

and then attach the handlerStuff to the form may be with a `use` directive?

**Comment by rob-balfre** [comment]
Not sure what the benefit of this would be.

**Comment by basaran** [comment]
What if there is like 10 select inputs for an unknown reason? That would 10x the listeners for each keypress and such, no?

**Comment by rob-balfre** [comment]
Interesting... I can't see how something like `use: handlerStuff` is better though. The browser would need to locate the Select that was focused and then fire the internals to achieve what the event listeners currently do. Happy to be proved wrong though if you want to demo a change?

Maybe we could internalise the logic so events listeners only register when the component is focused.

**Comment by basaran** [comment]
I could be wrong but if we do use:handler on each node, that should take care of the clicks, and keydowns isolated to each svelte-select on the page. So, the events will stop firing all over the place even when the user is typing inside an unrelated text input.

Then there is the matter of click outside handler to close the dropdown, for that I guess we can avoid using svelte:window and attach the handler directly to window while checking if nothing was attached before, like using a state variable inside the component to track if the window handler is added or not. We can use a browser check to make it SSR friendly.

If you want to use svelte:window, I suppose the handler function can be exported from the svelte-select so that the user may attach it at the parent. Like I said, I could be completely wrong.

**Comment by basaran** [comment]
I will put together something as soon as I have an opening, probably next week or so.

**Comment by rob-balfre** [comment]
Yeah I've been experimenting with how it works. It's an interesting problem.

**Comment by rob-balfre** [comment]
@basaran v5 (not ready for release just yet) will no longer use window events on the parent component.

Thanks for reporting this 👍

**Comment by basaran** [comment]
very good kind sir)
