### ISSUE TITLE
groupBy doesn't work when using loadOptions

### ISSUE THREAD

**Issue by iluuu1994** [rob-balfre/svelte-select#342]
Thanks for this library! `groupBy` seems to lose it's effect when using `loadOptions` instead of `items` directly.

https://svelte.dev/repl/332b98d719754c25a693e5443a65479d?version=3.12.1

```svelte
<Select {items} {groupBy}></Select>
```

<img width="242" alt="image" src="https://user-images.githubusercontent.com/1752683/139430725-a77cabaa-7817-437c-befd-656188890156.png">

```svelte
<Select {loadOptions} {groupBy}></Select>
```

<img width="220" alt="image" src="https://user-images.githubusercontent.com/1752683/139430827-c78cb5c1-e926-4c16-8ea2-3242faea79cf.png">

**Comment by rob-balfre** [comment]
@iluuu1994 what does your loadOptions promise return? Can you make a REPL please

**Comment by iluuu1994** [comment]
@rob-balfre The repl is linked above :slightly_smiling_face:

**Comment by rob-balfre** [comment]
yeah thats a juicy bug, thanks for reporting

**Comment by rob-balfre** [comment]
Fixed in v5

https://svelte.dev/repl/b0196eb07442413da1d4f097685f405c?version=3.47.0

**Comment by iluuu1994** [comment]
Thank you!
