### ISSUE TITLE
Ability to disable the deletion of the default value in mutliple-select.

### ISSUE THREAD

**Issue by TomS-** [rob-balfre/svelte-select#344]
I'm using this to be able to assign users to a project, but I don't want to give the use the ability to remove themselves from the assignment. What would be nice is an option in the item to assign whether it's removable or not.

Is there a work around for this currently?

**Comment by rob-balfre** [comment]
@TomS- set `isClearable` to `false`

```svelte
<Select isClearable={false} />
```
