### ISSUE TITLE
Hidden input value uses labelIdentifier instead of optionIdentifier

### ISSUE THREAD

**Issue by itay-grudev** [rob-balfre/svelte-select#345]
Currently there are two identifiers: `labelIdentifier` and `optionIdentifier`. One is supposed to be for labels while the other for values. Furthermore the library has a hidden input element where it populates the value of the currently selected item, but it has a bug - it populates the label instead of the value.

https://github.com/clustermarket/svelte-select/blob/1fe714b898e9b6faca8a89da087908f71ebdcabc/src/Select.svelte#L1025
https://github.com/clustermarket/svelte-select/blob/1fe714b898e9b6faca8a89da087908f71ebdcabc/src/Select.svelte#L1033

I believe this is a bug and these need to be changed.

**Comment by rob-balfre** [comment]
@itay-grudev It's not a bug it's for a11y support, screen readers etc
