### ISSUE TITLE
listContainer to show above input

### ISSUE THREAD

**Issue by milesje** [rob-balfre/svelte-select#346]
I've been trying to get the listContainer to show above the input, but I have not been able to do so. I have a case where my select is in the bottom right corner of a dialog which covers 95% of the screen and need to be able to show the listContain above the input as it currently flows off the screen when displaying below the input.

![image](https://user-images.githubusercontent.com/537359/140362716-4c842dcb-e22b-4db8-a24a-0b7844613be8.png)

**Comment by milesje** [comment]
I don't think I was too clear on this... I know that I can statically set the listPlacement to "top", but would really like for the select to be able to show below if there is room to do so... and then switch to above if there isn't room...

**Comment by rob-balfre** [comment]
`listPlacement`'s default is `auto` which is meant to do just that.  I'll need to investigate the `isOutOfViewport` internal method, might need some improvements.

Thanks for the bug report @milesje
