### ISSUE TITLE
Prioritize filtered results starting with the filter text

### ISSUE THREAD

**Issue by brollb** [rob-balfre/svelte-select#347]
When I start typing something to filter the list by, it would make sense for "pi" to select "Pizza" rather than "APizza" (shown below). It appears the original ordering is currently preserved when entering text:
![DeepinScreenshot_select-area_20211108104303](https://user-images.githubusercontent.com/4982789/140783207-9edeacb4-91ae-4c34-adee-ff8588d79fe7.png)

**Comment by rob-balfre** [comment]
It's configurable already but being improved in v5. So I wouldn't suggest
raising a PR currently.

**Comment by brollb** [comment]
Sounds good. Thanks for the heads up!
