### ISSUE TITLE
listContainer is being cropped

### ISSUE THREAD

**Issue by milesje** [rob-balfre/svelte-select#352]
When the Select is in a scrollable area (div) it is now correctly opening in the right direction, but is being cropped/clipped/cut off... whatever term you want to use for it (see image below). This might be solvable using CSS and if it is I'm willing to do that but I have not been able to figure out how to do so...

![image](https://user-images.githubusercontent.com/537359/142271934-57ffcfa8-7a98-43e0-a8bd-401ba634e141.png)

**Comment by rob-balfre** [comment]
Already solved in v5 (not released yet) otherwise use CSS fix for now.

Thanks

**Comment by milesje** [comment]
@rob-balfre is there an expected release date for v5? Can you provide a CSS fix for it?

**Comment by rob-balfre** [comment]
No ETA on v5, it's still in alpha.

The cropping is happening in your code. A simple overflow: visible on the
container usually fixes the problem. All depends on how you've setup the
form CSS.

**Comment by milesje** [comment]
so the containing <div> has overflow: auto set as the elements inside it can be repeated (variable # of rows) where each row will contain a Select element.

**Comment by rob-balfre** [comment]
@milesje does this help?
https://svelte.dev/repl/9ca7b2e76df5429d81ec05d6bf0bdb9f?version=3.12.1

**Comment by milesje** [comment]
@rob-balfre not really... or maybe I'm not fully grasping something here. I took your REPL and modified it to be closer to what my issue is....
The `<div>` in site must have `overflow: auto` as it will contain more rows of select than can fit on the screen at one time.... What I'm looking for is a way for the listContainer to escape the bounding of the scrollable area...

https://svelte.dev/repl/fb1e721d33b24487b92b0a284e6cdba9?version=3.12.1

**Comment by QuickMick** [comment]
> The `<div>` in site must have `overflow: auto` as it will contain more rows of select than can fit on the screen at one time.... What I'm looking for is a way for the listContainer to escape the bounding of the scrollable area...

i have the same problem, is there a quick fix for that? i think you could set listContainer as position fixed, but then you need to implement the positioning code again. is there an other solution? or any progress on the issue/v5? if it is already fixed there, could you maybe release a bugfix version?

**Comment by frederikhors** [comment]
Same here. This is huge.

**Comment by rob-balfre** [comment]
Fixed in v5
