### ISSUE TITLE
Is there a way to keep the list open at all times?

### ISSUE THREAD

**Issue by bewards** [rob-balfre/svelte-select#355]
I see that there is a `listOpen={true}` prop and that it controls when the list is rendered to the DOM, but this value gets updated to false immediately in my case when I have the select inside of a bootstrap dropdown. I was wondering if there was a way to keep the list active at all times?

My design encourages that the user can see the list of items that are loaded on page load (no further async calls):
![image](https://user-images.githubusercontent.com/3927169/143052430-611cb99e-42a6-4bf1-aa2b-1844c26dfa8f.png)

Since my select is within a bootstrap dropdown, I've tried using the "shown.bs.dropdown" event to trigger a click and/or focus on the input element, but that doesn't seem to open the list.

**Comment by rob-balfre** [comment]
@bewards I made this REPL for someone that wanted the list to stay open on selection, might be enough in there for you to refactor?
https://svelte.dev/repl/e1ca7867e3b543539b25ccba1ef4de0a?version=3.44.0

**Comment by bewards** [comment]
Thanks a lot @rob-balfre - being relatively new to Svelte I forgot that I could bind a property and react to it in my outer component:

``` svelte
  $: {
      if (!listOpen) listOpen = true;
  }
```

**Comment by rob-balfre** [comment]
@bewards haha yeah.  

Also on a side note if you are using bootstrap's dropdown are you sure you need svelte-select?  Might be able to just use some simple svelte logic instead.  Either way, happy coding :)

**Comment by bewards** [comment]
Well.. it was either use svelte-select or another vanilla JS select plugin. Since I'm already using svelte components for areas of the site that require data/functional complexities, it seems very fitting with all it's options.
