### ISSUE TITLE
Toggle selection

### ISSUE THREAD

**Issue by ashtyn3** [rob-balfre/svelte-select#359]
`on:select` binding only works if item hasn't been select yet. Is there a way to allow the event to fire even if it has been selected. Like a toggle?

**Comment by rob-balfre** [comment]
@ashtyn3 not baked in no, you'd need to create reactive statements that listened to value and listOpen.  Or you can replace the Item component and handle the events yourself.

**Comment by ashtyn3** [comment]
@rob-balfre Could I get an example? I am new to svelte...

**Comment by rob-balfre** [comment]
@ashtyn3 here ya go https://svelte.dev/repl/f2db1a265bae4f64976f9d24d7b7f996?version=3.12.1

Replaced Item.svelte and added a store to communicate changes.

**Comment by ashtyn3** [comment]
@rob-balfre Thank you so much!
