### ISSUE TITLE
Clear other select components when one is selected

### ISSUE THREAD

**Issue by bewards** [rob-balfre/svelte-select#360]
I am rendering 1-N svelte-select components in a loop for each. When the user selects an option a second time, I am trying to clear the other components. I am unsure of how to gain access to the other select components in order to clear them.

**REPL**
https://svelte.dev/repl/b72f07f11d1e459599ac64d1778e884e?version=3.12.1

**Update 1**
I tried using `bind:value={selectedOption}`, but that changed every select to be the currently selected option even when the option wasn't available in the other lists.

**Comment by rob-balfre** [comment]
@bewards not sure this is what you wanted but hopefully it's close enough...

https://svelte.dev/repl/9432dfa100044cf9bc141143f3f88c7c?version=3.12.1

**Comment by bewards** [comment]
@rob-balfre this is exactly what I was looking for! For my understanding, how does setting the **selectedValues** object-literal **key** property to the selected object get matched with `bind:value={selectedValues[product.Title]}`? This is magic to me.

![image](https://user-images.githubusercontent.com/3927169/145118843-95f40aef-8351-447a-828f-cf1a4675b79a.png)

**Comment by bewards** [comment]
To get this working outside of the REPL, I had to use the ES6 feature `ComputedPropertyName` when setting the object literal property name from a variable:

``` js
function handleProductSelection(e, productTitle) {
  const selected = e.detail as CalcProductSize;

  productSizeSelectedValues = { [productTitle]: selected };
  productSizeSelected = selected;
}
```

**Comment by rob-balfre** [comment]
coolio, glad you got it working
