### ISSUE TITLE
Virtual List Scroll into view

### ISSUE THREAD

**Issue by simeydotme** [rob-balfre/svelte-select#365]
## Bug;
- ❔ when using the `isVirtuallist` option
- ❔ upon opening the list with an item already selected
- ⚠ the virtual list is not scrolling the selected item in to view.

demo here;
https://svelte.dev/repl/34261c821d614fa49ac22d16f0910192?version=3.12.1

## Expected behaviour;
I expect that when the list opens that the virtual list would scroll the selected item into view, just as the non-virtual one does.

**Comment by rob-balfre** [comment]
@simeydotme virtual list has been reworked for v5.  Try out `5.0.0-alpha.10`... https://github.com/rob-balfre/svelte-select/tree/feature/v5

**Comment by simeydotme** [comment]
oh thanks, @rob-balfre ... I'll see about updating the REPL with v5-alpha tonight .. 

.. but I see the milestone for v5 has a lot of tickets and no expected date 😅  

_(p.s; great component!; I found v3 a while ago and it was better than anything else I could find without having to re-implement a lot of boilerplate around a pure JS implementation! 👍 )_

**Comment by rob-balfre** [comment]
@simeydotme cool thanks.

Also I've not tried it but there is also https://github.com/mskocik/svelecte now. Looks pretty nice

**Comment by rob-balfre** [comment]
Fixed in v5

https://svelte.dev/repl/67fdbe6c03c34a54bb4cb13b223e96de?version=3.47.0
