### ISSUE TITLE
returning single value instead of object

### ISSUE THREAD

**Issue by osmancoskun** [rob-balfre/svelte-select#375]
Is there anyway to return just a value insted of a object from given options?
`value = "a"`
instead of 
`value = { value:"a", label:"a" }`
i was looking at documentation but couldnt find anything

**Comment by quasarchimaere** [comment]
just use this snippet:

`$: onlyVal = value && value.value;`

**Comment by rob-balfre** [comment]
Added in v5

`justValue` prop

**Comment by CanRau** [comment]
Personally I would also really appreciate this feature, I don't want to have to rely on JS for this as I like to build my forms progressively enhanced with SvelteKit 😇
