### ISSUE TITLE
Adjust space between icon and text in item list

### ISSUE THREAD

**Issue by 99bits** [rob-balfre/svelte-select#376]
Hi, thank you for your amazing work with Svelte-Select.
I'm learning how to use it in my project.

I'm trying to adjust the white space between the icon and the label using CSS but cannot find the correct property.

**Comment by ZerdoX-x** [comment]
Just use [:global()](https://svelte.dev/docs#component-format-style). Svelte-select has classes on elements, you can use them to add your own custom global styles.
