### ISSUE TITLE
Dont reset search on click in multiselect

### ISSUE THREAD

**Issue by ZelvaMan** [rob-balfre/svelte-select#377]
Hello, 
Is it possible to not reset search after i click on Item in multiselect mode? I would like to search and then select multiple Items without it reseting search query. I was already able to keep options open after i select something.
Thanks for help.

**Comment by rob-balfre** [comment]
Sure, https://svelte.dev/repl/e1ca7867e3b543539b25ccba1ef4de0a?version=3.44.0

See:
https://github.com/rob-balfre/svelte-select/issues/355#issuecomment-977124481

**Comment by ZelvaMan** [comment]
Thanks for your responce,
I was able to keep it open, but unable to make search text not reset after selecting. I looked into the source code, but its hardcoded there. I ended up creating my own [fork ](https://github.com/KeenMate/svelte-select)to add this feature.

**Comment by greendesertsnow** [comment]
Can you please pull it to the main branch. This is the most popular svelte select library right now and it lacks this very basic functionality. keepOpen
