### ISSUE TITLE
Click on active item doesn't hide items list.

### ISSUE THREAD

**Issue by ZerdoX-x** [rob-balfre/svelte-select#379]
If you click on item that has current select's value (active item) dropdown won't close.
Demo of native select:

https://user-images.githubusercontent.com/49815452/157864648-19e9551a-ff86-41e4-9e48-41014f9c8099.mov

**Comment by rob-balfre** [comment]
Does for me in both v4 and v5 beta.

**Comment by ZerdoX-x** [comment]
Reopen issue and please do not close them if it's working for you only.

So this issue can be reproducable if you wrap select component with label.
I think it's worth to be mentioned in docs or fixed.

https://svelte.dev/repl/5a4fc690d7824f7eaa93601a6e3bbe59?version=3.46.4
