### ISSUE TITLE
List item customization. 

### ISSUE THREAD

**Issue by nezlicodes** [rob-balfre/svelte-select#384]
Is there a way to customize list items? 

**Context**
I have an Avatar.svelte component that I would like to display next to each client item in the list. Is it possible to display that component next to each list item given that each client has its own avatar?

**Comment by rob-balfre** [comment]
@nezlicodes yeah replace Item.svelte with your own version (https://github.com/rob-balfre/svelte-select#api)

**Comment by rob-balfre** [comment]
REPL: https://svelte.dev/repl/b8c20aecffba4cd99a81af37081bd709?version=3.12.1

@nezlicodes

**Comment by nezlicodes** [comment]
Thank you so much for the fast and neat reply !
