### ISSUE TITLE
Override Exposed methods

### ISSUE THREAD

**Issue by gponty** [rob-balfre/svelte-select#390]
Hi,

How to override Exposed methods ?
Like ;
```
export let getOptionLabel = (option, filterText) => {
        return option.isCreator ? `Creer le fournisseur \"${filterText}\"` : option.label;
    };
```

Thank you

**Comment by Edward-Heales** [comment]
Working example with object list
https://svelte.dev/repl/3b05d28025aa4c099ac4d35f419f4c11?version=3.20.1

**Comment by gponty** [comment]
Wow interesting ! Thank you very much
