### ISSUE TITLE
overflow issue

### ISSUE THREAD

**Issue by doki97** [rob-balfre/svelte-select#391]
When using `overflow:hidden`  on the container like:
`<Select containerStyles="overflow:hidden"/>`
to cut off exceeding text from the input, the list dropdown with the options will also be hidden.
Is there any other way to cut out exceeding text from the Input ?
I tried `listAutoWidth={false}` as well as putting` inputStyles="text-overflow: ellipsis; white-space: nowrap; overflow: hidden;"`

Thanks in advance

**Comment by jdromero88** [comment]
if i understand correctly you want to achieve this?
<img width="216" alt="image" src="https://user-images.githubusercontent.com/51330062/162499982-c4bd8c4f-1749-4f6c-8907-15106c7bd0ab.png">
if this is the case you can do it by adding a class to the select container then styling it using `:global`
```javascript
<Select
  containerClasses="myclass"
  placeholder="Select an Authority"
  {items}
></Select>
<style lang="scss">
  :global(.myclass) {
    width: 200px;
  }
</style>
```

**Comment by rob-balfre** [comment]
Fixed in v5

https://svelte.dev/repl/a1993624b8a24b29a778228081c053fe?version=3.47.0
