### ISSUE TITLE
Suggestions don't work correctly in v5

### ISSUE THREAD

**Issue by hmnd** [rob-balfre/svelte-select#392]
In v5, it appears that when `suggestions` is set to true, the `items` param passed to the `filter` function is overridden with the value of `suggestions` (ie. `true`), breaking the filter function.

When suggestions is set to true, I would instead expect either all of `items` to be displayed, or for `loadOptions` to be called without `filterText`, and for that result to be shown.

Not sure whether this is a bug with the docs in the v5 README, or with the implementation :)

**Comment by rob-balfre** [comment]
@hmnd thanks for raising this.  The docs are wrong for `suggestions`, it accepts an array not a boolean. I'll fix up.

**Comment by rob-balfre** [comment]
Fixed in v5.0.0-beta.2
