### ISSUE TITLE
Cannot interact with select inputs on iOS devices

### ISSUE THREAD

**Issue by gholaday** [rob-balfre/svelte-select#397]
Ive noticed tapping the select input doesnt work on real-life iphone devices. I even tested the REPL example and got the same behavior. It works fine on all Android devices that I have tested. Any ideas?

**Comment by rob-balfre** [comment]
@gholaday seems fine to me via Xcode's simulator.  Can you share the REPL please? Thanks

**Comment by ZerdoX-x** [comment]
I also have some issues with svelte-select which appear only on ios devices (simulator & real devices). Here is video:

https://user-images.githubusercontent.com/49815452/165935485-f6872600-6577-4c38-9059-4afee5476442.mov

I will try to implement REPL later.

**Comment by ZerdoX-x** [comment]
I investigated my issue from the video above:

https://gist.github.com/avesus/957889b4941239490c6c441adbe32398
https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d
WEBKIT BUGS:
https://bugs.webkit.org/show_bug.cgi?id=153224
IONIC ISSUES:
https://github.com/ionic-team/ionic-framework/issues/2256
https://github.com/ionic-team/ionic-framework/issues/2285
https://github.com/ionic-team/ionic-framework/issues/9346
SO QUESTIONS:
https://stackoverflow.com/questions/56351216/ios-safari-unwanted-scroll-when-keyboard-is-opened-and-body-scroll-is-disabled
https://stackoverflow.com/questions/39626302/ios-chrome-safari-unwanted-scrolling-when-focusing-an-input-inside-the-modal
https://stackoverflow.com/questions/31280864/ios-8-page-jumping-on-input-focus
https://stackoverflow.com/questions/32895105/prevent-fixed-elements-from-jumping-on-input-focus-in-mobile-safari

Not related to svelte-select at all. Just some bugs with mobile webkit. Managed to workaround this by replacing html as main scrollable element on the page via body.

**Comment by gholaday** [comment]
@rob-balfre sorry this is so late, wanted to mention after upgrading to the newest v5 beta the issue goes away. Very strange but thanks!

**Comment by Yehya22** [comment]
I experienced the same issue while using version 5.8.3 along with Svelte 5.12.0.
