### ISSUE TITLE
Is it possible to use the select items for navigation like an anchor?

### ISSUE THREAD

**Issue by chaosprint** [rob-balfre/svelte-select#399]
I use href but it triggers full page refresh. Pushstate messes up the history and makes the go back button mulfunction. Is it possible to add an a tag as the select item?

**Comment by rob-balfre** [comment]
` export let getOptionLabel = (option, filterText) => {
        return option.isCreator ? `Create \"${filterText}\"` : option[labelIdentifier];
 };`

Not really but you can override this method a return any HTML you'd like.  I made a nice REPL to show you but then the REPL wouldn't save 😭. Hopefully you can figure it out.

**Comment by ZerdoX-x** [comment]
Yep, It's possible for example like this: https://svelte.dev/repl/fcc351e081614bcab4236744231016fb?version=3.48.0
