### ISSUE TITLE
Using `justValue` with the store doesn't update Select component from external store updates

### ISSUE THREAD

**Issue by jnschrag** [rob-balfre/svelte-select#401]
Hello! Super excited to see the changes in progress for version 5. 🎉

I found what might be a bug (or more realistically, user error on my part) when testing out the v5 beta in my project. I put together a [REPL](https://svelte.dev/repl/a1f5471956d54558b4fcf7604a49f187?version=3.47.0) that illustrates the problem.

I was trying to connect the new `justValue` property up to a value in my project's store. If I change the value by selecting an item in the dropdown, the store updates correctly. But if I change the store value from another component (like clicking a button), the store value updates **but** the select component doesn't update to show that. As far as I can tell, the select component only updates if the value is set to the whole item object `[{value: value, label: label}]`, so saving only the value in the store and updating it from elsewhere doesn't work.

![image](https://user-images.githubusercontent.com/1896496/166061898-0da90cb6-410e-4974-bf7f-7c997515fc9e.png)
In the image from the REPL, I would expect the Select component to show me "Four" as selected to match the `$selectedValue`.

Any help you can provide is greatly appreciated! If I'm overlooking something with the implementation, I'd appreciate a pointer to the right place to look.

**Comment by rob-balfre** [comment]
I think I need to update the docs for `justValue` or rename it, it's causing confusing. It's meant to be a read-only.

**Comment by jnschrag** [comment]
Ooh yes, that would be helpful. I had not realized that at all. I did eventually accomplish the goal of syncing up just the value, but it took a little more finagling than I had hoped.
