### ISSUE TITLE
Clickable custom chevron icon

### ISSUE THREAD

**Issue by jdromero88** [rob-balfre/svelte-select#403]
It is possible to make the custom chevron icon clickable?
I used the solution mentioned in the issue #295 to add a custom chevron icon to the select. But if i click on the actual icon the select is not opening.

Here is a [repl](https://svelte.dev/repl/6ecb8b04f0a645f49738406e256e461a?version=3.48.0)

**Comment by ZerdoX-x** [comment]
> It is possible to make the custom chevron icon clickable?

Why you need it to be clickable? I don't think it's a good UI/UX case.


> But if i click on the actual icon the select is not opening.

Just use `pointer-events: none;` You can read about this property more [here](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) here is [browser's support](https://caniuse.com/pointer-events)

**Comment by rob-balfre** [comment]
Fixed in latest beta

https://svelte.dev/repl/53eee9295627449baf48ce62ebf247c3?version=3.48.0
