### ISSUE TITLE
--focusBorder

### ISSUE THREAD

**Issue by OlmoDalco** [rob-balfre/svelte-select#405]
I would like to create a Select Input with a border with of 1px and an focusBorder with of 2px to highlight the current focus. However it seems to me, this is currently not possible.

**Comment by ZerdoX-x** [comment]
Just use css?

**Comment by rob-balfre** [comment]
Added in v5.0.0-beta.20

https://svelte.dev/repl/cac78f915b734fb8beca695e0083d002?version=3.50.1
