### ISSUE TITLE
`Event.path` is deprecated

### ISSUE THREAD

**Issue by ZerdoX-x** [rob-balfre/svelte-select#406]
'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.

This PR introduced: https://github.com/rob-balfre/svelte-select/pull/106

Current code in master:
https://github.com/rob-balfre/svelte-select/blob/ea8a7f441ec6785db794d3d67538c59dddae10ed/src/Select.svelte#L539-L542

**Comment by rob-balfre** [comment]
Fixed in latest beta
