### ISSUE TITLE
[v5] ChevronIcon component override not working

### ISSUE THREAD

**Issue by madeleineostoja** [rob-balfre/svelte-select#413]
Just upgraded to the v5 beta and I can't get the `ChevronIcon` component override working. Is there a requirement I'm missing? My existing overrides for `Item` and `Selection` from v4 are still working well

**Comment by ZerdoX-x** [comment]
Provide REPL

**Comment by madeleineostoja** [comment]
Sorry just nuked my node modules and that fixed it, must have been a stale dep somewhere
