### ISSUE TITLE
Is it possible to show images when an element is selected?

### ISSUE THREAD

**Issue by Genebson** [rob-balfre/svelte-select#415]
👋, what I'm trying to achieve is something like [async input](https://svelte.dev/repl/3e032a58c3974d07b7818c0f817a06a3?version=3.20.1) but what I would like to do is select an option and then see the image and text inside that input, is that possible?

**Comment by rob-balfre** [comment]
Yes, it's just a bit fiddly and involves replacing the `Selection` component. 
REPL https://svelte.dev/repl/6f4f5793b2964a38a0be0891c644d4cd?version=3.48.0
