### ISSUE TITLE
Disable autofill on Select Box

### ISSUE THREAD

**Issue by Edward-Heales** [rob-balfre/svelte-select#418]
Hi, I cannot find the css or html option to disallow autofill of usernames and passwords on my select box.
Pictured below.
![image](https://user-images.githubusercontent.com/78352116/171140252-771338c2-861c-47f2-aacb-bd49adc578d0.png)

Inside the select box on the right you can see the autofill option.
Does anyone know how to disable this?

**Comment by bewards** [comment]
Maybe the inner input needs the autocomplete property set as such:

`<input type="text" autocomplete="off" />`

try using the `inputAttributes` property to pass in that key-value:

`<Select inputAttributes={{ autocomplete: "off" }} />`

**Comment by Edward-Heales** [comment]
> Maybe the inner input needs the autocomplete property set as such:
> 
> `<input type="text" autocomplete="off" />`
> 
> try using the `inputAttributes` property to pass in that key-value:
> 
> `<Select inputAttributes={{ autocomplete: "off" }} />`

Unfortunately this doesn't seem to have worked.

**Comment by rob-balfre** [comment]
@Edward-Heales that's the lastpass extension, it's nothing to do with svelte-select.  You can try changing the id to something other than username or password.

**Comment by Edward-Heales** [comment]
Will keep looking elsewhere then, thank you for trying.
