### ISSUE TITLE
List bouncing during scroll.

### ISSUE THREAD

**Issue by cyaris** [rob-balfre/svelte-select#422]
List bouncing during scroll, likely related to `computePlacement` function. This is on the newest version of V5.

**Comment by rob-balfre** [comment]
@cyaris thanks for reporting.  I can't seem to reproduce this one, got a REPL example?

**Comment by cyaris** [comment]
Hi @rob-balfre, I'm having trouble replicating the issue in a repl. You can mark as closed and I'll open a new issue if I find more information on what's causing it (assuming it's component-related). Thanks!
