### ISSUE TITLE
Allow `list-container` class to be set dynamically

### ISSUE THREAD

**Issue by spencermize** [rob-balfre/svelte-select#427]
Hi, 

Is it possible to allow the `.list-container` class to be overridden? Since it's now appended to the global body, targeting such a common selector name with CSS could potentially be a bit dicey. Thanks!

**Comment by ZerdoX-x** [comment]
> Since it's now appended to the global body, targeting such a common selector name with CSS could potentially be a bit dicey.

Trying to revert this dangerous behaviour in #428

**Comment by rob-balfre** [comment]
> Hi, 
> 
> Is it possible to allow the `.list-container` class to be overridden? Since it's now appended to the global body, targeting such a common selector name with CSS could potentially be a bit dicey. Thanks! 

Yes. Great idea. Will update shortly. Thanks
