### ISSUE TITLE
Couldn't upgrade from 5.0.0-beta11 to 5.0.0-beta12 due to breaking changes and fix of #402

### ISSUE THREAD

**Issue by ZerdoX-x** [rob-balfre/svelte-select#428]
_Not the best_ solution in my opinion.

https://github.com/rob-balfre/svelte-select/blob/7e74a32e26a35accdd86c0ce4ad1cf43e4186e65/src/lib/Select.svelte#L591-L594

Completely broke [my current select component](https://svelte.dev/repl/1edff35beec146b2b94ae31d0332adcb?version=3.48.0). For now upgrading from v11 to v12 is blocking all usage of this component. 

It's better to revert fix of this issue. It least issue could be workarounded with css, but now svelte-select just behaves unpredictably.

My svelte-select component I was using: https://svelte.dev/repl/1edff35beec146b2b94ae31d0332adcb?version=3.48.0

To feel my pain just replace `beta.11` with `beta.12` in `Select.svelte:2`

---

Wanted to upgrade recently because of click outside issue - https://github.com/rob-balfre/svelte-select/commit/36c55b438befb0abf4ba8ffa38b58a00e595441e. filterText just gets resetted every time I click outside

**Comment by ZerdoX-x** [comment]
Hero of the occasion: #402

**Comment by rob-balfre** [comment]
@ZerdoX-x there is little point making massive REPLs like that, no way to pinpoint an issue that way.  Must of taken you ages too!

**Comment by ZerdoX-x** [comment]
Migration from beta11 to beta16: bind parent element and pass it to `Select` component as `appendListTarget` prop.

Closing issue as similar one https://github.com/rob-balfre/svelte-select/issues/431 already resolved.
