### ISSUE TITLE
List bouncing during scroll.

### ISSUE THREAD

**Issue by cyaris** [rob-balfre/svelte-select#429]
Re-opening this issue because I found a solution. Still having trouble replicating it in a REPL.

Description: List bouncing during scroll, likely related to `computePlacement` function. This is on the newest version of V5.

Solution: 
```
.list {
	position: absolute !important;
	top: unset !important;
}
```

**Comment by cyaris** [comment]
Got my solution from this issue: https://github.com/rob-balfre/svelte-select/issues/402

**Comment by rob-balfre** [comment]
Need a REPL or example to pinpoint the actual problem.  Will keep open. Thanks

**Comment by ZerdoX-x** [comment]
Sorry, @rob-balfre but your "fix" caused three more issues:
1. Now it's harder to style your component as you thought that appending your list globally would be a great solution: #427
2. Some another bug (?), #429 which is waiting for reproduction (wrong label tho. it doesn't need help)

**Comment by cyaris** [comment]
Also wanna note, this solution works in Beta v11, but not in Beta v12.

**Comment by ZerdoX-x** [comment]
Same. Would be better to revert that fix

**Comment by rob-balfre** [comment]
v16 should help with this. If not reopen with a REPL example please.

Thanks
