### ISSUE TITLE
List not being appended to main Select wrapper in beta v11 and above.

### ISSUE THREAD

**Issue by cyaris** [rob-balfre/svelte-select#431]
I haven't found the actual bug in the code, but in checking my HTML, it seems that the list is getting appended to the bottom of the page, rather than appearing within the existing svelte-select wrapper element.

**Comment by spencermize** [comment]
i believe this is happening to compensate for the issues people were having here: https://github.com/rob-balfre/svelte-select/issues/402 (other conversation here: https://github.com/rob-balfre/svelte-select/issues/428). i think 402 can be fixed without appending to the body by using an overflow: hidden breakout technique, but i might be oversimplifying.

**Comment by rob-balfre** [comment]
Fixed in `5.0.0-beta.16` https://svelte.dev/repl/5c36b10164784d66b3734bab130da719?version=3.49.0
