### ISSUE TITLE
Possibility for XSS injection (duplicate of #373)

### ISSUE THREAD

**Issue by quasarchimaere** [rob-balfre/svelte-select#433]
since repro steps have been posted, and the issue is still present wouldnt we want to re-open it?

- #373 "Possibility for XSS injection"

**Comment by rob-balfre** [comment]
Fixed in v16

**Comment by quasarchimaere** [comment]
@rob-balfre not to be a stickler here, but can you please explain to me why the fix is adding an extra function that strips any (possibly) bad content from the option, rather than just removing the `@html` parameter that circumvents the built in svelte escaping?

**Comment by rob-balfre** [comment]
Because I use it ☺️

**Comment by ZerdoX-x** [comment]
The only way to avoid XSS injection (if your code implies vulnerability) is to pass custom components.

@rob-balfre reopen this issue as filtering doesn't help you with XSS, you can find plenty of examples people bypassing XSS filters. `@html` should not be used when user is not aware of this, this is possible vulnerability for the user.
