### ISSUE TITLE
Select list does not render above standard HTML `<dialog>`

### ISSUE THREAD

**Issue by tarngerine** [rob-balfre/svelte-select#434]
Since svelte-select portals the list to the bottom of document body, it can never be above "top layer" which is where `<dialog>` renders to ([more reading](https://stackoverflow.com/questions/41815069/is-it-possible-to-position-a-div-on-top-of-a-dialog-tag-that-is-not-its-parent)). 

Wondering if there's an option to disable the portaling and render the list inline next to the root svelte-select element?

<img width="358" alt="image" src="https://user-images.githubusercontent.com/1629901/177621167-cb61b7bb-88a9-472e-85c6-f391988478ec.png">

**Comment by quasarchimaere** [comment]
i had the same issue with v5 beta and sveltekit (using a the select box in a sveltestrap Modal)
my quick fix was to set the z-index of the list-container and the position to relative

code snippet:
```
// svelte-select style workaround (for overlays)
.list-container {
  z-index: 2000;
  position: relative;
}
```

**Comment by rob-balfre** [comment]
@tarngerine I've added a prop `appendListTarget` that lets you append the list wherever you'd like. 

REPL:
https://svelte.dev/repl/5c36b10164784d66b3734bab130da719?version=3.49.0

**Comment by tarngerine** [comment]
amazing! thank you!
