### ISSUE TITLE
[V5] css properties override do not seem to work on list or items

### ISSUE THREAD

**Issue by vboulaye** [rob-balfre/svelte-select#440]
Hi,

I am trying to migrate from V4 to V5. 
I use css properties to apply a custom theme to the Select Item.
I updated the names of the properties but it does not work as before.

I tested it in the REPL and it does not seem to work there either.
For example if I add to the following properties to the  .themed  class in the [REPL](https://svelte.dev/repl/9df1a81865564b2db6163a04445b311c?version=3.49.0) :
```
        --item-is-active-bg: #000000;
        --item-hover-bg: #666666;
        --item-hover-color: #fefefe;
``` 

I expect the colors of the item in the list to change but they stay blue.
It seems that only the properties on the first "level" of the svelte-sleect component can be changed.
Is there another way to change the properties used inside List or Item ?

**Comment by rob-balfre** [comment]
Got 2 options here...
Use :root or appendListTarget... See REPL
https://svelte.dev/repl/e0cd96c0711a46f4a390aaf486d7283c?version=3.49.0

**Comment by vboulaye** [comment]
Thanks, it works fine! (I used the :root selector)

**Comment by EskelCz** [comment]
@rob-balfre borderRadius didn't work for me either, not even with the :root selector. Had to use .svelte-select and !important.
