### ISSUE TITLE
creation of items broken in beta

### ISSUE THREAD

**Issue by andreasnuesslein** [rob-balfre/svelte-select#441]
Hello @rob-balfre ,

I think item creation is broken in the beta - https://svelte.dev/repl/7c23c33cb91045c2af1a95500967d295?version=3.49.0

the `itemCreated` is an unknown prop, and the `createItem` fires on every keystroke.

are the docs maybe not up-to-date on this?

cheers

**Comment by rob-balfre** [comment]
@andreasnuesslein  you were missing the on:eventname should be...

https://svelte.dev/repl/c37a1ea888304e9b8d8d3e134eb5932f?version=3.49.0

**Comment by andreasnuesslein** [comment]
:see_no_evil:   i'm sorry, yes it was PEBKAC

**Comment by rob-balfre** [comment]
TIL problem exists between chair and keyboard 😂😂😂
