### ISSUE TITLE
CSS typo: spinnerLeft -> spinnerTop

### ISSUE THREAD

**Issue by einars** [rob-balfre/svelte-select#442]
```
.spinner {
  ...
- top: var(--spinnerLeft, 11px);
+ top: var(--spinnerTop, var(--spinnerLeft, 11px));
}
```

or even just var(--spinnerTop, 11px), without the compatibility fallback, for apparently nobody's used and noticed that yet

https://github.com/rob-balfre/svelte-select/blob/328a9196e37b428062492becb239be1fc717c755/src/Select.svelte#L789

**Comment by rob-balfre** [comment]
Removed in v5
