### ISSUE TITLE
Blur event firing constantly

### ISSUE THREAD

**Issue by caleidon** [rob-balfre/svelte-select#444]
I notice that when you use the on:blur event and print something out in the console, it will fire every single time you click outside of the search box.

The intended behavior should be that it only fires the blur event if it had the focus, not every single time I click outside of it. Is this a bug?

**Comment by rob-balfre** [comment]
Can you confirm if this happens on the latest beta please? thanks

**Comment by bolstycjw** [comment]
this happens on ^5.0.0-beta.40, had to use a debounce/throttle to workaround this issue
