### ISSUE TITLE
Bypass selectable=false with keyboard

### ISSUE THREAD

**Issue by BAllendorf-OneFiber** [rob-balfre/svelte-select#447]
While I can't selected an item with `selectable: false` by mouse/clicking, I can do select it by **typing the label and pressing the enter key**.

This works for the `Complex` [advanced example](https://svelte.dev/repl/3df87e32340e4e9e85bf371becae2af0?version=3.49.0). When using Groups, one hast to press the up/down arrow key and afterwards one can select the item with enter (5.0.0-beta.16).

I'm not sure if this is a feature or a bug, but I expected it to not work like this.

**Comment by rob-balfre** [comment]
Partially fixed in beta.17 but you can still hit tab to select.  Will fix up.  Thanks

**Comment by rob-balfre** [comment]
Fixed in `5.0.0-beta.23`.

**Comment by BAllendorf-OneFiber** [comment]
Thank you for looking into this! 

I just tried it out [here](https://svelte.dev/repl/3df87e32340e4e9e85bf371becae2af0) and think there are still a few edge cases:
- in the `complex` example, I can't jump out via `ENTER`  but, for example, by using `TAB` (and the input still says "Cake" even though, for complete nonsense, the input gets reset)
- in `multi`, I can enter "Cake" and hit `ENTER`, it gets added as any other value would
- `group` is very special: after I typed two characters belonging to "Cake" (e.g., "Ca" or "ak"), Javascript runs into a RangeError "Maximum call stack size exceeded"

**Comment by rob-balfre** [comment]
@BAllendorf-OneFiber `5.0.0-beta.28` should squash those edge cases.  Thanks for finding them.

**Comment by BAllendorf-OneFiber** [comment]
Awesome, many thanks for the quick response! 👍
