### ISSUE TITLE
Some custom CSS props not recognized in component scope

### ISSUE THREAD

**Issue by yadoga** [rob-balfre/svelte-select#448]
Placing custom CSS props works as long as they are scoped to :root.

But when scoped for a component, only some props seems to work. Example:

```
<style lang="sass">
    :root
        --background: blue
        --list-background: red
        // => both working OK
    .select
        --background: blue
        // => working OK
        --list-background: red
        // => not working
</style>
```

_using 5.0.0-beta.16_

**Comment by yadoga** [comment]
Wrong expection by me possibly.

Matching the element then enables the use of variables. In this case

```
    :global(.svelte-select-list)
        --list-background: red
        // => Works
		
```

I was under the impression that variables would be inherited from scoped compents elements

**Comment by rob-balfre** [comment]
@yadoga should work as expected in 5.0.0-beta.17?

https://svelte.dev/repl/378787d7f9c04ba491d7f69dd3acb07f?version=3.49.0

**Comment by yadoga** [comment]
Works now, thank you!
