### ISSUE TITLE
CSS --multiItemColor prop missing to style the text color of multi item cards

### ISSUE THREAD

**Issue by adrisanchu** [rob-balfre/svelte-select#449]
I have tried to change the text color of a multi item on dark theme, but I couldn't find any prop that did the job.
I think the easiest way to do will be to add the following CSS variable on [MultiSelection.svelte](https://github.com/rob-balfre/svelte-select/blob/master/src/MultiSelection.svelte)

`.multiSelectItem_label {
     color: var(--multiItemColor, black);
 }`

**Comment by rob-balfre** [comment]
Added in v5.0.0-beta.20

https://svelte.dev/repl/408a2d56f08f4829a848d1af173d68be?version=3.50.1
