### ISSUE TITLE
v5 beta 16 renders large item lists very slowly

### ISSUE THREAD

**Issue by CameronNemo** [rob-balfre/svelte-select#451]
Hello,

I have been trying out v5 beta 16 and I noticed that large items list can take a second or three to render. I am not using debounceWait or loadOptions (I did try setting debounceWait to 10000 to rule it out; it had no effect).

I was unable to try from the tip of feature/v5 because npm installing from the branch (`npm install git+https://github.com/rob-balfre/svelte-select#feature/v5`) did not work. So I apologize if this performance issue is fixed.

Thanks.

**Comment by rob-balfre** [comment]
@CameronNemo remove virtualList, instead use the named slots provided... see migration guide for pointers.

Any issues and i'll try to put an example in the docs.  Let me know, thanks!

**Comment by CameronNemo** [comment]
Hmm so I really don't know what happened but it seems like it sped up overnight. Which does not make sense. But I guess if it ain't broke.
