### ISSUE TITLE
Some CSS variables bugs in beta17

### ISSUE THREAD

**Issue by yadoga** [rob-balfre/svelte-select#454]
~~Found some bugs regarding CSS variables.~~

~~--clear-icon-color~~
~~--item-active-background~~

~~… are not being used at the moment.~~

Also the select input now shows a cursor. 

_using 5.0.0-beta.17_

Edit: removed a deprecated variable
Edit: Above Variables do work. I scoped a wrong element in my tests. Cursor remains wonky, though. :)

**Comment by yadoga** [comment]
the blinking cursor in the Input can be turned off via the `caret-color `attribute in CSS:

```
.select {
	:global(input) {
		caret-color: transparent
	}
}
```

**Comment by rob-balfre** [comment]
The blinking cursor is a feature, not a bug. Maybe the default should be `carot-color: transparent` until filterText has length.

**Comment by yadoga** [comment]
all good, I wrongly assumed `searchable` would not be `true` by default. 

Came from a classic usecase of a regular Select in this instance, where no key inputs are needed. Thought of making searchable false by default…
