### ISSUE TITLE
Longer item labels not wrapping

### ISSUE THREAD

**Issue by yadoga** [rob-balfre/svelte-select#458]
![wrap](https://user-images.githubusercontent.com/685830/184217173-181980c0-b26a-44b8-8273-12e1cccec930.jpg)

_Using beta17_

**Comment by rob-balfre** [comment]
Can you make a REPL for this please? Thanks

**Comment by yadoga** [comment]
Sure: 
https://svelte.dev/repl/bdb17ddd0a5743bf9bc5248600ed1417?version=3.49.0
