### ISSUE TITLE
Bug for Input on mobile viewports [beta version]

### ISSUE THREAD

**Issue by yadoga** [rob-balfre/svelte-select#459]
Using this Repl in Chrome's inspector with a mobile viewport, items are not selected.
https://svelte.dev/repl/bdb17ddd0a5743bf9bc5248600ed1417?version=3.49.0

https://user-images.githubusercontent.com/685830/184474000-a182cfa8-ecda-4ff9-a68c-d8640950ee55.mov

In Firefox clicking the Input opens the list for just a split second:

https://user-images.githubusercontent.com/685830/184474092-52d58917-8e37-4948-b543-fb45553be83e.mov

Both are working in the default desktop viewports. I have not tested this yet on a real phone, but would be good to find the bug here if only just for testing the selects.

**Comment by rob-balfre** [comment]
This only seem happens in the Svelte REPL, going to close this.  Feel free to reopen if you find it happening in a real world.  Thanks

**Comment by mikekok** [comment]
> This only seems to happen in the Svelte REPL, going to close this. Feel free to reopen if you find it happening in a real world. Thanks

I'm facing the exact same issue right now. It works perfectly on desktop but doesn't seem to work for mobile devices (both Firefox mobile viewport and real device - OnePlus 8T running Android 13)

https://user-images.githubusercontent.com/9141685/209222837-93860240-40ef-41aa-aa40-2103702c0e4b.mp4

**Comment by rob-balfre** [comment]
@mikekok which version of svelte-select?

**Comment by rob-balfre** [comment]
@mikekok does the same happen with https://svelte-select-examples.vercel.app/examples/props/items on your phone?

**Comment by mikekok** [comment]
> @mikekok which version of svelte-select?

5.0.0

> @mikekok does the same happen with https://svelte-select-examples.vercel.app/examples/props/items on your phone?

Yes, same issue for both Firefox mobile viewport and actual phone.

**Comment by rob-balfre** [comment]
@mikekok thanks, will take a look. What browser on your phone do you use?  Firefox?

**Comment by mikekok** [comment]
> @mikekok thanks, will take a look. What browser on your phone do you use? Firefox?

Yeap, you're right, it's a firefox issue, it works fine in Edge and Chrome (both desktop emulator and real mobile device).

**Comment by rob-balfre** [comment]
@mikekok fixed in v5.0.1 (hopefully!)

**Comment by mikekok** [comment]
> 

Works perfectly fine in 5.0.1, thanks for the instant response!

**Comment by rob-balfre** [comment]
@mikekok great, thanks for reporting!
