### ISSUE TITLE
icon for each item

### ISSUE THREAD

**Issue by Roxgame95** [rob-balfre/svelte-select#460]
am trying to add icon for each item is that possible
![Select-Option-Icons-customSelect](https://user-images.githubusercontent.com/51464152/185009044-7e8055af-6532-41df-82b2-fb2fee3b396a.jpg)

**Comment by rob-balfre** [comment]
@Roxgame95 yes, use `item` and `selection` named slots (v5 beta).

**Comment by harunzafer** [comment]
Hi !

Can you give an example for this?
