### ISSUE TITLE
default font size for everything should be 16px to avoid layout issues on mobile...[V5]

### ISSUE THREAD

**Issue by rchrdnsh** [rob-balfre/svelte-select#462]
anytime a font size smaller than 16px is used iOS will zoom in the UI, which is generally not desirable. I recommend setting default font-size to 16px.

XD

**Comment by rob-balfre** [comment]
@rchrdnsh thanks, good to know. Will update.

**Comment by rchrdnsh** [comment]
oh, was it not supposed to be closed? my bad
