### ISSUE TITLE
List appears abruptly on scroll event on mobile (V5)

### ISSUE THREAD

**Issue by ismix** [rob-balfre/svelte-select#463]
Version: 5.0.0-beta.19
Platform: mobile

On mobile, if a scroll event is initiated by touching the select component area, the list appears. It is especially troublesome for pages with many select components. The issue started somewhere after 5.0.0-beta.16, might be because the click handler is moved from "click" event to "pointerdown" event. 

Here is a simple REPL to repro the issue, just open in a mobile browser and try to scroll by tapping on the select area: https://svelte.dev/repl/439b03d01e8f4376aa5a75ed0225fbcb?version=3.49.0

**Comment by rob-balfre** [comment]
Should be fixed in `5.0.0-beta.24`. Thanks
