### ISSUE TITLE
failed to load module for ssr: ./filter

### ISSUE THREAD

**Issue by Cluster2a** [rob-balfre/svelte-select#464]
Since the upgrade I am getting the following error:

![image](https://user-images.githubusercontent.com/84905165/188139889-ebd393a7-4379-4585-a600-4b5008bd7515.png)

Svelte: 3.49.0
Kit: 1.0.0-next.405

Downgrading to [5.0.0-alpha.10](https://www.npmjs.com/package/svelte-select/v/5.0.0-alpha.10) works fine.

**Comment by rob-balfre** [comment]
@Cluster2a seems fine with latest kit and beta...

https://stackblitz.com/edit/sveltejs-kit-template-default-2b4wc9?file=package.json

**Comment by BetaConnector** [comment]
@rob-balfre, you are right - I haven't updated to the latest version. Thanks!
