### ISSUE TITLE
new feature: create new item

### ISSUE THREAD

**Issue by BetaConnector** [rob-balfre/svelte-select#470]
Hey,

svelecte supports creating custom items (Creatable): https://mskocik.github.io/svelecte/#playground.

I am using svelte-select in my project, but now I am facing the issue that the user needs to create their own options.

Is this feature planned?

Thanks in advance - Alex

**Comment by BetaConnector** [comment]
I found the option _isCreatable_. Sorry for that.

**Comment by rob-balfre** [comment]
> @rob-balfre this option seems not available anymore in V5 ?

See the migration guide for an example and let me know how you get on...

https://github.com/rob-balfre/svelte-select/blob/feature/v5/MIGRATION_GUIDE.md

**Comment by kl3sk** [comment]
> > @rob-balfre this option seems not available anymore in V5 ?
> 
> See the migration guide for an example and let me know how you get on...
> 
> https://github.com/rob-balfre/svelte-select/blob/feature/v5/MIGRATION_GUIDE.md

My bad, I did see this section.

Any REPL example ?

**Comment by rob-balfre** [comment]
> > > @rob-balfre this option seems not available anymore in V5 ?
> > 
> > See the migration guide for an example and let me know how you get on...
> > 
> > https://github.com/rob-balfre/svelte-select/blob/feature/v5/MIGRATION_GUIDE.md
> 
> My bad, I did see this section.
> 
> Any REPL example ?

All good. No REPL but I'll add an example to the main site tomorrow. It's late in Sydney 😁

**Comment by kl3sk** [comment]
> > > > @rob-balfre this option seems not available anymore in V5 ?
> > > 
> > > 
> > > See the migration guide for an example and let me know how you get on...
> > > https://github.com/rob-balfre/svelte-select/blob/feature/v5/MIGRATION_GUIDE.md
> > 
> > 
> > My bad, I did see this section.
> > Any REPL example ?
> 
> All good. No REPL but I'll add an example to the main site tomorrow. It's late in Sydney 😁

Ok I understand that 😉. I'll try it on my side until you update it, because at this point it doesn't work for me.

Thank you
