### ISSUE TITLE
inputAttributes.name applied to both search input and hidden value input

### ISSUE THREAD

**Issue by hmnd** [rob-balfre/svelte-select#471]
As seen below, when `inputAttributes.name` is provided, the name is applied to both the search field and the hidden field containing the current value. The [internal `_inputAttributes`](https://github.com/rob-balfre/svelte-select/blob/cceaf9713b7b5e29da799d0668063cfac9a4e522/src/lib/Select.svelte#L93-L114) should either always have its name property always overridden, or there should be a separate way to specify a name for just the hidden input (preferable IMO). Providing a name value to the hidden input allows for the component to be compatible with `<form action>` submission without any extra work, so I believe it's a critical feature to have.

![image](https://user-images.githubusercontent.com/12853597/190602349-fd074909-a859-4f10-9cd6-d163de3e46e2.png)

**Comment by rob-balfre** [comment]
Added `name` prop that only applies to hidden field in `5.0.0-beta.24`.  Thanks
