### ISSUE TITLE
Race condition with loadOption set

### ISSUE THREAD

**Issue by PlkMarudny** [rob-balfre/svelte-select#472]
I retrieve data using loadOption. If I press 'Enter' (to select) before the list opens, the component crashes:

![image](https://user-images.githubusercontent.com/4361591/190618320-95f1d9ab-a7a8-4967-939b-c43e04060632.png)

in filter.js:
```
 let filterResults = items.filter((item) => {
        let matchesFilter = itemFilter(item[label], filterText, item);
        if (matchesFilter && multiple && value?.length) {
            matchesFilter = !value.some((x) => {
                return x[itemId] === item[itemId];
            });
        }

        return matchesFilter;
    });
```

5.0.0-beta.19

**Comment by rob-balfre** [comment]
@PlkMarudny can you supply a REPL please? Thanks
