### ISSUE TITLE
Large data set makes the component slow

### ISSUE THREAD

**Issue by BioMatti** [rob-balfre/svelte-select#474]
Using a large dateset with more than 2000 elements will create some delays specifically after:
- first click on the select element
- first character typed

If you can give me some direction on what could be causing this delay I am willing to help to improve this Svelte component.

Here is a demo REPL:
https://svelte.dev/repl/3931480ff2c1416ab16e3cb18abcd4cd?version=3.12.1

I have found another Svelte select component not as well developed as yours at the link above that handles large datasets better.
https://svelte.dev/repl/286f92d1bddd4d3a97b6289e584b7411?version=3.22.3

**Comment by rob-balfre** [comment]
https://svelte.dev/repl/2ac9ef0a8bdb42a993f2f537cdfd96bc?version=3.12.1
