### ISSUE TITLE
Some CSS variables are ignored

### ISSUE THREAD

**Issue by rogerfar** [rob-balfre/svelte-select#475]
It seems that some CSS variables are not honored, for example font-size:
https://svelte.dev/repl/b771ec4253594153b649e9e6dc027ced?version=3.50.1

It's all the variables that are defined here:
https://github.com/rob-balfre/svelte-select/blob/feature/v5/src/lib/Select.svelte#L869

This should probably be:
```
font-size: var(--font-size, 16px);
```

**Comment by rob-balfre** [comment]
@rogerfar thanks, good spot.
