### ISSUE TITLE
Documentation: how to pass name parameter to SvelteKit's <form method="POST>

### ISSUE THREAD

**Issue by VoiceOfSoftware** [rob-balfre/svelte-select#477]
I wrote a little tutorial here that shows how to send <Select> data to a SvelteKit form https://www.reddit.com/r/SvelteKit/comments/xtgu97/how_to_pass_value_of_select_to_pageserverjs/

**Comment by sawyerclick** [comment]
This just solved hours of headache for me! Ideally there'd be a way to access the formData values without using `.getAll(value).slice(1)`, especially if it's not a multi-select input

**Comment by rob-balfre** [comment]
I've been exploring form actions with v5 beta. Latest version example here...
Useful?

https://svelte-select-examples.vercel.app/examples/advanced/form-action

**Comment by VoiceOfSoftware** [comment]
Yes!! I haven't tried it yet, but looking at your example, it looks so much simpler and intuitive. Having the **name** parameter helps a lot, compared to the wacky {{}} syntax I had to come up with.
