### ISSUE TITLE
V5 Bug: listAutoWidth is inverted

### ISSUE THREAD

**Issue by crimx** [rob-balfre/svelte-select#478]
v5 https://github.com/rob-balfre/svelte-select/blob/13d8b712584b28c46f06e2ad335680ba647cd0bb/src/lib/Select.svelte#L636

v4 https://github.com/rob-balfre/svelte-select/blob/328a9196e37b428062492becb239be1fc717c755/src/List.svelte#L221

**Comment by rob-balfre** [comment]
Think it makes sense for v5 to keep as is. It's less about the CSS attribute but more about linking the width of the select box and the list element.

See: https://svelte-select-examples.vercel.app/examples/props/list-auto-width
