### ISSUE TITLE
Could not resolve './filter' when using unstyled version

### ISSUE THREAD

**Issue by extremelygooddeveloper** [rob-balfre/svelte-select#479]
Getting
`Could not resolve './filter' from node_modules/.pnpm/svelte-select@5.0.0-beta.30_c36sqhgzdfaw4kmxogryyrffx4/node_modules/svelte-select/no-styles/Select.svelte`

when using unstyled component, works fine with the default component.

**Comment by rob-balfre** [comment]
@extremelygooddeveloper  fixed error in `5.0.0-beta.31` but could do with some PRs to improve the example `tailwind.css` if possible?  I don't use tailwind in my day job so don't really know what I'm doing! Thanks

**Comment by rob-balfre** [comment]
If I add to examples site it applies it's styles globally, not sure how to scope them... 
https://svelte-select-examples.vercel.app/examples/advanced/tailwind

**Comment by extremelygooddeveloper** [comment]
Thanks! 
I'm not really well versed in tailwind either, so i don't think I can contribute to that.
