### ISSUE TITLE
v3 - selected item label doesnt display when searched for and selected

### ISSUE THREAD

**Issue by dontwork** [rob-balfre/svelte-select#48]
Im not sure how to recreate this but I had an option in my list with the name 'A5', if i type A5 and then A5 is the only item in the list then press enter the select box goes empty despite the fact the item has been selected. All other methods of selecting seem to work it just seems to be when you have typed in to filter that when you select an option from the filtered list it does not appear in the select box

**Comment by felipedrumond** [comment]
Couldn't recreate that. Could you share your code?

**Comment by rob-balfre** [comment]
He's talking about the v3 branch @felipedrumond.  It's still WIP, I'll take a look.

**Comment by dontwork** [comment]
thanks!
