### ISSUE TITLE
floating-ui flashing

### ISSUE THREAD

**Issue by rogerfar** [rob-balfre/svelte-select#480]
When using `strategy: 'fixed'` the list flashes from the left top to the correct position:

https://svelte.dev/repl/62a0199924ef4ddd980822860891b228?version=3.51.0

Not sure if this is because of the float UI library or if it's in here.

**Comment by rob-balfre** [comment]
Interesting. Will investigate, thanks

**Comment by rob-balfre** [comment]
Fixed in `5.0.0-beta.32`
