### ISSUE TITLE
hoverIndex = 0 or null on open

### ISSUE THREAD

**Issue by rogerfar** [rob-balfre/svelte-select#481]
We're porting from another select component to this svelte and I found 1 small difference.

For example this select (react-select as a random example):
![image](https://user-images.githubusercontent.com/1142915/196267573-30737c04-5a98-49dd-8a41-55c144d92d3f.png)

The `Orange` item is selected, when opening the list, only the `Orange` item is selected.

But when doing something similar in svelte-select:
![image](https://user-images.githubusercontent.com/1142915/196267901-96fd3424-4b1e-4816-8afa-c8fb84b9eaa0.png)

The first item is always in the hover / preselect state. This gets confusing if the hover state and the select state are the same background color.

It seems to be from this line:
https://github.com/rob-balfre/svelte-select/blob/feature/v5/src/lib/Select.svelte#L459

Would it be an idea to set the default hoverItemIndex to null/undefined instead of 0?

**Comment by rob-balfre** [comment]
Sounds like a reasonable suggestion to me. Thanks

**Comment by rob-balfre** [comment]
Added in `5.0.0-beta.34`

**Comment by rogerfar** [comment]
@rob-balfre This works, but not when adding groups:

![image](https://user-images.githubusercontent.com/1142915/196750050-92994c3a-111a-4c84-8f36-a821ac9b8467.png)

https://svelte.dev/repl/d41eb93a71874979b24a86467fe3ec92?version=3.52.0

**Comment by rob-balfre** [comment]
@rogerfar thanks, nice spot

**Comment by rogerfar** [comment]
Yes looks great, I did find another small bug when you have multiple selects on a page:

https://svelte.dev/repl/d41eb93a71874979b24a86467fe3ec92?version=3.52.0

You can kinda see it when opening the bottom select, it flashes, while the top one stays.

**Comment by rob-balfre** [comment]
@rogerfar how's 5.0.0-beta.38 looking?!

**Comment by rogerfar** [comment]
Perfect!
