### ISSUE TITLE
Help how to bind:value as a simple value and how to style select

### ISSUE THREAD

**Issue by kane81** [rob-balfre/svelte-select#483]
Hi 

I need help - I have a object array of items and I would like svelte-select to bind:value to bind the value selected and not the object selected.... I have a workaround, but it is extra boiler plate code and wondering if there is a better way?

Also I cannot seem to style svelte-select background color to say red on an error.

Please see example in repl
https://svelte.dev/repl/16a4db40caf24df6befff466dcceb9e8?version=3.52.0

Thank you

**Comment by kl3sk** [comment]
Hello,

May this [REPL](https://svelte.dev/repl/463119ab0cdd4d3c9978323420249294?version=3.52.0) help you

You have to `bind:value` and refer to it.

**Comment by kane81** [comment]
Thank you for your reply and REPL- 

re bind:value - yeah I had worked that out - was hoping there was a more elgant way that uses less boiler plate lol :P

thanks for the beta preview. FYI for example code - 
probably adjust samle from
`class={styleAsError ? "invalid" : ""}`
to 
`class:invalid={styleAsError}`
