### ISSUE TITLE
[V5] Create item: Keybord event

### ISSUE THREAD

**Issue by kl3sk** [rob-balfre/svelte-select#487]
Hello,

To continue [this thread](https://github.com/rob-balfre/svelte-select/issues/470#issuecomment-1288728247), I achieve how to [add item](https://svelte.dev/repl/4f447ad7d75543b285260c3a150ec277?version=3.52.0).

But select item with keyboard seems impossible.

ping @rob-balfre

**Comment by rob-balfre** [comment]
@kl3sk how's this work for you?

https://svelte.dev/repl/42006b39bce245d2be3b8a7e651dc959?version=3.52.0

**Comment by kl3sk** [comment]
Hello,

Thank you for this interesting example, but the feeling is not the same as it was on V4. As in this [REPL](https://svelte.dev/repl/c3562df0ecc742feb255c88aa5112f84?version=3.52.0)

**Comment by rob-balfre** [comment]
@kl3sk I'll add that REPL to the examples site. Thanks
