### ISSUE TITLE
[v5] Expand list to fit contents (wider than input)

### ISSUE THREAD

**Issue by madeleineostoja** [rob-balfre/svelte-select#488]
I have a bit of a niche use-case and I can't figure out how to address it with v5. The items in my list have extra content compared to the rendered selected item, and I want the list to be wider than the select's input. 

Ie, not clip this content:
<img width="178" alt="Screen Shot 2022-10-25 at 12 08 12 PM" src="https://user-images.githubusercontent.com/6374876/197646911-725a77b6-869f-47a2-8e31-975ce180737f.png">

I can't find the right combination of CSS vars or floating-ui config to achieve that, do you have any pointers? Is it even possible?

**Comment by rob-balfre** [comment]
@madeleineostoja how about this https://svelte.dev/repl/3e45fab6855e44b59e5fa58a06bf495c?version=3.52.0 ?

**Comment by madeleineostoja** [comment]
ah heck I totally missed that option, sorry! Yep works perfecly.
