### ISSUE TITLE
bind to justValue (using multiselect)

### ISSUE THREAD

**Issue by spassvogel** [rob-balfre/svelte-select#489]
following up on https://github.com/rob-balfre/svelte-select/issues/338, I cant seem to make it work with a multi-select.

https://svelte.dev/repl/237b01ecd77048589c14612cce15617b?version=3.52.0

As you can see, it initially reads: `Selected value for flight.city is null`, whereas I want it to say: `Selected value for flight.city is ADL,SYD`

**Comment by spassvogel** [comment]
Yes I understand that, but is that a technical limitation or a design choice? The ability to databind just to the value seems quite valuable to me. In fact, I believe that [this ticket]( https://github.com/rob-balfre/svelte-select/issues/338) also mentioned databinding. 

What is the use of having a read-only value? Quite often one has a value already serialized in some database or something to start off with.

**Comment by rob-balfre** [comment]
@spassvogel, design choice.  Feel free to PR and improve.
