### ISSUE TITLE
V3 - when using Selection component, scrollbar appears

### ISSUE THREAD

**Issue by dontwork** [rob-balfre/svelte-select#49]
Hi there. I am having to style my Selection component with height: 100% to prevent a scrollbar appearing... This could be bad on my end but my Selection just contained text and seemed to be 1px taller than its containin div

**Comment by rob-balfre** [comment]
hey @dontwork will be hard to debug without seeing your Selection component.

**Comment by dontwork** [comment]
```
<script>
  export let item
  export let getSelectionLabel
</script>

<style>
div {
  height: 100%;
}
small {
  color: #A9A9A9;
}
</style>

<div>
  {getSelectionLabel(item)}
  <small>
    {item.dimensions.join('mm x ')}mm
  </small>
</div>
```

**Comment by subpx** [comment]
@dontwork I've had a look at this and I would say you have some styles that are being inherited and causing this issue. Most probably the small tag.
