### ISSUE TITLE
Multiselect: Limit to number of selected items

### ISSUE THREAD

**Issue by EskelCz** [rob-balfre/svelte-select#490]
Is there a way to limit the number of selected items? Thanks.

**Comment by rob-balfre** [comment]
Not internally but there are a few ways to achieve the same result with
reactive statements. How do you want it to work? Lock more selections when
limit is reached?

**Comment by EskelCz** [comment]
@rob-balfre Exactly, disabling the ability to select more than the limit, until some are deselected again.
Maybe also triggering an event to allow for some explanation to the user. (alert, label, shaking animation, whatever)

In my case it's just a prevention of abuse, if someone were to select hundreds of items just to see what happens. Don't want to even test that scenario. :)

**Comment by rob-balfre** [comment]
V5?

**Comment by EskelCz** [comment]
Yep

**Comment by EskelCz** [comment]
I'd prefer an integrated feature, for the sake of clean code, but this does the trick for now. Thanks a lot
