### ISSUE TITLE
Show results with matching starting string on top

### ISSUE THREAD

**Issue by planemad** [rob-balfre/svelte-select#491]
**Expected**

When typing my search string, the top results would be those words that start with my typed string.

**Actual**

The top results are alphabetical, and i need to type more characters than expected to find my result.

Eg. Picking Tanzania from a country list requires typing `tanz`, but if it was ordered by matching starting string it would just need `t`

![screen5](https://user-images.githubusercontent.com/126868/199162857-cf7f73f3-6d36-495a-beaf-9308b0285d07.gif)

--

This is a very cool project ❤️ !

**Comment by rob-balfre** [comment]
You can use `loadOptions` a promise based method to return them sorted how you'd prefer. 

v5 example here...
https://svelte-select-examples.vercel.app/examples/props/loadOptions

**Comment by planemad** [comment]
Perfect, that would work!
Thanks @rob-balfre
