### ISSUE TITLE
Updating value externally should not fire change event

### ISSUE THREAD

**Issue by subpx** [rob-balfre/svelte-select#492]
Currently if you change the value of a svelte-select component externally a change event is fired.
As with a native select element, this is not the expected behaviour.

"The change event is fired for <select> elements when the user modifies the element's value.

Note: The input event is fired every time the value of the element changes. This is unlike the change event, which only fires when the value is committed, such as by pressing the enter key, selecting a value from a list of options, and the like."

**Comment by rob-balfre** [comment]
Hi Tom,

Hope you're well.

Had some people that wanted that behaviour so added `on:select`...

https://svelte.dev/repl/216604caa9b64dfb87b30e0823dc5bbb?version=3.52.0

**Comment by subpx** [comment]
Hi, thanks thats perfect I will use that. To keep it more inline with web standards i would change 'select' to 'update' and 'update' to 'input'. But that is up to you. Closing issue.

**Comment by rob-balfre** [comment]
@subpx breaking lots of stuff with v5 anyway so actually it's a good point.  Will update later today. thx

**Comment by rob-balfre** [comment]
Updated in `v5.0.0-beta.39`
