### ISSUE TITLE
Is 'value' property in the bound object mandatory?

### ISSUE THREAD

**Issue by PlkMarudny** [rob-balfre/svelte-select#493]
Hi, not  sure what is wrong with the following setup, but it does not seem to work, REPL [here](https://svelte.dev/repl/72fe591da0e24273a63f8f08c6a690cc?version=3.52.0)
```
<script>
    import Select from 'svelte-select@beta';

    let collection = [
        { display: 'One', id: 1 },
        { display: 'Two', id: 2 },
        { display: 'Three', id: 3 },
    ];
	
	let value;
	
	$: console.log(value);
</script>

<br />
<Select items={collection} id="id" label="display" bind:value/>
```

**Comment by rob-balfre** [comment]
@PlkMarudny you were just missing the `itemId` prop.

https://svelte.dev/repl/f1449e2a1e7b42058c1d6da5a521754c?version=3.52.0
