### ISSUE TITLE
Can't bind value, because it's not the value, but the whole item.

### ISSUE THREAD

**Issue by stemaDev** [rob-balfre/svelte-select#495]
I would like to know the point of having a "value", because when I use bind:value={something}, then "something" get's set to the item in the select, which contains the value, but it's not the value itself. I can't bind it, can't preselect anything, and having the value set to "something" and updating the "something" in the on:select would result in an endless loop.

**Comment by rob-balfre** [comment]
You can bind just fine, just need to read the docs and look at the examples.  Add a REPL example I can show you where you are going wrong. Thanks. Reopen if needed.
