### ISSUE TITLE
BUG: Delayed processing following on:select event.

### ISSUE THREAD

**Issue by cyaris** [rob-balfre/svelte-select#498]
I'm on version `5.0.0-beta.11`. I've been on this version for a long time and have not experienced this issue before. In between selections, there is a delay where the `Select` component is no longer clickable. Any idea why it might be happening?

https://user-images.githubusercontent.com/35279417/202302589-a5534d18-4873-45c0-aad7-47d46f3e7804.mov

**Comment by rob-balfre** [comment]
@cyaris still happening in v5?  Reopen is need be. Thanks

**Comment by cyaris** [comment]
Fixed. Thanks @rob-balfre.
