### ISSUE TITLE
V3 - cannot set ID on field

### ISSUE THREAD

**Issue by dontwork** [rob-balfre/svelte-select#50]
Since this can be an element within a form and form elements need IDs to have a relationship with labels it would be good to be able to pass an id prop to the component

**Comment by rob-balfre** [comment]
Added a new prop, inputAttributes, that should do the trick.

**Comment by robertocarroll** [comment]
The inputAttributes is great if you have one instance on the same layout. Is there an approach for two or more instances? i.e. pass inputAttributes to one select to give it an ID and then pass another to another select on the same layout and give it a different ID so they can have different labels?

**Comment by rob-balfre** [comment]
@robertocarroll can you make a REPL with an example please? Thaks

**Comment by robertocarroll** [comment]
Thanks for getting back to me. Sorry for troubling you! I've worked out how to do it now:
https://svelte.dev/repl/43a3d987f84647a0954093a01029901f?version=3.23.2
