### ISSUE TITLE
select with loadOptions : function don't fire when empty filterText

### ISSUE THREAD

**Issue by amandineLecuyer** [rob-balfre/svelte-select#501]
Version : beta
On a Select with display async options, when I type a letter then  remove, loadOptions function don't fire and the options visible are items get with previous call on loadOptions. 
When text is empty, loadOptions should fire with filterText=''.
On v4 it's work like that but not on v5.

**Comment by jwlarocque** [comment]
On 4.4.7 it also doesn't seem to fire with an empty input, it just clears the options without checking.  
I agree that especially if a custom loadOptions is passed in, it should be fired.  It would be nice if it could be called on focus as well - I'd like to show some unfiltered options even before text has been entered.

(This might be an option somewhere already, but I looked through the readme and didn't see it there.)

**Comment by rob-balfre** [comment]
Yeah I think `loadOptions` is a bit too prescriptive and inflexible, I'll have a think. Thanks
