### ISSUE TITLE
[Question/Feature Resuest]: tabbing out of a select?

### ISSUE THREAD

**Issue by davidroeca** [rob-balfre/svelte-select#502]
I've been trying out the beta: `v5.0.0-beta.40`, so it may be beta-specific.

Is there a simple way to configure this component to enable tabbing to the next input? E.g. would there be a way to configure the first dropdown [on this demo site](https://svelte-select-examples.vercel.app/examples/props/items), to enable tabbing into the next one?

I've found that I can tab from an input into a select, but not the other way around. Ideally I could `Tab` from an input before or `Shift+Tab` from an input after, and do the same from a Select to an input or another Select.

**Comment by rob-balfre** [comment]
This used to work, not sure what happened there. BUG!
