### ISSUE TITLE
V5: Initial Value not set if value of itemId is numeric 

### ISSUE THREAD

**Issue by yoh-extradat** [rob-balfre/svelte-select#503]
```html
<script>
const Items = [
    {value: 1, label: 'Chocolate'},
    {value: 2, label: 'Pizza'},
    {value: 3, label: 'Cake'},
    {value: 4, label: 'Chips'},
    {value: 5, label: 'Ice Cream'}
];
</script>
<Select items={Items} value={1}></Select>
```
**Result**
<img width="490" alt="Screenshot 2022-12-08 at 13 54 21" src="https://user-images.githubusercontent.com/41435569/206451748-266e6bac-a2c8-4deb-8881-0017f668e613.png">

**Comment by Maadtin** [comment]
Think your value should be value={{ value: 1, label: 'Chocolate'}}

**Comment by georgeemr** [comment]
I'm having this issue and cannot resolve it, just if the id is string. How can I resolve it using the Ids numeric.

My datasource is numeric, and with a normal select it just works:
https://svelte.dev/repl/f203e41b174441a1a217216ce01b0099?version=4.2.8
