### ISSUE TITLE
List offset/size does not update

### ISSUE THREAD

**Issue by gusi1994** [rob-balfre/svelte-select#511]
Hi @rob-balfre, I am not sure if I am missing something.
If the list opens on top of the select, the list does not update in size (height) if it gets filtered.

**Expected behavior:** In this REPL (scroll down to the select) the list opens on top and after searching for one item the list adjusts its size and sticks to the select: https://svelte.dev/repl/cb19720ae0874125aea95c6d7260abcb?version=3.52.0

**Unexpected behavior:** In this REPL (scroll down for the select with the title "Theming" or any other that should open the list on top) if you search for an element i.e. "one" the list keeps his original size and a gap between the found element appears: https://svelte.dev/repl/3df87e32340e4e9e85bf371becae2af0?version=3.55.0

![Screenshot](https://user-images.githubusercontent.com/15858721/209929694-b1a400be-43d3-467d-8997-425284e9c4b0.png)

Thanks in advance.

**Comment by rob-balfre** [comment]
See https://github.com/rob-balfre/svelte-select/issues/510#issuecomment-1366964937

**Comment by gusi1994** [comment]
Thank you, that solved the issue. I missed that one.
