### ISSUE TITLE
on:hoverItem isn't called when there is only one item

### ISSUE THREAD

**Issue by joepetrakovich** [rob-balfre/svelte-select#512]
I was expecting `hoverItem` to be called when I hover any item but it doesn't work if you only have one item.   I'm assuming because the hoverIndex defaults to the first item.   

Is there any way around that?  I'd like the event to fire whenever an item is hovered.

```
<script>
	let items = ['One'];
</script>

<Select {items} on:hoverItem={(e) => {console.log(e)}} />
```

**Comment by rob-balfre** [comment]
You can create your own hover event in the item named slot. That should
work

**Comment by joepetrakovich** [comment]
That'll work.  I assume you mean via mouseenter/mouseleave events on the slot?

**Comment by rob-balfre** [comment]
yeah and a focus event.

**Comment by joepetrakovich** [comment]
Got it!  Thanks for the idea, that'll work perfectly.
