### ISSUE TITLE
Single-select clear event should behave like multi-select clear event

### ISSUE THREAD

**Issue by libklein** [rob-balfre/svelte-select#513]
A clear event raised by a multi-select carries a reference to the cleared item in the `details` field:

https://github.com/rob-balfre/svelte-select/blob/master/src/lib/Select.svelte#L341

The `details` of clear events raised by single-selects is always `undefined`:

https://github.com/rob-balfre/svelte-select/blob/master/src/lib/Select.svelte#L468

I think we should align behavior in both cases. Imho, most people would expect a reference to the cleared item in the raised event and there are several usecases:

* Removing the select after it has been cleared
* Adding the removed item to some collection

**Comment by rob-balfre** [comment]
@libklein thanks very much.  Released in 5.1.0
