### ISSUE TITLE
Value prop only seems to work with label, not value

### ISSUE THREAD

**Issue by piewebnl** [rob-balfre/svelte-select#515]
The value prop doesn't seem to to take the value into account with complex items (value and label), but just uses the label.

Hope makes more sense here:
[Repl](https://svelte.dev/repl/ce00b584df21498a9eec6ac431ce44c0?version=3.55.0)

**Comment by rob-balfre** [comment]
Hi @piewebnl, `value` needs to be an object...

https://svelte.dev/repl/18becccc0d54467b8e3395622050d931?version=3.55.0
