### ISSUE TITLE
Is there an alternative for noOptionsMessage?

### ISSUE THREAD

**Issue by DjeboDigital** [rob-balfre/svelte-select#518]
I am working with svelte-select and i really like it! But I saw in the new release noOptionsMessage is removed.

Is there an alternative for it?

Edit:
Is this the replacement? https://svelte-select-examples.vercel.app/examples/slots/empty

**Comment by rob-balfre** [comment]
Yes. Named slots. See doc

**Comment by rob-balfre** [comment]
> Edit: Is this the replacement? https://svelte-select-examples.vercel.app/examples/slots/empty
 Yes
