### ISSUE TITLE
Visual bug: filtered elements stay above selector

### ISSUE THREAD

**Issue by aureleoules** [rob-balfre/svelte-select#520]
See video above.

[Screencast from 2023-01-13 15-38-19.webm](https://user-images.githubusercontent.com/22493292/212346068-218857bd-fa9f-4baf-8d42-504be8a34e93.webm)

**Comment by rob-balfre** [comment]
What version you on?

**Comment by aureleoules** [comment]
The latest, 5.1.1.

**Comment by rob-balfre** [comment]
Strange. Floating UI should auto align. Are you passing in any floating UI
configuration?

**Comment by rob-balfre** [comment]
Fixed in 5.1.2 

Thanks

**Comment by aureleoules** [comment]
Thanks a lot!
