### ISSUE TITLE
Prefix css custom properties

### ISSUE THREAD

**Issue by jorri11** [rob-balfre/svelte-select#522]
Hi

I think it would be a good idea to prefix the css variables with something project specific in order to not interfere with other codebases. Like bootstrap [has done.](https://getbootstrap.com/docs/5.2/customize/css-variables/#:~:text=in%20future%20updates.-,Prefix,via%20the%20%24prefix%20Sass%20variable.)

**Comment by rob-balfre** [comment]
Hi @jorri11  I'd suggest wrapping a component in a class, that saves having to add a prefix to every var

```
.foo {
  --clear-select-width: 20px
}
```

You can also `import Select from 'svelte-select/no-styles/Select.svelte` and then supply 100% your own CSS. 

Hope that helpful, thanks.

**Comment by jorri11** [comment]
That is really helpful! Thank you!
