### ISSUE TITLE
Error with keydown event. It throw undefined value

### ISSUE THREAD

**Issue by geminway92** [rob-balfre/svelte-select#523]
Using the select in a personal project, I found this issue relationed in the `on:keydown` event (I assume that). I post a video with the problem. Each time a press `Enter` key with any item selected, it throws an error trying to read the option defined for each item (in the example the param is `id`).

Here is the video.

https://user-images.githubusercontent.com/88619799/212737109-7c6fd89c-8298-4037-9999-6485731b0fe2.mov

Thanks.

**Comment by rob-balfre** [comment]
@geminway92 apologies I hadn't updated that example... `on:select` became `on:change` during beta.  Also found a juicy little hover index bug, fixing now. Thanks

**Comment by rob-balfre** [comment]
Fixed in 5.1.3
