### ISSUE TITLE
Sync component items with stores values

### ISSUE THREAD

**Issue by gschurck** [rob-balfre/svelte-select#524]
How to update the svelte-select items list with a store ?
Like I have an itemsStore, and if I add an item in the store list on a form on the same page, I want the select list to be instantly updated from the store.

**Comment by rob-balfre** [comment]
Same way you would with any svelte component...

https://svelte.dev/repl/86220649f2e64e9b870e03b34db9e29e?version=3.55.1

**Comment by gschurck** [comment]
Thanks for the example.
