### ISSUE TITLE
When showChevron on onclick behaviour appears buggy

### ISSUE THREAD

**Issue by nkostic** [rob-balfre/svelte-select#536]
This is minor thing.

When showChevron set to true, onClick (click on the chevron itself) the drop down behaves as expected: the list opens.
If we click again on the chevron itself now the list closes for a moment and than opens again.

Not sure if by design but I Expected behaviour to be more "consistent" with basic select element: onClick on the chevron toggles state open / close for dropdown.

**Comment by rob-balfre** [comment]
@nkostic got a REPL? I'm not seeing this on my end

Thanks

**Comment by rob-balfre** [comment]
Might have been fixed here a few days ago?  

https://github.com/rob-balfre/svelte-select/pull/535

**Comment by nkostic** [comment]
Thank you, will check asap.

**Comment by rpadmanabhan** [comment]
Hi, I find the same issue as OP, could there have been a regression ?
https://svelte.dev/repl/0a474836e4da42cfa33616d08e8ebac9?version=4.2.19
