### ISSUE TITLE
Better solution for 'CreateItem'

### ISSUE THREAD

**Issue by MCMattia** [rob-balfre/svelte-select#538]
I was a fan of this library before v5. Now I find that allowing the creation of a new item has become less intuitive and more difficult.

Also adding a prop to the items array as shown [here](https://svelte-select-examples.vercel.app/examples/advanced/create-item) will not work with typescript.

Why not use the same method of v4 where setting `isCreatable` to true was enough?

**Comment by rob-balfre** [comment]
@MCMattia  No one cares whether you're a fan or not... please by more constructive in future when communicating with OS projects. 

v5 main goals were to clean up, reduce file size and add named slots.  `isCreatable` and virtual list were the main casualties of those changes. Only a small number to users need these features and they can now be achieved using slots and some filter adjustments. 

What about the example doesn't work in TS?

**Comment by MCMattia** [comment]
wow I did't mean to offend you
