### ISSUE TITLE
Access to multiselect value from the HTML input

### ISSUE THREAD

**Issue by EskelCz** [rob-balfre/svelte-select#540]
Please would it be possible to expose the current list of selected values of a multiselect, from the HTML element? With a single select it works fine.

## Reproduction:
1. On the example page https://svelte-select-examples.vercel.app/examples/props/multiple
2. Select multiple values
3. Run `document.getElementsByTagName('input')[0].value` in console.
4. It returns an empty string. :(

I could really use a string of comma separated values, for automated Cypress testing.
Thanks for your consideration.

**Comment by rob-balfre** [comment]
@EskelCz this should do the trick hopefully?

`document.querySelector('.svelte-select input[type=hidden]').value`

<img width="1153" alt="Screenshot 2023-02-05 at 12 14 08 pm" src="https://user-images.githubusercontent.com/2623102/216796546-a766110a-2160-49a9-865a-0b9e5ef39485.png">

**Comment by EskelCz** [comment]
@rob-balfre That would be just perfect :)

**Comment by EskelCz** [comment]
@rob-balfre But I must say it would be nicer to have the behavior unified, for the sake of consistency and simplicity of use. The ID set of svelte-select is passed down onto the visible input, which makes it for an natural direct selector.

**Comment by rob-balfre** [comment]
@EskelCz it is. The input you were targeting is the filter input. It loses its value after selection

<img width="1396" alt="Screenshot 2023-02-05 at 12 54 02 pm" src="https://user-images.githubusercontent.com/2623102/216797583-57961d3d-3004-4576-ab67-f1ff910f44bc.png">
