### ISSUE TITLE
Click event doesn't get released

### ISSUE THREAD

**Issue by MCMattia** [rob-balfre/svelte-select#545]
There seems to be an issue with the click event.

While using the Svelte-select inside a drag element, when selecting an option, the drag element is activated.

Please see the following repl:
https://svelte.dev/repl/8fbebe93180a404897199fab26619395?version=3.55.1

The draggable div should move only when clicked. Instead after selecting an option, the div behaves as if we were holding the mouse down on the draggable div.

A unoptimal fix is to use the focused select variable to disable the draggable action of the div.

**Comment by rob-balfre** [comment]
here ya go...

https://svelte.dev/repl/f7e18691bb6a4d68aca79539404618d5?version=3.55.1


Also I've not heard of that dragging lib... looks nice! @MCMattia thanks
