### ISSUE TITLE
Overflow issue: select list in its full height

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#547]
Given the example below is there a way to avoid the overflow issue?

I would like to see the select list above the modal in its full height.

REPL: https://svelte.dev/repl/f5581a06d05d44258b1ae90af299df41?version=3.55.1:

![image](https://user-images.githubusercontent.com/41120635/217884471-cce059de-5b84-4ecf-92c2-e5c6b0606b58.png)

As you can see I need the `overflow-auto` but I also need to see the list in its full height above the modal, above all.

![image](https://user-images.githubusercontent.com/41120635/217867012-9283ac62-c9d5-437d-9b2c-983d9ea01b53.png)

**Comment by frederikhors** [comment]
I'm creating another example here: https://svelte.dev/repl/f5581a06d05d44258b1ae90af299df41?version=3.55.1

**Comment by frederikhors** [comment]
I'm creating another example here: https://svelte.dev/repl/f5581a06d05d44258b1ae90af299df41?version=3.55.1

**Comment by rob-balfre** [comment]
```
floatingConfig={{ strategy: 'fixed' }}
```

Add the above as a prop... 

The horizontal scrollbar will align to the input 'please select' on focus/click which is annoying but not currently unavoidable.

**Comment by frederikhors** [comment]
Thanks.
