### ISSUE TITLE
Enter keypress within a form clearing the select rather than submitting

### ISSUE THREAD

**Issue by christoomey** [rob-balfre/svelte-select#549]
Hello, first and foremost, thanks for the great project.

Unfortunately we're hitting what I believe to be a bug when using svelte-select in a `<form>` where hitting enter in _any_ input will cause the svelte select clear logic to fire, rather than the expected result of submitting the form.

[Reduced test case repl](https://svelte.dev/repl/3c94b066a91b46eda72b52cc66f2cfd8?version=3.55.1)

**Comment by rob-balfre** [comment]
Fixed in `5.3.0`

**Comment by christoomey** [comment]
Thanks for the fix!
