### ISSUE TITLE
Multi items checkboxes Example does not update checkbox when selecting items with keyboard

### ISSUE THREAD

**Issue by gschurck** [rob-balfre/svelte-select#551]
Component : [Multi items checkbox](https://svelte-select-examples.vercel.app/examples/advanced/multi-item-checkboxes)

Search for an item and press `Enter`, the item is added to the list but the checkbox is not updated :

![Screenshot_20230212_153144](https://user-images.githubusercontent.com/21091232/218317187-d79ce2f5-63e4-4cd6-a7ee-3cf1d69b9dc1.png)

**Comment by rob-balfre** [comment]
Got a beta running with some refactors on this one...
https://svelte-select-git-develop-robertbalfre.vercel.app/examples/advanced/multi-item-checkboxes

looking any better?

`5.3.0-beta.7`

**Comment by gschurck** [comment]
Yes it's working for me !

**Comment by rob-balfre** [comment]
Released 5.3.0
