### ISSUE TITLE
Grab the text inside the input

### ISSUE THREAD

**Issue by Lucasmiguelmac** [rob-balfre/svelte-select#552]
Is there a way of accessing the actual text of the input?

For example:

```
<script lang="ts">
  import Select from "svelte-select";

  function handleChangeText(e: CustomEvent) {
    console.log(e.detail);
  }
</script>

<Select on:changeText={handleChangeText} />

```

Some context: I'm trying to achieve this using multiple={true}, so basically we would need to handle this as I'm typing on the input box

**Comment by rob-balfre** [comment]
By actual text do you mean 'filterText' or the text of the selected item?

**Comment by Lucasmiguelmac** [comment]
That's it. That's what I was looking for. I'll close the issue.
