### ISSUE TITLE
In "multiple" mode, seems like event propagation is bugging out. Clicking on X to remove a tag opens the list

### ISSUE THREAD

**Issue by 0radek** [rob-balfre/svelte-select#554]
First off, thanks for this awesome library. I'm working on a MVP and this has saved me a few days of work.

I have a minor issue, and I tried messing around in the code a bit and added some stopPropagations, but was unable to resolve the issue locally. Maybe you know a simple way to fix it but whenever this click occurs https://github.com/rob-balfre/svelte-select/blob/master/src/lib/Select.svelte#L761 the dropdown list opens.

My opinion is that the dropdown list should appear when the parent container is clicked. If the tag or its X is clicked, it should not open the dropdown list. Or, maybe there could be some precedence option to toggle based on needs?

The reason I bring this up is that when you click the X and the list opens, clicking another X on another tag closes the list. Then clicking the X on another tag opens. So, it is kind of jarring so maybe the former behavior I posted above is preferable? 

This behavior with the dropdown list appearing when clicking the X can be seen here: https://svelte-select-examples.vercel.app/examples/advanced/create-item-multiple

Add a couple items, and click the X.

Thoughts?

**Comment by rob-balfre** [comment]
@0radek looks like if you remove the final item of selected items its ok but if you remove anything else it opens. That's a bug in my opinion. 

I'm actually working on a new prop to give more granular control of listOpen, not quite figured out the best approach but  I'll include a bug fix for this either way. 

Thanks for reporting.

**Comment by 0radek** [comment]
thanks @rob-balfre !

**Comment by rob-balfre** [comment]
@0radek fixed the bug... https://svelte-select-git-develop-robertbalfre.vercel.app/examples/advanced/create-item-multiple
Also added a new prop `closeListOnChange`

v `5.3.0-beta.7`

How's that looking?

**Comment by 0radek** [comment]
@rob-balfre that's amazing, thanks so much! works great

**Comment by rob-balfre** [comment]
Released `5.3.0`
