### ISSUE TITLE
multiple together with label does not work

### ISSUE THREAD

**Issue by jorri11** [rob-balfre/svelte-select#556]
I am trying to use the `Select` together with the `label` property and multiple. The problem is when i choose just one item i am no longer able to choose any more. Reproducible example below: 

```
<script>
		window.process = {env: {}} // REPL issue, ignore
    import Select from 'svelte-select';

    let items = [
        { someProp: 123, name: 'One' },
        { someProp: 345, name: 'Two' },
        { someProp: 567, name: 'Three' },
    ];
	let value
</script>

<Select bind:value {items} multiple label="name" />
```
Result after choosing one item: 

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/42845131/219039340-09e6675b-c996-4656-9d2a-a6376ce8bea3.png">

**Comment by rob-balfre** [comment]
Need to pass in itemId if you're using a collection without a value
property

**Comment by jorri11** [comment]
Thank you
