### ISSUE TITLE
Accessibilty doesn't work properly

### ISSUE THREAD

**Issue by easteryard** [rob-balfre/svelte-select#560]
Using the arrow keys to focus list items in the drop down doesn't make the drop down view follow along with the focused list item.

If the focused list item is outside of the drop down view and you scroll down to it and then start using the arrow keys again the drop down view will reset to the top of the list.

https://user-images.githubusercontent.com/19154371/220345699-de229e8d-54e9-4de5-abaf-ec27e012b61a.mp4

**Comment by rob-balfre** [comment]
@easteryard got a REPL example?

A basic setup works ok...
https://svelte.dev/repl/b0841bd9a09b4d8288eb889256bb8842?version=3.55.1
