### ISSUE TITLE
How to scroll through selected items in multiple select

### ISSUE THREAD

**Issue by Edward-Ta** [rob-balfre/svelte-select#561]
In v4 I implemented my own code inside Select.svelte to make overflow: scroll once my multi select box got to a certain height.
The issue that I solved with this can be seen here [#388](https://github.com/rob-balfre/svelte-select/issues/388)

In v5 the items have been put inside 
```html
<div class="svelte-select"> 
  <div class="value-container"> 
    item 1...
  </div>
</div>
```
I cannot scroll with the outer svelte div like I used to:
```html
<div class="svelte-select" style="overflow: scroll"> 
  item 1...
</div>
```
Because it's now inside another div inside the svelte-select container, and my possible implementation looks ugly:

v4
![image](https://user-images.githubusercontent.com/78352116/222170049-2db51375-35dd-42a1-a1ca-44f76b005e30.png)

v5
![image](https://user-images.githubusercontent.com/78352116/222169212-46ee11a1-29e4-41fd-889c-d51de33cdb53.png)

Are you able to advise on how to make my scrollable implementation for a max height multi select work?

'Dodgy' select code I wrote before in [issue 338](https://github.com/rob-balfre/svelte-select/issues/388)
```javascript
$: value, setTimeout(selectAllCssChanges, 100);
function selectAllCssChanges(){
  let select = document.querySelector(`#${id} .svelte-select`)
  if(select && maxHeightBeforeScroll){
    if(value && select.scrollHeight > maxHeightBeforeScroll){
      select.style.maxHeight = `${maxHeightBeforeScroll}px`
      select.style.overflow = "scroll"
    } else{
      select.style.overflow = "visible"
      select.style.maxHeight = undefined
    }
  }
}
```

**Comment by rob-balfre** [comment]
@Edward-Heales added some extra css props for you in `5.4.0`, any better?

```svelte
<Select {items} {value} multiple 
    --height="40px" 
    --max-height="40px"
    --value-container-overflow="scroll"
    --value-container-padding="3px 40px 3px 0"
    --indicators-position="absolute"
    --indicators-top="0"
    --indicators-right="0"
    --indicators-bottom="0"    
/>
```

**Comment by Edward-Heales** [comment]
This seems to be working well, indicators-right needs to come in a bit because the scroll takes up some space so I set it to 4%.
```
--indicators-right="4%"
```
One thing, do you think it's possible to set --value-container-overflow to "hidden" before --max-height is reached and then change it to "scroll", after max-height is reached?
Or shall I create that for myself because it might not be a requirement for anyone else.

**Comment by Edward-Heales** [comment]
Genius
