### ISSUE TITLE
Add `list-prepend` and `list-append` slots

### ISSUE THREAD

**Issue by sawyerclick** [rob-balfre/svelte-select#564]
Add slots for content at the top and bottom of the list. I propose `list-prepend` and `list-append` for adding content at the top and bottom of the opened list. To do this currently you need to access the `list` slot which overwrites all select logic and makes the developer rewrite (see the on:click event in the [demo](https://svelte-select-examples.vercel.app/examples/slots/list) vs. the robust classings & events in the source cdoe). This proposal would preserve item logic without having to duplicate all the magic in the source. 

Willing to write this myself, as I think the inclusion of the two empty slots would be enough.

**Comment by rob-balfre** [comment]
@sawyerclick released in `5.5.0`

thanks

**Comment by rob-balfre** [comment]
`5.5.1` ... messed up release!
