### ISSUE TITLE
list-append & list-prepend not yet working in 5.5.0

### ISSUE THREAD

**Issue by Oggymot** [rob-balfre/svelte-select#569]
Version changed `"version": "5.5.0",`, but still not working and in console 😥:
![image](https://user-images.githubusercontent.com/17729992/223563449-25b431cd-9bc9-4268-bbac-924f57fc619c.png)

**Comment by rob-balfre** [comment]
That's so annoying. My release script got messed up it probably never
actually released the stupid thing. I'll double check

**Comment by rob-balfre** [comment]
`5.5.1` fixed.... thanks for reporting
