### ISSUE TITLE
on:blur event not always firing.

### ISSUE THREAD

**Issue by cyaris** [rob-balfre/svelte-select#570]
On newest version, `5.5.1`.

**Comment by rob-balfre** [comment]
@cyaris seems ok to me. Got an example?  Thanks

**Comment by cyaris** [comment]
i'll try to replicate.

**Comment by cyaris** [comment]
Here's a [repl](https://svelte.dev/repl/12bc6bfa15f4489ea3bcb9d7bdcb1f44?version=3.55.1) @rob-balfre. Select an item, then click the container to open the list, then click outside the list. The list will still be focused and won't close.

**Comment by cyaris** [comment]
@rob-balfre apologies for all the unused props in the repl.

**Comment by cyaris** [comment]
The blur event stops working once an item is selected.

**Comment by cyaris** [comment]
@rob-balfre just simplified the repl.

**Comment by rob-balfre** [comment]
@cyaris I can't debug that its way too complex.

**Comment by cyaris** [comment]
Hey @rob-balfre , just stripped it down significantly. Would you mind taking a look again? Thanks.

**Comment by cyaris** [comment]
This example in the docs is demonstrating the same bug: https://svelte-select-examples.vercel.app/examples/slots/list

**Comment by rob-balfre** [comment]
Tweaked the `on:blur` code and released `5.5.2`.  Let me know if that's helped.

**Comment by cyaris** [comment]
It did. thanks @rob-balfre .
