### ISSUE TITLE
Wrong event type when unchecking in list

### ISSUE THREAD

**Issue by mabar** [rob-balfre/svelte-select#575]
Hello,

I am using your example with item check boxes https://svelte-select-examples.vercel.app/examples/advanced/multi-item-checkboxes
It works greats, except when I uncheck an item, event type is `'select'`, not `'clear'`

I have some extra code that depends on difference between select and clear and I wondered if it could be fixed in the lib. If not it is fine, workaround simple condition `!Array.isArray(e.detail) && isChecked[e.detail.value]`

Thank you

**Comment by rob-balfre** [comment]
It's not really a `clear` event that needs to fire, I'd suggest a `on:change` event on the input checkboxes.
