### ISSUE TITLE
When using the required props, the keyboard focus is going to the select

### ISSUE THREAD

**Issue by Ennoriel** [rob-balfre/svelte-select#578]
Hi

When using the `required` props, a select is added to the DOM in order to have the html native validation which is nice! However the select is focusable and should probable not.

Here is a [REPL showing it](https://svelte.dev/repl/80f6a8c4a0c4479780c194e64004d559?version=3.58.0).

I don't know if it's as simple as adding a `tabindex="0"` or if it should also have `aria-hidden`

**Comment by rob-balfre** [comment]
Thanks for finding that!  Fixed `5.5.3`
