### ISSUE TITLE
How to have custom label per item

### ISSUE THREAD

**Issue by EddTally** [rob-balfre/svelte-select#586]
Pre v5 we had these options, getOptionLabel & getSelectionLabel.
This allowed us to edit how the label was displayed, like so:
```Javascript
getOptionLabel={(option) => `Item Id: ${option.itemId}, Item Name: ${option.itemName}`}
getSelectionLabel={(option) => `Selected Id: ${option.itemId}, Selected Name: ${option.itemName}`}
```
I read the docs but cannot find a replacement for this functionality.
Could I get some help please.

**Comment by rob-balfre** [comment]
Named slots.

**Comment by EddTally** [comment]
> Named slots.

So I would do something like 
```Svelte
 <div slot="item" let:item let:index > Item Id: {item.itemId}, Item Name: {item.itemName} </div>
```
These are new to me, just learned from here https://svelte.dev/tutorial/slot-props 

Thanks
