### ISSUE TITLE
Why does svelte-select not understand that it needs to truncate itself based on parent width?

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#590]
I would like to understand how to make svelte-select to "auto-regulate" it's width based on parent width.

Example: https://svelte.dev/repl/e69f84a4208a4a5887e2f56e8c16bb89?version=3.58.0

![image](https://user-images.githubusercontent.com/41120635/232313656-4f62c90c-0cba-4582-a89e-499c0d150e1f.png)

When I reduce the REPL window width do you see the horizontal scrollbar at the bottom?

I would like `svelte-select` auto understand it needs to use the ellipsis / truncate behavior, like this:

![image](https://user-images.githubusercontent.com/41120635/232313806-91845b45-2529-4cf5-8c0e-32a721f2df65.png)

I can fix it by using on the parent the code:

```html
<div class="col-span-1 overflow-x-hidden">
  <CustomSelect />
</div>
```

but I need something inside the `CustomSelect.svelte` component and not in the parent one. This because the `CustomSelect` is used **a lot** and in **a lot** of places.

Any idea?

**Comment by rob-balfre** [comment]
It works fine without tailwind I think?

**Comment by frederikhors** [comment]
Nope, tailwind is just what I'm using, you can try it even without Tailwind. The issue is the ellipsis is not present if the parent width is smaller.

**Comment by rob-balfre** [comment]
See here: https://svelte.dev/repl/a343790c42254d698c885aecc0e90925?version=3.58.0

Otherwise show me what you mean in your own simple REPL.

**Comment by frederikhors** [comment]
Ok, I reduced the example in REPL removing Tailwind and what is not needed.

Plus the gif:

![iss](https://user-images.githubusercontent.com/41120635/232559241-b42a5d8e-1609-4146-81c7-705d10922c74.gif)

Do you see now what I mean?

**Comment by rob-balfre** [comment]
Nothing to do with svelte-select, just CSS...
https://svelte.dev/repl/2e34e9b2088d4a7e8b51e4f07058e062?version=3.58.0
