### ISSUE TITLE
Ability to set a limit on multi selects

### ISSUE THREAD

**Issue by fabushawish** [rob-balfre/svelte-select#594]
Hi there, 
I am wondering if it is possible to have the ability to set a limit on how many options can be selected when **_multiple_** is set to true. 

> Use case:
> Allowing users to self tag their own profile by selecting from a multi-select with a limit of up to 3 options per dropdown.

**Comment by rob-balfre** [comment]
https://svelte-select-examples.vercel.app/examples/advanced/limit-multi-value
