### ISSUE TITLE
Edit empty/no matches text

### ISSUE THREAD

**Issue by henryjameslau** [rob-balfre/svelte-select#595]
Hi,
I'd like to be edit the text shown when there are no match to the string entered.
Thanks

**Comment by rob-balfre** [comment]
@henryjameslau use the 'empty' slot...
https://svelte.dev/repl/434fd3ba20414bf0a37a0c800122c8ed?version=3.58.0

**Comment by henryjameslau** [comment]
Ah sorry I didn't know that was the slot I needed, thank you!
