### ISSUE TITLE
how to make items larger than main select box

### ISSUE THREAD

**Issue by kewp** [rob-balfre/svelte-select#599]
I have a list of items where each item title is very long. How do I make the main select box a fixed with and have the drop-down list width expand to a bigger width?

**Comment by kewp** [comment]
I've managed to do it with this:

```svelte
<style>
    :global(.svelte-select-list) {
        width: 800px !important; 
    }
</style>
```

**Comment by ricochenft** [comment]
I have to add `div` before `.svelte-select-list` in order for the style to be picked up.
> ```svelte
> <style>
>     :global(div.svelte-select-list) {
>         width: 800px !important; 
>     }
> </style>
> ```
