### ISSUE TITLE
V3 - Removing item not working in multiselect

### ISSUE THREAD

**Issue by PaulMaly** [rob-balfre/svelte-select#60]
When we use multiselect and try to remove single selected value it's not working. If to click remove button the same times how many of selected items we have, it'll remove all of them.

**Comment by rob-balfre** [comment]
I can't seem reproduce this.  What does your items array look like?

**Comment by PaulMaly** [comment]
Version 3? A simple array of objects like:

```javascript
 let items = [
    { id: 1, name: "Foo", group: "first" },
    { id: 2, name: "Bar", group: "second" },
    { id: 3, name: "Baz", group: "second" },
    { id: 4, name: "Qux", group: "first" }
  ];
```

Usage:

```html
<Select 
        {Item} 
        {isMulti} 
        {items} 
        bind:selectedValue={selected} 
        optionIdentifier="id" 
        groupBy={groupBy} 
        getSelectionLabel={getLabel} 
        getOptionLabel={getLabel} 
        placeholder="Select..." 
        menuPlacement="bottom" 
        on:select 
        on:clear
/>
```

**Comment by rob-balfre** [comment]
@PaulMaly I still couldn't fully reproduce but I did find a bug with groupBy and isMulti.  Hopefully that solved your issue?

**Comment by rob-balfre** [comment]
Hang on, do you mean the 'clear all' button on the right?
