### ISSUE TITLE
Continue filtering after selection

### ISSUE THREAD

**Issue by tomasz13nocon** [rob-balfre/svelte-select#603]
I'd like to have the selected item as the input value, to be able to continue typing.

User selects "twenty" -> user types " two" -> value becomes "twenty two"

Is this possible?

**Comment by rob-balfre** [comment]
@tomasz13nocon hmm not seen that kind of behaviour in a select before. Got an example? Thanks

**Comment by rob-balfre** [comment]
@tomasz13nocon something like this?
https://svelte-select-examples.vercel.app/examples/advanced/create-item-multiple

**Comment by tomasz13nocon** [comment]
Yes, that would work for tags.
Another use case was a form with autocomplete for previously used names.
