### ISSUE TITLE
Does v5 no longer support optionIdentifier?

### ISSUE THREAD

**Issue by nelldkLee** [rob-balfre/svelte-select#609]
Hi, I'm using the select library well. When I tried to use the searchable option, it didn't work in v4, so when I uploaded it to v5, the ones I had optionIdentifier and labelIdentifier came out as undefined
Does v5 no longer support optionIdentifier and labelIdentifier?

**Comment by rob-balfre** [comment]
Yeah it does.

Changed to itemId and label

**Comment by nelldkLee** [comment]
Your quick reply was very helpful. Thank you!
