### ISSUE TITLE
How to select an item via playwright testing?

### ISSUE THREAD

**Issue by josephceth** [rob-balfre/svelte-select#621]
Pretty straight forward issue, I am struggling with setting the value of a svelte-select component for our playwright testing, whether through writing my own code or using the recording, the results are inconsistent.

We've tried:
```
await page.locator('label').filter({ hasText: 'Default Value' }).getByRole('textbox').click()
await page.getByText('Value to Select, { exact: true }).click() 
```
...in an attempt to open the control and select an item, but again, it doesn't work all the time.

Any help would be appreciated...thanks!

**Comment by rob-balfre** [comment]
@josephceth sure, I've tackled it like this in the past:

```js
await page.locator('input[id=<ID OF SELECT>]').fill('<FILTER TEXT>');
await page.click('.svelte-select-list .list-item >> nth=0'); // or something similar to match your need
```

**Comment by rob-balfre** [comment]
Or

```js
await page.locator('input[id=<ID OF SELECT>]').click();
await page.click('.svelte-select-list .list-item >> nth=1'); // or something similar to match your need
```

**Comment by josephceth** [comment]
Welp...I feel dumb, the svelte-select was a piece of a much large component and the id wasn't being applied to the select it was applied to the hidden input containing the value.  

As if by magic, once an Id was provided to the actual <Select> component, it works.

Thanks!
