### ISSUE TITLE
Custom Style for Multi-Item

### ISSUE THREAD

**Issue by JVariance** [rob-balfre/svelte-select#623]
Hi, I'd like to prepend a selected multi-item with an icon.
As ist seems I currently only can style the list items.

**Comment by rob-balfre** [comment]
https://svelte-select-examples.vercel.app/examples/slots/selection

**Comment by JVariance** [comment]
> https://svelte-select-examples.vercel.app/examples/slots/selection

Oh, how could I miss this. Thanks 😃
