### ISSUE TITLE
Changing focus border styling to be on the outside

### ISSUE THREAD

**Issue by AndreasPB** [rob-balfre/svelte-select#625]
Hi, Rob (and possibly others), 

I love the library

Sorry for this "non-issue"-issue, but I didn't  know where else to ask this

I'm having trouble getting the svelte-select's focus border on the outside like the rest of my styling. If I'm not wrong the default border position is on the outside, but I cannot figure out what svelte-select does to change that

Added a video to show the difference - The svelte-select is the "Søg efter person" where you can see the inner text jump when focused:

https://github.com/rob-balfre/svelte-select/assets/43907402/068a0038-143d-4ec4-9815-cf7767c6d1b4

Any help is very much appreciated

**Comment by rob-balfre** [comment]
Try box-shadow?

```css
:global(.svelte-select.focused) {
   box-shadow: 0px 0px 0px 5px pink;
}
```

**Comment by AndreasPB** [comment]
That did the trick, thank you :)
