### ISSUE TITLE
Empty State ('No Options') cannot be translated

### ISSUE THREAD

**Issue by steppenwolfXYZ** [rob-balfre/svelte-select#627]
When the select has no options and the hideEmptyState option is set to false, the text 'No Options' is shown. This text is hard coded and cannot be translated.

Would be very nice to have this text as parameter so the plugin works for other languages than english.

My workaround so far: Find the element in an interval and replace text if it is there. Any better suggestions?

**Comment by rob-balfre** [comment]
Yeah. Use the slot....

https://svelte-select-examples.vercel.app/examples/slots/empty

**Comment by steppenwolfXYZ** [comment]
Perfect, thanks a lot, solved my problem.

**Comment by steppenwolfXYZ** [comment]
Perfect, thanks a lot, solved my problem.
