### ISSUE TITLE
justValue binding does not reflect state when Select is or returns from disabled

### ISSUE THREAD

**Issue by cbetti** [rob-balfre/svelte-select#653]
After selecting an item, if the Select becomes disabled by a subsequent action, then something external sets the bound value to null or undefined while disabled, the prior Select selection remains. If enabled, the selection still remains, which does not correspond with the binding state.

I would expect the Select state to reflect the binding state both while disabled and when re-enabled, but at the very least when re-enabled.

```
<Select items={members} itemId="id" label="name"
        bind:justValue={$selectedId.value}
        on:clear={clearMemberSelection}
        disabled="{newMemberCheckboxState || nonMemberCheckboxState}" />

<p>{$selectedId.value}</p>
```

(in this case "selectedId" is a svelte-forms field, hence the $selectedId.value binding)

I did not test bind:value.

**Comment by cbetti** [comment]
Any hints for a workaround? I didn't see a way to explicitly clear the Select.

**Comment by rob-balfre** [comment]
It might be because you can't set justValue, it's a read-only prop.  If you
make a REPL I can show you an alternative.

**Comment by cbetti** [comment]
Thank you, I think you're right and it's unrelated to disabled:

https://svelte.dev/repl/3ae71e0bfa23453da1b65f8b53ed0b8d?version=4.2.8

**Comment by rob-balfre** [comment]
not familiar with the svelte-forms but hopefully enough in this example to
unblock you...

https://svelte.dev/repl/21f1951476af401198324252007f6f60?version=4.2.8

**Comment by cbetti** [comment]
Really appreciate your help, I can definitely make it work using both bindings. Great component Rob!
