### ISSUE TITLE
Upgrading today from `"@sveltejs/kit": "1.30.0"` to `"@sveltejs/kit": "2.0.0"` I'm getting a warning

### ISSUE THREAD

**Issue by frederikhors** [rob-balfre/svelte-select#656]
Upgrading today from `"@sveltejs/kit": "1.30.0"` to `"@sveltejs/kit": "2.0.0"` I'm getting this warning:

```
WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-select@5.8.1
svelte-floating-ui@1.2.8

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

Can we please fix this?

**Comment by frederikhors** [comment]
I opened https://github.com/fedorovvvv/svelte-floating-ui/issues/11.

**Comment by fedorovvvv** [comment]
Yop!
I answered here: [comment](https://github.com/fedorovvvv/svelte-floating-ui/issues/11#issuecomment-1858631057)

**Comment by Cluster2a** [comment]
@frederikhors, how is it going? We still have this message and we would like to get rid of it.

**Comment by frederikhors** [comment]
Yeah. I think you should ask to @rob-balfre...

**Comment by rob-balfre** [comment]
v5.8.2

**Comment by Cluster2a** [comment]
> v5.8.2

![image](https://github.com/rob-balfre/svelte-select/assets/84905165/31209baf-6d28-41d3-a18c-5314515f9592)

The issue still exists.

**Comment by mcmxcdev** [comment]
Looks like there is already an open PR that fixed this, see: https://github.com/rob-balfre/svelte-select/pull/651

**Comment by rob-balfre** [comment]
v5.8.3

**Comment by Cluster2a** [comment]
> v5.8.3

@rob-balfre, message is gone - thanks a lot!
