### ISSUE TITLE
compiler 3.6.6 not working at all

### ISSUE THREAD

**Issue by northkode** [rob-balfre/svelte-select#66]
cant seem to get this to work at all
![image](https://user-images.githubusercontent.com/6988083/61012870-828b2380-a33d-11e9-8fcc-bc42357e6018.png)

when i select an item the svg is tiny (i had to fix that) colors are all white(until i fixed) and the actual selected item doesnt show up in the input. it just clears the input field.

**Comment by rob-balfre** [comment]
@northkode Can I see some example code please? Not sure how to help otherwise.

**Comment by northkode** [comment]
@rob-balfre i'm not sure how to share my experience

Your example works in the REPL.

But i do a basic import of your plugin into my code and nothing works. The styles done work probably related to your :root issue. But i see in the chat you resolved with :global(body), which at the end of the day I can get around the style issue for now. 

But for some reason when I select an item.. the input just goes blank, even tho the component says an item is selected. 

I'm on svelte compiler 3.6.7

**Comment by rob-balfre** [comment]
@northkode try to replicate your issue with svelte-select here please... 

https://svelte.dev/repl/9dbdebb5d2a24fc599ad2064179167b0?version=3.6.6
