### ISSUE TITLE
How can I bind:value while the value key is not named 'value'

### ISSUE THREAD

**Issue by kodaicoder** [rob-balfre/svelte-select#664]
I have  a collection like
```javascript
const colllection = 
[
     { id:1,  name:"John Doe"},
     { id:2 , name:"Jane Doe"},
     { id:3 , name:"Richard Roe"},
     { id:4 , name:"Rachel Roe"}
]
```
then in `data` from sever-side I has passing a object name `initialUserId` 
and using in  svelte file like this
 ```html
<script>
	import Select from 'svelte-select';
	
	/** @type {import('./$types').PageData} */
	export let data;

     const colllection = 
     [
          { id:1,  name:"John Doe"},
          { id:2 , name:"Jane Doe"},
          { id:3 , name:"Richard Roe"},
          { id:4 , name:"Rachel Roe"}
     ]
</script>
<Select
	placeholder="Choose user"								
	itemId="id"
	label="name"
	items={colllection }
bind:value={data.initialUserId}
/>

 ```
but this will giving me a `undefined` in svelte-select box
any suggestion on this issue or I using `bind:value` incorrectly

here is a [demo](https://www.sveltelab.dev/l0epk9iz3jram6m)

**Comment by jlaflash95** [comment]
IMO it's broken but perhaps I don't fully understand how it works either.

For now, I was able to extract the value of the select by removing the bind:value attribute and creating an on:change handler and accessing the detail property of the event. By removing the data binding it allows your placeholder to display.

[Demo](https://www.sveltelab.dev/?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte#code=N4IgdA5glgLlEDsD2AnApiAXKAZlANhtiAMZIIxoUDOWoA1lAgCZYjUBua%2Bl%2BAhgCMAtAFcoADj4gANCAEicONCiwBtACwA2aZvHTxAZmkBOAKz6jARkvbrl6dfUOADPcvOH7z2%2Bcf39sxdjbxc-SwB2Fz1-T3MvdUjjaIiXOOdo3xdpBOzbSzjLDJ9k21dstMj3AtLsyssAJhNE4PdEyucrMvjSty9rDNyXXrC9LWzGrwMjMZjrEcHZ%2Bo9jdpaGqKGs-tTPHsHjNeGXCec06dK88xmbHfcWrvzdpqDPRvUrk88M6s2xg5C5sdbh0FjdrFc8qU0vdej8Vi9rG8Pi4ALoAXwxsjAAAd0DA4MoUCQ6CA8IQSWQKFQYLRiIwWGxONxeIJRBIpLJ5IplGoGp0TNIDE5rHU0vZxE54UlYoKnKY9AYJmDLMKUjF1MLlrKZVVPH4Qe4ivpenVenshdJ5YKlXlVe17BqssELdZbc9dYbbn0QZpTQjnMF4RarYrtYC7HrNhbHV5naqlZqCmFtOJ2mlky4nMGFW9gupRqNNQKXetPSKXJ0kzLs9aTPYSwnNq6nh6Hk53q8NuX3JXIx3wV8m%2BkW2ULcZpkW452y2qDadI4ZNvDHCZ7k5dF7VeYa6HjPX29oxxOnWHrIPZirPInQk3HjvGnuHPUjKGXc4TmkjQP79r1G9LueXTDs2MTRlmjQlr0Npekc35yjmT4vhB8bupeA4Xlm8G1iWBRfsBYKjuBT7bhM9TmOOWxkaiGJorI2J8CQ9B8BAaBgAAVtQ5AkmSRCgJSlA0CS9KsJg7BcDw3CsmIkgyHIChKComCqHyJ4lssqxRlhr6Snoy6PLq-xgapqpfmh%2BnzhGgI-tGozaPmgzqFOMZag2V5erpdTmlp0Ert2ZTOcWW6rm5Hqlsq27eYhJ5Tu4%2Bq9AqkUlt8I71iccWDkZsaBSYyRpl2mTWSZXrmg%2BuXAhkHiZVqMVhZq8XAr0U4hshgE-KBSqNheyUXk5k7ZWWFl9DchXTmhDyQg1bmhh2-alvh7S9oCs1iqhkpruUN6hURYzTVc5HrTE-ytLWO3tn1MXvgCY2Bp52rNaenXjSOK0rrtG2Il2s6LfEBQrXpa2Zu9mRbSdh5Iu9lhrNeIGjv%2BYZag0Vx9W%2B6XbBuF4nLBwMPMs9wvXekUqVlU6aEF2yzPhezuABOTLpkek%2BW2G16bdEYjcYcoOnZtnZAl2TndqpM6oUQ4lEONPtHlzbs3KHhjPZ8t8wFgaC2TIsU2LFMS61KUQycZU9l6cu-YBxS6zLlpc7zDlKwLrm%2BU9MP45hloIWOsuDKYdnc7%2BdsoQ7ZrPbe7YFPrngLUbEO4aL5uJZKHvy3mPOOb70WntHGux672Hx5acMK9opgvmdadJcVmnZ9pJhyuc1uK-DAqI-zxktvUUEV-db6HJts5GlV-XY%2B3F76qjsZ47eEWV6R-IqzhpufXsHZHc4dXBcdFumFbphw6YLvK-1%2Bnq0Bmv%2BSbmeHWsh5x9Xlq117nv7ieTd9FR7jopi7BEiSzBQOgJAwKgAAniSPg2JsRgAABYwAALb4G4gQXipByACRpEJJgIkxLMkksIaSHI5LckUqoTQlUjAbnCMEX0%2BgnDiGCOIDwmhnQnFVKUe4ehNCfGIYDGGrDayej0vqUhj9h6C0%2BBQ-Uq86b0NEQKThdxbzaCDA%2Bda-0dRPU0EItUBFwb3wtNNSI7C06yOAoNfUkRQwBw2Oo%2BG%2B0rqVSIu4VUq93CNCsbo0U88ZxU2cFLG4fx3HoUdneSIORnGoWSkdM8S08hKgEdqPROhpFiP9IHRRkY6Ywh0Bo7qDw1hKl6MwuJSjbG63DDcVxqpx6xRHOuHwo9wkZNmpU4GBEXbxIMcTQU-ij5mxhj4Hx3suFlEkZ0k8nCQkryXO0KRozljJFqU%2BVKN49IKOCWfbpC8hz9L1iFY%2BIRhn9nprdeE5SuGRPWa9dciSdAj3crww%2Btg275XsCcqpoVQ4bGXI8%2B6ETYIEV%2BQBC0BiDBdLwifPp5c-hzM2o84F1zaibUGmw6RYzEhQteY89p9C5btAKXIz0mL360RAPgKAAhv6-zQP-IBJIADCSARBUhQGAJkEl4HkmIPxaktIGDoMZOJFkOD2SyS5ApNQsjHgROhmFbQmLG7GMDrubu3Yhpg0ySdPQph7iqULghVsEE3i4yunUDMoYDGuNzHXRZRNqrunlSFXxywFFKs0Saj81Y0qoViRhI1qjogwqYcCToWYjDGDsvYTVacfnh0jNLFxizTCRAjVlZ%2B%2Bo5VKmNWvAiBQjjmImfwhFRpKEDRscddQcsrXPkjc6jNsbsiCJOsEJNCNX5YvhQOSVXpoKyq8Jw6UyqJqWUmHkyMVpl71JcPotwlaHGeoLZsItxiS3eOIgk0Z7Rx3HQppVaemaTQxrBC2xulao3KtdWqqx5rsiMJ0EhQUl9gQZIMNezu97WwZO-C0Q9KKcrRpAsqI4BKaKyHQWgAAHuxblpIEEUmQVytBDJRIsoFWyGSnJ5I8iUjkHI5i5oeTXrDIErZTIkQWT6nDN192qr-VaiyAZRr5KeDh0ojifWGxnUxwZizQ2ClKOE3Sqq6bhPcbmqsHGZ1vN4ZdSyxjR4HmojRIlKB6WUEgz-P%2BACUDAOIAAan4IA5TzL%2BWIJ4jBqkgk6S8sQ0Z-ggrUP4NFUpcVJaxrvObLKppuSroFNfHmOyEcZwBDw56P4awTZPstFq797aoadqeN21tAS0XDTePok4hLZDafoixZlyguBMo4myxBnLzM8oQ5giSNmUN4JFRh5SXQlj0ftQJ51YQfi5qhcM01XH-GPMBIZA12RFkXv1VFZNY1A7KtVNu0bNrQr6javOQT%2Bgz5M3CJ0Dw90U7Jqok2ldTb0sgEy8xViSHjPQY5bBkrIBhJ8qwZV3Bwr0OEKc5mqVXbpFvsa75ZLFgY4X0YycTqkS6M%2BeFqC3Wy0-tDPveF3b76GsfUHd5sOF4qOHKePCXbr4RuKuKehH7J7jEZCNBEqExSuuSewjjh8Pgqd0%2Bx-TndImbxWhTo6BnfWNIxBDE4cIqofBTdrOjYHQiqIBQZxL6ndOVLM6qVaUw032cxNtRknn0g%2BezvajoNFhEV3i6l5LxnUVZeZHl4spXaSudlDV%2BIN1y9JR1E1NN23AJddN310bw3HPK0m42xqkbFvOfJMrtQh8zROMbFDC76Tou0ie4fEYXbya7W1oaBtrVgYWvCzRw7mN2NC04s13OIb5vpta-UCX1d5jp2zYaxT3NVtXlPTpp%2BKtePD49P8rx130w-ANeuOpYPFen5fuxTKDtoV3tbFbYuc%2B0ORxG8R8OKU76JnSYqsHNVgLC%2BDthFGdNqiGNjiyIb0KXjghrZvC82jdiT9S74aimOLzYxW6EdNjng1z8yisSpQnxOnmZpk6Dp95x5Z6jrKI1rF5qrWq57hj57zqF75psb1Zx45DsIHYQD4BIACB8D4BgAkDUCQYmYXZmaoIWZlanb3ZCpoYEJqBWjfa9AKo7pZQzQrarI-or4TpAyRQK7Wy7wRYnisGqLsHSicGlrmCbzcG%2BpTwCEsF7TCHMx4bLzsEpz3TibmSjByyFjqojIW5s4Fi6HhoZ4bSQ7iEcHh5mG8FqFr4aHZBaHNzTQKjBLbRJzWywrD5w4mFsGKHPDKEbSSHWFkzDhlqWj2H8EW78Hby6FEQJqWiHjBJGGCHyEBIiFKH3DsFRGBHSEhG8H2ThExGNBRHuExGJr1gJGyFahCEpE%2BFiHLodhFwyHqGt45FhElyhi5FOEOGFE%2BzuGJFyFRxcGzRUwI6%2BJXCNq6o2HNH2F6GdF6GNplGDYVEChVHmTsG9JPgZj1F%2B6SZBGaF1zbSzExEbbbjlGeErEVAQzDGbESHhoTG7F2GhF5z7G1g6LOEvGFEQSnHGHnGDELZOJ0bqhjGNGTEbAhGqHHjTSuH2TFEvGJ4vhfFJEDFmEwz-ENISHbG5r3EtFPEKwxHxFdFPFFEIn9GmF1F-FDhomWzAlYkbZhFvAuF1yHEvGcyGFLF5jJGrFAzDqlI6rYQX5rCmQoR6RhZ5jbTkR1AdQAGmG9b3IUkEmaDd5zZcHhBtDBSz4ykLY%2BAX5hD-IEnhaz5ARWAi61jiDmCX7hYW7R5nh9pnJ5AOhETkIbGkbIFHCWnkQGwqrRr7wUKqk8mrRQ7aGg7hDzZuSpKLhIF3iil8na72o%2BDpgmkho1qRl6kX6YyfSmRk7-CpLhCmT2h3oEntpJkcnOzAiFHfHFm-GEZnLXEIjVkhAvrq4hkrjZl%2BilL1hRm5pZ6DrvK1F9EgHT46Cair4hmpIhGI7jaEZMwDhLxKr4QMaQ725ync4TGD4OzlHV4zzZwMFXRUY14CjslIlknmH4YqHjE7HZHTEHHRENpuHEk2o-FmGiEWFHlWF3EXnPGOHXmQlxGsmeEHmkmpG%2BHpH%2BG3HnmJYPG4k6EwnflEmLF-leEKFLxpGVmZFvngVgmBlvBMntG0m-nGH-neFIVAUoWJ5oW2EYUEnQlvHtFYV4VpwPlHnrFp5PAzRnmYnvmQWfnQWFHBKzF9n7kIXVFDFNgjF2TonUkcWYW3kEn3xUVwX4WCWcnCWLA1kBFkVTEfm0XcWWg1x0XbZx7Ew6594VqbmZ6u5JYhzj4HRASq4rn%2BnHSeEporreg-rSbGW8J7mBjIWboGhmR7pwHGy7qfQMZqEiwqJgkVmPneUvkOj8VmXr5eYyF9rL7PmJrGFyIqLIFVibY8ymASGdBalslVm6kHJh7%2Bit4NCgU4ZBaXgRWHlrFSZ1nNgeH4Xh7LwlXOY9JnKExhWO4QWRWMUtJLmnxXryWURpCEoKayDUAwB8BwDEjEBqaUoaZaa4B8AcBQCUg4gIAQCFamYoKQY3ZWZ3ZSTUH2a1bPgtCPiFC0IeA5nq5uD8j1A1AeCvUOBGCX7hAuJ6Au5vVyzaB-W-iCjSCA2XUODXU0LLbSBg2QxuCQ0NCRCA1TD6B3UpjrjBCg3haw0OCQ1CweAw0Q0UJOD41Y2E2Dkg3Q2k1w1E0U0E3U06DmAk1XX0142U3M040UKM1s3g0s1c100c3k1M080C2s0WgSjc3Y03UOCI0U1hBPAu73WLhC2S2Q381S1q243tiRAa2NoCkS1k063Q2NDa2RDhD2CA2eZfX6Chay0OBOCG1vWXiG32CG3qBWD20y1vWG2X4biaDmDi3MWG1B1U0C3O3a0h1S32TrCG2PjcbB3s3q0R2Q3K1k3R1J3BDx3C1S2SGPKZ0q0tBGB52p2F16CG1RHmlGnCj1AQSfrmBF30310C2OmN3q2SikSlCF3p3Q0u1d0ix11d2G1WCND1A-Wj2eBGnD2o36303WAZ293V3T1N2L1S0qQt243D1d38HGCNAp0N0SF81d3iDPK72h0D1n0J2Q1u11qWjh0X02286FGd133d3L2q0D2VANbO393P3O31D22921VP1Z1v0-293-3P2OlX0GC4WOl0JOkqQqmv1z2gPP2ehr3IPAMZ2liOkpB5VPFm0ODQ0WQGA90oOYPCzgPkPO3ziG0MKWjf3kOQzCiIMrhB2WDu1AP51IPOk%2Bh74Rq-3TAMNcPoMhDO1ngiPSh4OzSRAB0NamncNiMPgb1kNcNyK-2kPkPD4bhUQiOVXcNjAiO8HhZtyVCwoiOLiu3h5UQGDaBW2G3i0GAmzUNJnFw3r6OcMG3n1UNn1xD9hJriOQwOBWhjJCOePP2aAeP02A13WkIX5sKl1d0KkmDaA62TVEqnb4HkB4AQAQZ7UkEHXwYYKUGnV2Y1aEKfbjkMa1rDIMwlKXi5pA6FWg5Cz47g5MXODaw1MSl1OWUswthniw5arxDBJvAjYtMHpDwEbWrQhfZmR2SVQ02tN-Z-IuDaw%2BVtZ5hWxFpNVSa0ZD0kZ-htqGrAHZ61gnrehuqGz17MEIzLpn6NGeXLHBJmJlVVK1NMW1Xim-r-p3JYx%2BpWqHzdOVNNburCyFVa7CLkyDT8557vqenTn2LmQ%2BA0a4rKhKgSGjDPNcH3PXAZy7LrEzCDyDjjI6mZpXC%2Bno7jlUyfOoSswDOA6JW7gvP5RrIDIdJYbMuX6hLV6MHfP2I4w6zblwFwtnoSY4akup6AujTclzNDhl7dUeW8vlg4b4wDop4FQyvTapL45pnLxpB27XqQtHwFAwvCu3ibGIsFCVI3CLk4b%2BU-Yon762qrnSqb6EsCUcsJlDgov9PRIyis5YvrMsUARQtdWLylB1JHOksRLkvOuoSMxVN3gMtI6SbOqryy4XOJUZWsyDQ5plU2n2sCZTLxs9MyjusqxdOjTUuRSVtUtuvloj4GU7ZDOowjEyvI4Io%2BCvO9wA5BVwGXMgj7ZAYgAbWUCZMIDZO5PEDEF8SXZkGlZFPWYlPVZPa8i0aeYpup4%2B7oseKUybLlzV4kahJCsg413k1LPnwrPUxluSwQp1DdQrODPT4zPAvfa7m3pN5duRwxDbNYwDsfvWPJt%2BUvCg5Quan5lJ6tthDtu9uftAh9OeKSaoy7NVg-utmZuti94zaNy4a-pzioePDfJ76hsbIUxbJgkBD8ju59mTVAA)

Hope this helps.

**Comment by jamesscottbrown** [comment]
The  value of the `value` prop corresponds to an entry in the `collection` array, not just the `id` of an entry (which could be accessed as `justValue` but is read-only).

Try something like:

```js
let value = colllection.find(user => user.id === data.currentUserId);
```

And:

```js
<Select
   placeholder="Choose user"	
   itemId="id"
   label="name"
   items={colllection}
	bind:value
/>
```

And then either respond to changes in `value` or listen to the `on:change` event on the `Select` component to handle changes in the selection appropriately.

**Comment by rob-balfre** [comment]
```svelte
<script>
	import Select from 'svelte-select';
	export let data;
        const collection = 
    [
         { id:1,  name:"John Doe"},
         { id:2 , name:"Jane Doe"},
         { id:3 , name:"Richard Roe"},
         { id:4 , name:"Rachel Roe"}
    ];

	let value = collection.find(c => c.id === data.initialUserId);
</script>

<Select
   placeholder="Choose user"	
   itemId="id"
   label="name"
   items={collection}
   bind:value
/>
```
