### ISSUE TITLE
Blue square on second attempt to select an item

### ISSUE THREAD

**Issue by fedeperin** [rob-balfre/svelte-select#666]
Video of the issue:  

[Video](https://github.com/rob-balfre/svelte-select/assets/83504427/dc08683d-fbb0-4dcb-bcbc-0fc3cf249953)

I'm having a problem, the second time that I try to select an item the options change it's background to a blue one and they are no more selectable.
The code is the following: 
```svelte
<script>
    import Select from 'svelte-select'
    const items = [
        {
            label: 'Cats',
            name: 'cats'
        },
        {
            label: 'Dogs',
            name: 'dogs'
        },
        {
            label: 'Rats',
            name: 'rats'
        }
    ]
    let value = items[0].label
</script>
<Select
{items}
clearable={ false }
bind:value
/>
```

**Comment by rob-balfre** [comment]
`<Select itemId="name" ... >`

**Comment by jamesscottbrown** [comment]
More explicitly:

Unless you provide an alternative field name as the `itemId` prop, `svelte-select` assumes that the id of each item is contained in a field called `value`. Once an item has been selected, any items with the same id will be highlighted. In your case, selecting any item hghlights all of them: the field is missing from all the items, so they are all treated as having the same id (`undefined`).

**Comment by fedeperin** [comment]
Thanks, my problem got solved.
