### ISSUE TITLE
Webpack Module not found

### ISSUE THREAD

**Issue by gponty** [rob-balfre/svelte-select#667]
I use webpack 5.70 and i have this error :

`
Module build failed: Module not found:
"./node_modules/svelte-floating-ui/index.js" contains a reference to the file "./core".
This file can not be found, please check it for typos or update it if the file got moved.
`
Any idea ?
Thank you

**Comment by mikiastilahun** [comment]
Add the rule below to webpack.config.js file
`  {
        test: /\.m?js/,
        resolve: {
          fullySpecified: false,
        },
      },`

**Comment by gponty** [comment]
Thank you, it's worked
