### ISSUE TITLE
onClearItem in multi select event needed

### ISSUE THREAD

**Issue by an4morph** [rob-balfre/svelte-select#67]
I have an array of items
`let items = [{ value: '1', label: 'one' }, { value: '2', label: 'two' }];`
and empty array of selected
`let selected = []`
When I select one of this - on:select event trigger and change selected array

But, when I remove one selected item - nothing happend, because I have no access to the event that remove this item
You have only two events - select, and clear all selected

**Comment by rob-balfre** [comment]
@an4morph yeah looks like we're missing an event for clearing an item from multi select.

You can achieve something similar without using :bind https://svelte.dev/repl/c6b4c4ee1f0a4d2c9c3dbe6cfed52397?version=3.6.2

**Comment by rob-balfre** [comment]
v2.1.0 will fire correct events on clear
