### ISSUE TITLE
Inquiry: Any plans on updateing for svlete 5?

### ISSUE THREAD

**Issue by ar4hc** [rob-balfre/svelte-select#680]
This package works really great, 
but not in svelte 5, i'm afraid.

Just did a quick check and mouse isn't working for selecting items, but keyboard does.

Not sure what's wrong, and nothing in the browser console, so ...

Before digging into this, i wonder if there is some effort already ongoing?

**Comment by fsoft72** [comment]
I noticed the same thing today,
I think it is related to this issue on [svelte5](https://github.com/sveltejs/svelte/issues/9777) issues page.

I had to revert back to svelte 4 for my project.

**Comment by frederikhors** [comment]
Svelte 5 is in Release Candidate state starting today! ♥

**Comment by frederikhors** [comment]
Did you find a way @ar4hc @fsoft72 ?

**Comment by rob-balfre** [comment]
@ar4hc @fsoft72 I'll take a look soon hopefully, day job is v busy and 100% Svelte 4 so not had a chance

**Comment by fsoft72** [comment]
> Did you find a way @ar4hc @fsoft72 ?

@frederikhors at the moment I was forced to revert back to Svelte 4, because I have a very big project relying very much on svelte-select.

**Comment by fsoft72** [comment]
> @ar4hc @fsoft72 I'll take a look soon hopefully, day job is v busy and 100% Svelte 4 so not had a chance

@rob-balfre    I hope you'll find some time. Your component is very powerful and I want to use it also in my future projects  :wink:

**Comment by frederikhors** [comment]
@rob-balfre https://github.com/sveltejs/svelte/issues/11365#event-12645769864 is fixed!

**Comment by frederikhors** [comment]
@rob-balfre I think we should open it again, it doesn't work anymore with latests releases:

https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACoWRPW_CMBCG_8rpFi9G7CZFqpi6VWIkDMZcilV_yXaCIMp_r0wilMDQ8X3kx6_v3GOjDSUUhx6dtIQCP0NAjvkWSkgdmUzIMfk2qkKqpKIOeVs7AG2Djxn2ZEhlaKK3wEZjlR6MbWpXDirvUgadySb4gENBAH0nTUsCmLp45Y3MxDgYeSIjgO1m7Cf6Nghg-ytRZgN_0YO-3-VM_Z7yU5Odj7d3T8nfReMYl2UcxkHkyZCARppE7_dcdEiLp4_5v36taKUiSTtzvxTBbmIvYxf7uKldtX7-QO2qaff9Y7cDrLfI0fqzbjSdUeTY0nAc_gD3U2Kl5gEAAA==

@ar4hc can you please change the issue title from "svlete 5" to "Svelte 5" (to search it)?
