### ISSUE TITLE
Not working as expected after upgrading to v5

### ISSUE THREAD

**Issue by EricSSartorius** [rob-balfre/svelte-select#688]
After upgrading to Svelte v5 (RC), among other things, when clicking an item in the dropdown list the list closes without the `on:change` firing. Are there plans to upgrade this package to work with Svelte 5 any time soon?

**Comment by rob-balfre** [comment]
Think this is fixed already. Updated to latest RC?

**Comment by EricSSartorius** [comment]
@rob-balfre My apologies, looks like I was using `5.0.0-next.115`. Updating to `5.0.0-next.123` fixed it as you mentioned. Thank you
