### ISSUE TITLE
Is there a way to identify selected option id?

### ISSUE THREAD

**Issue by sinistra** [rob-balfre/svelte-select#71]
I've passed in a method to loadOptions that returns an array of objects containing 'ID' & 'Name'.

code looks like this....
` const optionIdentifier = 'ID';
  const getOptionLabel = option => option.Name;
  const getSelectionLabel = option => option.Name;

<Select
    loadOptions={getCompanies}
    {optionIdentifier}
    {getSelectionLabel}
    {getOptionLabel}
    {items}
    placeholder="Search for "
    on:select={handleSelect}
    on:clear={handleClear} />`

handleSelect successfully displays option.Name from event.target.innerText.

Is there are way to reveal the id/value of the selected option?

**Comment by subpx** [comment]
I think what you want is to bind the selectedValue prop.

`
<Select bind:selectedValue />
`

**Comment by sinistra** [comment]
thanks for your help.
