### ISSUE TITLE
Tick is not exported

### ISSUE THREAD

**Issue by Mattinn** [rob-balfre/svelte-select#75]
Hi Rob, I got this strange error when trying to integrate you component into my svelte 3 & sapper app 

```
✗ client
..\..\node_modules\svelte-select\src\VirtualList.svelte (32:18)
'tick' is not exported by ..\..\node_modules\svelte\compiler\svelte.js
30:
31:   // whenever `items` changes, invalidate the current heightmap
32:   $: if (mounted) refresh(items, viewport_height, itemHeight);
                       ^
33:
```

Have you run into this before?

**Comment by rob-balfre** [comment]
@Mattinn what version of Sapper?  Also are you using webpack or rollup?

**Comment by Mattinn** [comment]
Im using rollup, ill see about updating them but current version are: 

```
    "rollup": "^1.12.0",
    "rollup-plugin-svelte": "^5.1.0",
    "sapper": "^0.27.0",
    "svelte": "^3.0.0"
```

**Comment by Mattinn** [comment]
The actual version are: 
``
   "rollup": "1.20.3",
    "rollup-plugin-svelte": "5.1.0",
    "sapper": "0.27.8",
    "svelte": "3.9.2"

**Comment by Mattinn** [comment]
Ah you can close this issue, the problem had something to do with an outdated build script
