### ISSUE TITLE
CreateItem not working

### ISSUE THREAD

**Issue by thiagomagro** [rob-balfre/svelte-select#76]
Hello guys.
If we enable the isCreatable and set the CreateItem function, it will be invoked for every keydown, and when we create on the "Create Item" option its firing the createItem event twice.

**Comment by rob-balfre** [comment]
Hey @thiagomagro got a REPL example?

**Comment by rob-balfre** [comment]
Thanks. CreateItem will only fired once now in svelte-select@3.0.1

**Comment by Bighamster** [comment]
The bug is still present in 4.4.1

[REPL](https://svelte.dev/repl/f5e34a60da28458f9826dab5fb959238?version=3.37.0)
