### ISSUE TITLE
isVirtualList + isSearchable can lead to a blank list being rendered

### ISSUE THREAD

**Issue by JimFung** [rob-balfre/svelte-select#77]
Setup: A select with many items (mine has 10k+ items). This select should have `isSearchable` and `isVirtualList` set to true.

Steps to Reproduce
1. Scroll to the bottom of the options dropdown
2. Type into the Search Select

Expected behaviour
- I see the reduced set of available options

Actual behaviour
- I see no options rendered

What I think is happening is the Virtual list is not scrolling back to the top of the container when you start typing. The options are still being rendered, you're just so far down the container that you don't see it. If you move the scrollbar back to the top you'll see the option. In addition, you'll see the size of the scrollbar increase, which I believe is further proof in my hypothesis.

**Comment by rob-balfre** [comment]
Thanks. Fixed in svelte-select@3.0.1

**Comment by JimFung** [comment]
Thanks for the quick fix!
