### ISSUE TITLE
better document selectedValue

### ISSUE THREAD

**Issue by jsfenfen** [rob-balfre/svelte-select#82]
I noticed something odd (that was super confusing at the moment). If you bind:selectedValue you can apparently set the value initially by setting selectedValue to the option id, but that doesn't work to update? 
Example: https://svelte.dev/repl/f556155a3a9f4197af68df21cf2626e2?version=3.6.2

The above was, I'll admit, user error, it seems like I should have been passing in the item, as illustrated here: https://svelte.dev/repl/a18753cd4fd14f7b8d67153c234dfa78?version=3.6.2 

Not quite sure what the best fix is, maybe just in the documentation? I found the first example confounding enough to write up this issue, though dunno how many folks would get bit by it.

**Comment by rob-balfre** [comment]
Thanks for the feedback. You're right it's a bit overly complicated for
newcomers. I'll reorganise the demos next week.

**Comment by rob-balfre** [comment]
Fixes in v3.0.2 release
