### ISSUE TITLE
Select does not bind Value correctly if selectedValue is set in onMount

### ISSUE THREAD

**Issue by muellercornelius** [rob-balfre/svelte-select#86]
I am using Svelte Select on different pages. 
When i navigate away from the route and come back the input is lost (this is fine) 

Thats why i save it to my Store with the on select method
`<Select {items} on:select={() => ProblemWhoChanged.set(selectedValue)} bind:selectedValue></Select>`

When navigating back to that page i have an onMount Event to reassign the value from the store:
```
onMount(async () => {
        selectedValue = $ProblemWhoChanged
        console.log(selectedValue) // this prints the previous selected Value so thats fine
    });
```
Even though the variable is set correctly the Select does not update to reflect the value.

Just for fun I added a buttton on the same page which triggers this function:
```
function update() {
        selectedValue = $ProblemWhoChanged
        console.log(selectedValue)
    }
```
As you can see they are identical. 

When i trigger this update function the value from the Select changes to the value from the Store.

Maybe its a problem about Timing? and onMount is too early? I dont know. Do you have an idea?

**Comment by rob-balfre** [comment]
@muellercornelius you can bind directly to the store value:
https://svelte.dev/repl/4053e1ba382841bfbf203d13a2cedfa1?version=3.12.1

**Comment by rob-balfre** [comment]
With you exact example it's just a race condition with onMount.  Use await tick if you need to in future...  https://svelte.dev/repl/4a51fa8cf4b644aaab077d634b981e31?version=3.12.1 

Please leave this ticket open though as svelte-select should play nicely with OnMount.

Thanks :)

**Comment by rob-balfre** [comment]
Had a little go at debugging this but I think it's just the way Svelte works.  🤷
