### ISSUE TITLE
<Select> is not a valid SSR component in Sapper

### ISSUE THREAD

**Issue by hdeyana** [rob-balfre/svelte-select#87]
i'm using sapper, if you install it with npm i svelte-select, and use it.
you will get this error

`<Select> is not a valid SSR component`

to resolve it, just **install it in dev dependency** 

>  npm i --save-dev svelte-select

relate to this 
https://github.com/sveltejs/sapper/issues/774

if this is good way to solve, maybe you can add in readme ?

**Comment by rob-balfre** [comment]
Thanks. I'll take a look.

**Comment by rob-balfre** [comment]
@hdeyana strange, I just tried adding svelte-select to a sapper application and didn't see the error.  What version of Sapper are you using?

**Comment by hdeyana** [comment]
@rob-balfre try in slow 3G connection you'll see the error, then error disapear.

**Comment by rob-balfre** [comment]
@hdeyana are you using webpack or rollup?  If webpack make sure you do this.. https://github.com/rob-balfre/svelte-select#configuring-webpack

**Comment by hdeyana** [comment]
@rob-balfre im using rollup. 
here my screencast video.
https://drive.google.com/file/d/1_J1tmXBeWEqL1laM8Sg6qKrL20drNCe8/view?usp=sharing

**Comment by rob-balfre** [comment]
How are you importing svelte-select?

**Comment by rob-balfre** [comment]
Working for me... https://svelte-select-sapper-demo.robertbalfre.now.sh

Code @ https://github.com/rob-balfre/svelte-select-sapper-demo

**Comment by rob-balfre** [comment]
OH WAIT!  I SEE IT NOW!  I will debug :D

**Comment by rob-balfre** [comment]
Updated README, thanks for spotting that @hdeyana  👍

**Comment by softwarerero** [comment]
It is also possible to render the select only on the client:

```
{#if (process.browser) }
	<Select items={items} ></Select>
{/if}
```

**Comment by shailesh345** [comment]
Thank you @softwarerero 

{#if (process.browser) }
	<Select items={items} ></Select>
{/if}

**Comment by Absleepy** [comment]
```
import { browser } from '$app/environment';

    {#if browser}
    <YourComponent />

    {/if}

```
