### ISSUE TITLE
list width isn't correct

### ISSUE THREAD

**Issue by kovapatrik** [rob-balfre/svelte-select#88]
If I get it right, the list width will automatically set to the parent component.
So if I use the Select component like this, my list width should be 50% of the parent div.
```
<div class="mb-3" style="width: 50%;">
          <Select items={alldata} isMulti={true} bind:selectedValue </Select>
</div>
```
But if my list has an item, which length is greater than the list width is, then the list width will set to this item width and the list will be outside of the viewport. How can I overwrite this behaviour?

Edit:

I have solved this problem by adding the line at the arrow in the List.svelte file at the 264th line:
```
.listContainer {
    box-shadow: var(--listShadow, 0 2px 3px 0 rgba(44, 62, 80, 0.24));
    border-radius: var(--listBorderRadius, 4px);
    max-height: var(--listMaxHeight, 250px);
-->max-width: var(--listMaxWidth, 100%);
    overflow-y: auto;
    background: var(--listBackground, #fff);
  }
```

**Comment by rob-balfre** [comment]
@MatyiFKBT thanks for the PR. If you could update the CSS variable's default to be `inherit` instead of `100%` then it won't be a breaking change.

**Comment by MatyiFKBT** [comment]
@rob-balfre Done. Check the latest commit.

**Comment by rob-balfre** [comment]
Unfortunately your PR doesn't fix the issue.  The list width is controlled by JS.  I'll have a look at adding an extra prop to control this.

**Comment by kovapatrik** [comment]
If I use the --maxListWidth like this, I can set the list width to the "maxWidth" variable.

```
<div class="mb-3" style="--listMaxWidth: {maxWidth}">
          <Select items={alldata} isMulti={true} bind:selectedValue></Select>
</div>
```

**Comment by rob-balfre** [comment]
v3.1.0 Added prop listAutoWidth - List width will grow wider than the Select container (depending on list item content length)

**Comment by samal-rasmussen** [comment]
listAutoWidth is great, but I have some content that is rather long, and I've love to put a max width on it, but listMaxWidth doesn't seem to exist.
