### ISSUE TITLE
Error on select "Cannot read property 'children' of undefined"

### ISSUE THREAD

**Issue by SemperPeritus** [rob-balfre/svelte-select#92]
svelte-select crashes on select with any items, with and without bind:selectedValue. **Only** on dev build.
Versions and stack: svelte 3.12.1, sapper 0.27.9, svelte-select 3.1.1, rollup 1.22.0.
dev: `sapper dev`
prod: `sapper build --legacy && node __sapper__/build`
Script:
```
  let form = {
    player1OfTeam1: null,
    player2OfTeam1: null,
    player1OfTeam2: null,
    player2OfTeam2: null,
    winner: null,
  };
  const winners = [{ value: 1, label: 'First team' }, { value: 2, label: 'Second team' }];
```
Html:
```
<Select items={winners} bind:selectedValue={form.winner} />
```
Stacktrace:
```
VM108231:57 Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at removeNode (<anonymous>:57:31)
    at Object.block.d (<anonymous>:185:9)
    at destroy_component (index.mjs:1235)
    at List.$destroy (index.mjs:1342)
    at List.$destroy (index.mjs:1432)
    at removeList (Select.svelte:424)
    at Select.svelte:220
    at run (index.mjs:18)
    at Array.forEach (<anonymous>)
    at run_all (index.mjs:24)
```
Example in [this branch](https://github.com/SemperPeritus/foosball-rating/tree/svelte-select) (`svelte-select`, last commit). You can just run `yarn install && yarn dev` in the `frontend` folder without backend and DB. Page `/game/create`. Without API dev build is a little inhibited and page will loads about 5-10 seconds.

**Comment by rob-balfre** [comment]
@SemperPeritus I've checked out your branch and I can't see the error.  I get a load of API errors but svelte-select renders and I can select an option. https://streamable.com/owtj4

**Comment by subpx** [comment]
@SemperPeritus I've had a look too and don't get the mentioned error. I would delete sapper files and node modules and rebuild/install.

**Comment by SemperPeritus** [comment]
Sorry, the error does not occur without the [Svelte Devtools](https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn) extension. I was wrong to not check in incognito before the creation of the issue.

**Comment by jakubblaha-ids** [comment]
I can confirm that this issue is still present when using Svelte DevTools. What should I do if I wanna use it?

**Comment by aislanmaia** [comment]
I'm getting the same problem but after HRM through Snowpack. 
And reading this thread I discovered that the problem is related to Svelte DevTools. 
Disabling it, the problem doesn't occurs anymore.

**Comment by hazg** [comment]
There was a similar error. Removing Svelte DevTools helped.
