### ISSUE TITLE
Select component broken when combined with another component

### ISSUE THREAD

**Issue by markcheno** [rob-balfre/svelte-select#93]
I implemented svelte-select to retrieve data via async fetch.
The component works fine standalone or even with multiple instances on the same page.
But when I introduce a Tradingview Lightweight Chart (https://github.com/tradingview/lightweight-charts), it will not work when the select component is created *before* the chart. The select works fine when created *after* the chart.

Minimal example here:

https://svelte.dev/repl/22e3f52ae6d746828ebba83d0aa00f63?version=3

The top search is broken, the bottom works fine. Remove the chart component and both work fine.
Obviously something is colliding somewhere, but I can't find it after much effort.

Any help would be greatly appreciated!

**Comment by rob-balfre** [comment]
I'm away this weekend but from a quick play around on my phone it just
looks like the chart is capturing the click event when you try to select an
item from the dropdown list.

**Comment by markcheno** [comment]
Thanks, I'll look at it from that angle..

**Comment by markcheno** [comment]
Btw, something seems off with the z-index as well with the top component dropdown. The chart crosshair overlays the top dropdown. It does not do that with the bottom one.

**Comment by rob-balfre** [comment]
Yeah the dropdown list will only have a z-index of 2.
https://github.com/rob-balfre/svelte-select/blob/master/src/Select.svelte#L483
try this...
https://svelte.dev/repl/9e14d0942f984a67917508b84c059396?version=3.12.1

**Comment by markcheno** [comment]
That takes care if it. Thank you! I spent days trying to figure that out.
