### ISSUE TITLE
Clear after item selected

### ISSUE THREAD

**Issue by northkode** [rob-balfre/svelte-select#97]
is it possible to clear the input after I have selected an item? 

Side note: Would be awesome if the documentation actually show cased all the api calls and what you are intending.  The advanced demo just really doesnt get into much detail.

**Comment by rob-balfre** [comment]
@northkode yep you sure can just need to fire off an `await()` for it work currently...

https://svelte.dev/repl/f8198af9d51e4aecaf0832332a01614e?version=3.12.1

Docs can always be improved but its just finding the time! What do you think the adv demo is missing?

Hope the REPL helps!

**Comment by northkode** [comment]
@rob-balfre the advanced repl helps, but the doc's dont show how certain things work. For instance using bind:this=instance in order to clear items, isn't stated anywhere so It can be confusing at times. 

Each api items would be nice to have a little code snippet example in the github readme.

Nice work on the component tho!
